import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "psv-01",
    enunciado: "PERRO es a CACHORRO como GATO es a:",
    opciones: ["Felino", "Gatito", "Ratón", "Maullido"],
    correcta: 1,
    explicacion: "Un cachorro es la cría del perro; un gatito es la cría del gato.",
  },
  {
    id: "psv-02",
    enunciado: "MÉDICO es a HOSPITAL como PROFESOR es a:",
    opciones: ["Libro", "Alumno", "Colegio", "Examen"],
    correcta: 2,
    explicacion: "Un médico ejerce en un hospital; un profesor ejerce en un colegio.",
  },
  {
    id: "psv-03",
    enunciado: "LLAVE es a CERRADURA como CONTRASEÑA es a:",
    opciones: ["Ordenador", "Acceso", "Usuario", "Seguridad"],
    correcta: 1,
    explicacion: "Una llave sirve para abrir una cerradura; una contraseña sirve para obtener acceso.",
  },
  {
    id: "psv-04",
    enunciado: "RÁPIDO es a LENTO como ALTO es a:",
    opciones: ["Grande", "Bajo", "Pequeño", "Ancho"],
    correcta: 1,
    explicacion: "Son parejas de antónimos: rápido/lento y alto/bajo.",
  },
  {
    id: "psv-05",
    enunciado: "POLICÍA es a LEY como MÉDICO es a:",
    opciones: ["Salud", "Hospital", "Enfermedad", "Paciente"],
    correcta: 0,
    explicacion: "La policía vela por el cumplimiento de la ley; el médico vela por la salud.",
  },
  {
    id: "psv-06",
    enunciado: "OJO es a VER como OÍDO es a:",
    opciones: ["Sonido", "Hablar", "Oír", "Ruido"],
    correcta: 2,
    explicacion: "El ojo es el órgano con el que vemos; el oído es el órgano con el que oímos.",
  },
  {
    id: "psv-07",
    enunciado: "DELITO es a SANCIÓN como MÉRITO es a:",
    opciones: ["Esfuerzo", "Trabajo", "Recompensa", "Castigo"],
    correcta: 2,
    explicacion: "Un delito conlleva una sanción; un mérito conlleva una recompensa.",
  },
  {
    id: "psv-08",
    enunciado: "SEMANA es a DÍA como AÑO es a:",
    opciones: ["Estación", "Mes", "Década", "Siglo"],
    correcta: 1,
    explicacion: "Una semana se compone de días; un año se compone de meses.",
  },
  {
    id: "psv-09",
    enunciado: "LIBRO es a BIBLIOTECA como CUADRO es a:",
    opciones: ["Pintor", "Museo", "Marco", "Lienzo"],
    correcta: 1,
    explicacion: "Los libros se conservan y exponen en una biblioteca; los cuadros, en un museo.",
  },
  {
    id: "psv-10",
    enunciado: "AGUA es a SED como PAN es a:",
    opciones: ["Hambre", "Trigo", "Horno", "Comida"],
    correcta: 0,
    explicacion: "El agua sacia la sed; el pan sacia el hambre.",
  },
  {
    id: "psv-11",
    enunciado: "INVIERNO es a FRÍO como VERANO es a:",
    opciones: ["Lluvia", "Calor", "Nieve", "Viento"],
    correcta: 1,
    explicacion: "El invierno se asocia al frío; el verano, al calor.",
  },
  {
    id: "psv-12",
    enunciado: "PEZ es a AGUA como PÁJARO es a:",
    opciones: ["Nido", "Aire", "Pluma", "Rama"],
    correcta: 1,
    explicacion: "El pez se desplaza en el agua; el pájaro, en el aire.",
  },
  {
    id: "psv-13",
    enunciado: "SEMILLA es a ÁRBOL como HUEVO es a:",
    opciones: ["Nido", "Ave", "Pluma", "Cáscara"],
    correcta: 1,
    explicacion: "Una semilla se desarrolla hasta convertirse en árbol; un huevo, hasta convertirse en ave.",
  },
  {
    id: "psv-14",
    enunciado: "AUTOR es a LIBRO como COMPOSITOR es a:",
    opciones: ["Instrumento", "Partitura", "Orquesta", "Concierto"],
    correcta: 1,
    explicacion: "Un autor crea un libro; un compositor crea una partitura.",
  },
  {
    id: "psv-15",
    enunciado: "JUEZ es a SENTENCIA como LEGISLADOR es a:",
    opciones: ["Delito", "Ley", "Tribunal", "Proceso"],
    correcta: 1,
    explicacion: "Un juez dicta sentencias; un legislador elabora leyes.",
  },
  {
    id: "psv-16",
    enunciado: "TERMÓMETRO es a TEMPERATURA como BALANZA es a:",
    opciones: ["Volumen", "Peso", "Longitud", "Tiempo"],
    correcta: 1,
    explicacion: "El termómetro mide la temperatura; la balanza mide el peso.",
  },
  {
    id: "psv-17",
    enunciado: "ESCRITOR es a NOVELA como PINTOR es a:",
    opciones: ["Pincel", "Cuadro", "Lienzo", "Museo"],
    correcta: 1,
    explicacion: "Un escritor crea una novela; un pintor crea un cuadro.",
  },
  {
    id: "psv-18",
    enunciado: "LLUVIA es a PARAGUAS como FRÍO es a:",
    opciones: ["Nieve", "Abrigo", "Invierno", "Viento"],
    correcta: 1,
    explicacion: "Frente a la lluvia nos protegemos con un paraguas; frente al frío, con un abrigo.",
  },
  {
    id: "psv-19",
    enunciado: "DEDO es a MANO como TECLA es a:",
    opciones: ["Ordenador", "Teclado", "Pantalla", "Ratón"],
    correcta: 1,
    explicacion: "Un dedo es una parte de la mano; una tecla es una parte del teclado.",
  },
  {
    id: "psv-20",
    enunciado: "MÉDICO es a ENFERMO como ABOGADO es a:",
    opciones: ["Juez", "Cliente", "Delito", "Tribunal"],
    correcta: 1,
    explicacion: "Un médico atiende a un enfermo; un abogado representa a un cliente.",
  },
  {
    id: "psv-21",
    enunciado: "ESPADA es a VAINA como PISTOLA es a:",
    opciones: ["Bala", "Funda", "Gatillo", "Cargador"],
    correcta: 1,
    explicacion: "Una espada se guarda en su vaina; una pistola se guarda en su funda.",
  },
  {
    id: "psv-22",
    enunciado: "HORMIGA es a HORMIGUERO como ABEJA es a:",
    opciones: ["Miel", "Colmena", "Panal", "Flor"],
    correcta: 1,
    explicacion: "La hormiga vive en el hormiguero; la abeja vive en la colmena.",
  },
  {
    id: "psv-23",
    enunciado: "CIEGO es a BASTÓN como COJO es a:",
    opciones: ["Silla", "Muleta", "Cama", "Escayola"],
    correcta: 1,
    explicacion: "Un ciego se ayuda de un bastón para caminar; un cojo se ayuda de una muleta.",
  },
  {
    id: "psv-24",
    enunciado: "FRÍO es a HIELO como CALOR es a:",
    opciones: ["Sol", "Fuego", "Verano", "Vapor"],
    correcta: 3,
    explicacion:
      "El frío convierte el agua en hielo (estado sólido); el calor la convierte en vapor (estado gaseoso).",
  },
  {
    id: "psv-25",
    enunciado: "GERMINAR es a SEMILLA como NACER es a:",
    opciones: ["Vida", "Bebé", "Madre", "Familia"],
    correcta: 1,
    explicacion: "La semilla germina para dar inicio a una planta; el bebé nace para dar inicio a una vida.",
  },
  {
    id: "psv-26",
    enunciado: "TIJERA es a CORTAR como MARTILLO es a:",
    opciones: ["Construir", "Clavar", "Golpear", "Serrar"],
    correcta: 1,
    explicacion: "La tijera sirve específicamente para cortar; el martillo sirve específicamente para clavar.",
  },
  {
    id: "psv-27",
    enunciado: "ISLA es a MAR como OASIS es a:",
    opciones: ["Agua", "Desierto", "Palmera", "Arena"],
    correcta: 1,
    explicacion: "Una isla está rodeada de mar; un oasis está rodeado de desierto.",
  },
  {
    id: "psv-28",
    enunciado: "TERMÓMETRO es a FIEBRE como RADAR es a:",
    opciones: ["Velocidad", "Coche", "Carretera", "Policía"],
    correcta: 0,
    explicacion: "El termómetro detecta y mide la fiebre; el radar detecta y mide la velocidad.",
  },
  {
    id: "psv-29",
    enunciado: "LARVA es a MARIPOSA como RENACUAJO es a:",
    opciones: ["Rana", "Pez", "Charca", "Huevo"],
    correcta: 0,
    explicacion: "La larva se transforma en mariposa; el renacuajo se transforma en rana.",
  },
  {
    id: "psv-30",
    enunciado: "CACHORRO es a PERRO como POTRO es a:",
    opciones: ["Vaca", "Caballo", "Oveja", "Cerdo"],
    correcta: 1,
    explicacion: "El cachorro es la cría del perro; el potro es la cría del caballo.",
  },
];
