import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "psi-01",
    enunciado: "Indica el SINÓNIMO de \"diligente\":",
    opciones: ["Perezoso", "Trabajador", "Lento", "Torpe"],
    correcta: 1,
    explicacion: "\"Diligente\" significa aplicado y cuidadoso en el trabajo, como \"trabajador\".",
  },
  {
    id: "psi-02",
    enunciado: "Indica el ANTÓNIMO de \"escaso\":",
    opciones: ["Abundante", "Limitado", "Exiguo", "Poco"],
    correcta: 0,
    explicacion: "\"Escaso\" significa insuficiente; su contrario es \"abundante\".",
  },
  {
    id: "psi-03",
    enunciado: "Indica el SINÓNIMO de \"sagaz\":",
    opciones: ["Ingenuo", "Torpe", "Astuto", "Lento"],
    correcta: 2,
    explicacion: "\"Sagaz\" significa perspicaz o astuto para percibir las cosas.",
  },
  {
    id: "psi-04",
    enunciado: "Indica el ANTÓNIMO de \"veraz\":",
    opciones: ["Sincero", "Mentiroso", "Honesto", "Franco"],
    correcta: 1,
    explicacion: "\"Veraz\" significa que dice la verdad; su contrario es \"mentiroso\".",
  },
  {
    id: "psi-05",
    enunciado: "Indica el SINÓNIMO de \"diligencia\" (en el sentido de \"prontitud\"):",
    opciones: ["Pereza", "Lentitud", "Rapidez", "Desidia"],
    correcta: 2,
    explicacion: "En este sentido, \"diligencia\" equivale a prontitud o rapidez para hacer algo.",
  },
  {
    id: "psi-06",
    enunciado: "Indica el ANTÓNIMO de \"prudente\":",
    opciones: ["Cauto", "Sensato", "Imprudente", "Reflexivo"],
    correcta: 2,
    explicacion: "\"Prudente\" es actuar con cautela; su contrario es \"imprudente\".",
  },
  {
    id: "psi-07",
    enunciado: "Indica el SINÓNIMO de \"coacción\":",
    opciones: ["Presión", "Libertad", "Permiso", "Ayuda"],
    correcta: 0,
    explicacion: "\"Coacción\" es forzar la voluntad de alguien, es decir, ejercer presión.",
  },
  {
    id: "psi-08",
    enunciado: "Indica el ANTÓNIMO de \"imparcial\":",
    opciones: ["Neutral", "Objetivo", "Subjetivo", "Equilibrado"],
    correcta: 2,
    explicacion: "\"Imparcial\" es juzgar sin favorecer a nadie; su contrario es \"subjetivo\" (dejarse llevar por opiniones propias).",
  },
  {
    id: "psi-09",
    enunciado: "Indica el SINÓNIMO de \"arduo\":",
    opciones: ["Fácil", "Difícil", "Sencillo", "Ameno"],
    correcta: 1,
    explicacion: "\"Arduo\" significa difícil, penoso de llevar a cabo.",
  },
  {
    id: "psi-10",
    enunciado: "Indica el ANTÓNIMO de \"conceder\":",
    opciones: ["Otorgar", "Denegar", "Dar", "Permitir"],
    correcta: 1,
    explicacion: "\"Conceder\" es dar u otorgar algo; su contrario es \"denegar\".",
  },
  {
    id: "psi-11",
    enunciado: "Indica el SINÓNIMO de \"exiguo\":",
    opciones: ["Abundante", "Escaso", "Grande", "Amplio"],
    correcta: 1,
    explicacion: "\"Exiguo\" significa insuficiente, escaso.",
  },
  {
    id: "psi-12",
    enunciado: "Indica el ANTÓNIMO de \"diáfano\":",
    opciones: ["Claro", "Transparente", "Turbio", "Nítido"],
    correcta: 2,
    explicacion: "\"Diáfano\" significa claro o transparente; su contrario es \"turbio\".",
  },
  {
    id: "psi-13",
    enunciado: "Indica el SINÓNIMO de \"perentorio\":",
    opciones: ["Urgente", "Tranquilo", "Pausado", "Lento"],
    correcta: 0,
    explicacion: "\"Perentorio\" significa urgente, que no admite demora.",
  },
  {
    id: "psi-14",
    enunciado: "Indica el ANTÓNIMO de \"magnánimo\":",
    opciones: ["Generoso", "Noble", "Mezquino", "Benevolente"],
    correcta: 2,
    explicacion: "\"Magnánimo\" es generoso y noble; su contrario es \"mezquino\".",
  },
  {
    id: "psi-15",
    enunciado: "Indica el SINÓNIMO de \"taciturno\":",
    opciones: ["Alegre", "Callado", "Hablador", "Extrovertido"],
    correcta: 1,
    explicacion: "\"Taciturno\" significa callado, reservado, de carácter melancólico.",
  },
  {
    id: "psi-16",
    enunciado: "Indica el ANTÓNIMO de \"efímero\":",
    opciones: ["Breve", "Pasajero", "Duradero", "Fugaz"],
    correcta: 2,
    explicacion: "\"Efímero\" significa breve, pasajero; su contrario es \"duradero\".",
  },
  {
    id: "psi-17",
    enunciado: "Indica el SINÓNIMO de \"afable\":",
    opciones: ["Hosco", "Amable", "Rudo", "Hostil"],
    correcta: 1,
    explicacion: "\"Afable\" significa amable y agradable en el trato con los demás.",
  },
  {
    id: "psi-18",
    enunciado: "Indica el ANTÓNIMO de \"beligerante\":",
    opciones: ["Agresivo", "Combativo", "Pacífico", "Hostil"],
    correcta: 2,
    explicacion:
      "\"Beligerante\" significa que está en guerra o es propenso a ella; su contrario es \"pacífico\".",
  },
  {
    id: "psi-19",
    enunciado: "Indica el SINÓNIMO de \"ineludible\":",
    opciones: ["Evitable", "Inevitable", "Opcional", "Dudoso"],
    correcta: 1,
    explicacion: "\"Ineludible\" significa que no se puede eludir o evitar, es decir, inevitable.",
  },
  {
    id: "psi-20",
    enunciado: "Indica el ANTÓNIMO de \"lícito\":",
    opciones: ["Legal", "Permitido", "Ilícito", "Justo"],
    correcta: 2,
    explicacion: "\"Lícito\" es lo permitido por la ley; su contrario es \"ilícito\".",
  },
  {
    id: "psi-21",
    enunciado: "Indica el SINÓNIMO de \"fehaciente\":",
    opciones: ["Dudoso", "Fidedigno", "Falso", "Ambiguo"],
    correcta: 1,
    explicacion: "\"Fehaciente\" significa que da fe o certeza de algo, es decir, fidedigno.",
  },
  {
    id: "psi-22",
    enunciado: "Indica el ANTÓNIMO de \"explícito\":",
    opciones: ["Claro", "Directo", "Implícito", "Evidente"],
    correcta: 2,
    explicacion: "\"Explícito\" es lo expresado con claridad; su contrario es \"implícito\".",
  },
  {
    id: "psi-23",
    enunciado: "Indica el SINÓNIMO de \"sumiso\":",
    opciones: ["Rebelde", "Obediente", "Altivo", "Desafiante"],
    correcta: 1,
    explicacion: "\"Sumiso\" significa que obedece con docilidad, es decir, obediente.",
  },
  {
    id: "psi-24",
    enunciado: "Indica el ANTÓNIMO de \"escrupuloso\":",
    opciones: ["Cuidadoso", "Meticuloso", "Negligente", "Riguroso"],
    correcta: 2,
    explicacion: "\"Escrupuloso\" significa cuidadoso y meticuloso; su contrario es \"negligente\".",
  },
  {
    id: "psi-25",
    enunciado: "Indica el SINÓNIMO de \"ostensible\":",
    opciones: ["Oculto", "Evidente", "Disimulado", "Encubierto"],
    correcta: 1,
    explicacion: "\"Ostensible\" significa que se manifiesta clara y visiblemente, es decir, evidente.",
  },
  {
    id: "psi-26",
    enunciado: "Indica el ANTÓNIMO de \"parco\":",
    opciones: ["Moderado", "Sobrio", "Excesivo", "Austero"],
    correcta: 2,
    explicacion: "\"Parco\" significa moderado y sobrio; su contrario es \"excesivo\".",
  },
  {
    id: "psi-27",
    enunciado: "Indica el SINÓNIMO de \"solícito\":",
    opciones: ["Indiferente", "Atento", "Perezoso", "Desganado"],
    correcta: 1,
    explicacion: "\"Solícito\" significa diligente y cuidadoso en atender a alguien, es decir, atento.",
  },
  {
    id: "psi-28",
    enunciado: "Indica el ANTÓNIMO de \"inequívoco\":",
    opciones: ["Claro", "Evidente", "Ambiguo", "Cierto"],
    correcta: 2,
    explicacion: "\"Inequívoco\" es lo que no admite duda; su contrario es \"ambiguo\".",
  },
  {
    id: "psi-29",
    enunciado: "Indica el SINÓNIMO de \"pusilánime\":",
    opciones: ["Valiente", "Cobarde", "Audaz", "Osado"],
    correcta: 1,
    explicacion: "\"Pusilánime\" significa de poco ánimo o valor, es decir, cobarde.",
  },
  {
    id: "psi-30",
    enunciado: "Indica el ANTÓNIMO de \"cordial\":",
    opciones: ["Amable", "Afectuoso", "Hostil", "Amistoso"],
    correcta: 2,
    explicacion: "\"Cordial\" significa afectuoso y amable; su contrario es \"hostil\".",
  },
];
