import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "psi-01",
    enunciado: "Indica el SINÓNIMO de \"diligente\":",
    opciones: ["Perezoso", "Trabajador", "Lento", "Torpe"],
    correcta: 1,
    explicacion: "\"Diligente\" significa aplicado y cuidadoso en el trabajo, como \"trabajador\".",
  },
  {
    id: "psi-02",
    enunciado: "Indica el ANTÓNIMO de \"escaso\":",
    opciones: ["Abundante", "Limitado", "Exiguo", "Poco"],
    correcta: 0,
    explicacion: "\"Escaso\" significa insuficiente; su contrario es \"abundante\".",
  },
  {
    id: "psi-03",
    enunciado: "Indica el SINÓNIMO de \"sagaz\":",
    opciones: ["Ingenuo", "Torpe", "Astuto", "Lento"],
    correcta: 2,
    explicacion: "\"Sagaz\" significa perspicaz o astuto para percibir las cosas.",
  },
  {
    id: "psi-04",
    enunciado: "Indica el ANTÓNIMO de \"veraz\":",
    opciones: ["Sincero", "Mentiroso", "Honesto", "Franco"],
    correcta: 1,
    explicacion: "\"Veraz\" significa que dice la verdad; su contrario es \"mentiroso\".",
  },
  {
    id: "psi-05",
    enunciado: "Indica el SINÓNIMO de \"diligencia\" (en el sentido de \"prontitud\"):",
    opciones: ["Pereza", "Lentitud", "Rapidez", "Desidia"],
    correcta: 2,
    explicacion: "En este sentido, \"diligencia\" equivale a prontitud o rapidez para hacer algo.",
  },
  {
    id: "psi-06",
    enunciado: "Indica el ANTÓNIMO de \"prudente\":",
    opciones: ["Cauto", "Sensato", "Imprudente", "Reflexivo"],
    correcta: 2,
    explicacion: "\"Prudente\" es actuar con cautela; su contrario es \"imprudente\".",
  },
  {
    id: "psi-07",
    enunciado: "Indica el SINÓNIMO de \"coacción\":",
    opciones: ["Presión", "Libertad", "Permiso", "Ayuda"],
    correcta: 0,
    explicacion: "\"Coacción\" es forzar la voluntad de alguien, es decir, ejercer presión.",
  },
  {
    id: "psi-08",
    enunciado: "Indica el ANTÓNIMO de \"imparcial\":",
    opciones: ["Neutral", "Objetivo", "Subjetivo", "Equilibrado"],
    correcta: 2,
    explicacion: "\"Imparcial\" es juzgar sin favorecer a nadie; su contrario es \"subjetivo\" (dejarse llevar por opiniones propias).",
  },
  {
    id: "psi-09",
    enunciado: "Indica el SINÓNIMO de \"arduo\":",
    opciones: ["Fácil", "Difícil", "Sencillo", "Ameno"],
    correcta: 1,
    explicacion: "\"Arduo\" significa difícil, penoso de llevar a cabo.",
  },
  {
    id: "psi-10",
    enunciado: "Indica el ANTÓNIMO de \"conceder\":",
    opciones: ["Otorgar", "Denegar", "Dar", "Permitir"],
    correcta: 1,
    explicacion: "\"Conceder\" es dar u otorgar algo; su contrario es \"denegar\".",
  },
  {
    id: "psi-11",
    enunciado: "Indica el SINÓNIMO de \"exiguo\":",
    opciones: ["Abundante", "Escaso", "Grande", "Amplio"],
    correcta: 1,
    explicacion: "\"Exiguo\" significa insuficiente, escaso.",
  },
  {
    id: "psi-12",
    enunciado: "Indica el ANTÓNIMO de \"diáfano\":",
    opciones: ["Claro", "Transparente", "Turbio", "Nítido"],
    correcta: 2,
    explicacion: "\"Diáfano\" significa claro o transparente; su contrario es \"turbio\".",
  },
  {
    id: "psi-13",
    enunciado: "Indica el SINÓNIMO de \"perentorio\":",
    opciones: ["Urgente", "Tranquilo", "Pausado", "Lento"],
    correcta: 0,
    explicacion: "\"Perentorio\" significa urgente, que no admite demora.",
  },
  {
    id: "psi-14",
    enunciado: "Indica el ANTÓNIMO de \"magnánimo\":",
    opciones: ["Generoso", "Noble", "Mezquino", "Benevolente"],
    correcta: 2,
    explicacion: "\"Magnánimo\" es generoso y noble; su contrario es \"mezquino\".",
  },
  {
    id: "psi-15",
    enunciado: "Indica el SINÓNIMO de \"taciturno\":",
    opciones: ["Alegre", "Callado", "Hablador", "Extrovertido"],
    correcta: 1,
    explicacion: "\"Taciturno\" significa callado, reservado, de carácter melancólico.",
  },
  {
    id: "psi-16",
    enunciado: "Indica el ANTÓNIMO de \"efímero\":",
    opciones: ["Breve", "Pasajero", "Duradero", "Fugaz"],
    correcta: 2,
    explicacion: "\"Efímero\" significa breve, pasajero; su contrario es \"duradero\".",
  },
];
