import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "En psicología social, la actitud se define como una predisposición relativamente estable y aprendida a valorar y responder de forma favorable o desfavorable ante un objeto, persona, grupo o situación determinados. El modelo tripartito clásico distingue tres componentes en toda actitud: el componente cognitivo, formado por las creencias e informaciones que se poseen sobre el objeto; el componente afectivo, referido a los sentimientos y emociones que dicho objeto suscita; y el componente conductual o conativo, que expresa la disposición o tendencia a actuar de un modo determinado ante él. Daniel Katz propuso además una clasificación funcional de las actitudes en cuatro categorías: la función utilitaria, orientada a obtener recompensas o evitar castigos; la función de defensa del yo, que protege la autoestima frente a conflictos internos; la función expresiva de valores, que permite manifestar la propia identidad; y la función de conocimiento, que organiza y simplifica la información del entorno.",
    "Los valores sociales, por su parte, son principios o criterios normativos compartidos en mayor o menor medida por los miembros de un grupo o sociedad, que sirven de referencia para orientar la conducta y para evaluar como deseables o indeseables determinados fines, comportamientos o formas de vida. Tanto las actitudes como los valores se transmiten y modifican a lo largo del proceso de socialización, en el que intervienen distintos agentes: la familia, como núcleo de la socialización primaria; la escuela, encargada de la transmisión formal de normas y valores sociales; el grupo de iguales, con especial peso durante la adolescencia; y los medios de comunicación, cuyo papel se ha visto notablemente reforzado con la generalización de internet y las redes sociales, que aceleran la difusión de información y opiniones, pero que también pueden favorecer fenómenos como las «cámaras de eco» —la exposición selectiva a contenidos afines— y la polarización de actitudes en torno a determinados temas sociales.",
    "Entre los fenómenos psicosociales más relevantes para comprender la dinámica de actitudes y valores destaca la disonancia cognitiva, teoría formulada por Leon Festinger en 1957, que describe el malestar psicológico que experimenta una persona al mantener simultáneamente dos cogniciones incompatibles —por ejemplo, una actitud y una conducta contradictorias entre sí—, lo que genera una motivación para reducir dicha tensión modificando alguno de los elementos en conflicto. Otro fenómeno de particular relevancia social es el prejuicio, entendido como un tipo de actitud, generalmente negativa, dirigida hacia un grupo social o sus miembros, formada de antemano sin una valoración individualizada suficiente y apoyada con frecuencia en estereotipos, esto es, en creencias generalizadas y simplificadas sobre las características atribuidas a dicho grupo.",
  ],
};
