import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La ciberdelincuencia comprende el conjunto de conductas delictivas que se cometen utilizando sistemas informáticos o redes de comunicación como instrumento para su comisión, o que tienen a dichos sistemas, a las redes o a la información que contienen como objeto directo del ataque, conductas que en el ordenamiento español encuentran su respuesta penal, entre otros, en los artículos 197 (descubrimiento y revelación de secretos), 249.1.a (estafa informática) y 264 (daños informáticos) del Código Penal. Entre las técnicas más habituales empleadas por los ciberdelincuentes destaca la ingeniería social, un conjunto de técnicas de manipulación psicológica dirigidas a inducir a las personas a revelar información confidencial o a realizar acciones que comprometan la seguridad de un sistema, explotando el factor humano en lugar de vulnerabilidades técnicas; una de sus manifestaciones más extendidas es el phishing, que consiste en suplantar la identidad de una entidad legítima —un banco, una empresa, un organismo público— para engañar a la víctima y obtener de ella datos personales, credenciales o información financiera.",
    "Entre las modalidades de ataque más significativas se encuentra el ransomware, un tipo de software malicioso que cifra los archivos de un sistema o bloquea el acceso a él, exigiendo a la víctima el pago de un rescate económico —habitualmente en criptomonedas— a cambio de restaurar dicho acceso; y los ataques de denegación de servicio distribuido o DDoS, que consisten en saturar un sistema, servidor o red con un volumen masivo de tráfico procedente de múltiples fuentes simultáneas, con frecuencia dispositivos infectados que forman una red de bots o «botnet», con el objetivo de impedir su funcionamiento normal o dejarlo inaccesible para los usuarios legítimos.",
    "Los agentes de la amenaza en el ciberespacio presentan perfiles y motivaciones muy diversos: desde ciberdelincuentes con una motivación fundamentalmente económica, orientada al fraude, la extorsión o el robo y venta de datos, hasta los llamados hacktivistas, que emplean técnicas de intrusión o filtración de información con una motivación ideológica, política o social. Entre los actores más sofisticados se encuentran los responsables de las llamadas amenazas persistentes avanzadas o APT (Advanced Persistent Threats), ataques dirigidos a un objetivo específico y sostenidos en el tiempo, habitualmente atribuidos a actores estatales o a grupos organizados con recursos técnicos avanzados, cuyo objetivo es lograr una infiltración prolongada en los sistemas de la víctima procurando pasar desapercibidos el mayor tiempo posible.",
    "En España, la respuesta institucional frente a estas amenazas se articula, entre otros organismos, a través del Centro Criptológico Nacional, adscrito al Centro Nacional de Inteligencia, que cuenta con su propia capacidad de respuesta a incidentes de seguridad informática —el CCN-CERT— para la protección de las Administraciones Públicas y de las entidades de interés estratégico para el país, en coordinación con la Estrategia Nacional de Ciberseguridad y con el Centro Nacional de Protección de Infraestructuras Críticas ya analizados en el tema dedicado a la protección de infraestructuras críticas, conformando así un marco institucional que combina la vertiente preventiva y de respuesta técnica con la persecución penal de estas conductas.",
  ],
};
