import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Código Civil, aprobado por Real Decreto de 24 de julio de 1889, abre su Título Preliminar regulando las fuentes del ordenamiento jurídico español: la ley, la costumbre (que solo rige en defecto de ley aplicable) y los principios generales del derecho. Establece también las reglas de aplicación de las normas: interpretación conforme al sentido de las palabras y su finalidad, la analogía para casos no previstos, y principios generales como la buena fe y la prohibición del abuso del derecho. Un punto especialmente relevante para la actuación policial es el artículo 8.1: las leyes penales, de policía y de seguridad pública obligan a todos los que se hallen en territorio español, con independencia de su nacionalidad.",
    "El Título I del Libro I regula la nacionalidad española, distinguiendo la nacionalidad de origen (por filiación o nacimiento en España en determinados supuestos) de las formas de adquisición derivada: la opción, la carta de naturaleza (discrecional) y la residencia. Para esta última, los plazos varían según el caso: diez años con carácter general, cinco para los refugiados, dos para nacionales de países iberoamericanos y asimilados, y uno para supuestos especiales como el matrimonio con español. En todos los casos se exige jurar fidelidad al Rey y obediencia a la Constitución, renunciar a la nacionalidad anterior (salvo excepciones) e inscribir la adquisición en el Registro Civil.",
    "El Código fija también las reglas básicas sobre la persona: la personalidad se adquiere con el nacimiento con vida y se extingue con la muerte; el domicilio de las personas físicas es el lugar de su residencia habitual. La vecindad civil determina la sujeción al derecho civil común o al foral de cada territorio, y se adquiere por dos años de residencia con declaración de voluntad, o por diez años sin declaración en contrario.",
    "El Título IX regula la tutela y guarda de los menores no sujetos a patria potestad o en situación de desamparo, siempre bajo la vigilancia del Ministerio Fiscal; y el Título X fija la mayoría de edad en los 18 años cumplidos, junto con las distintas formas de emancipación. Finalmente, el Título XI —fruto de una reforma reciente que sustituyó el antiguo sistema de incapacitación— regula las medidas de apoyo a las personas con discapacidad (guarda de hecho, curatela y defensor judicial), inspiradas en el respeto a su voluntad, deseos y preferencias, con revisión periódica obligatoria de las medidas judiciales.",
  ],
};
