import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La geografía humana es la rama de la geografía que estudia la distribución espacial de la población y de sus actividades económicas, sociales, políticas y culturales, así como las relaciones entre los grupos humanos y el territorio que ocupan. Se distingue así de la geografía física, centrada en el estudio de los elementos naturales del espacio —relieve, clima, hidrografía, vegetación—, mientras que la geografía humana centra su atención en el ser humano y en la organización de sus actividades sobre el territorio, articulándose en ramas especializadas como la geografía de la población, la geografía urbana, la geografía económica o la geografía política.",
    "El análisis demográfico se apoya en indicadores como la densidad de población, que expresa el número medio de habitantes por unidad de superficie, o las tasas de natalidad y mortalidad, cuya diferencia determina el crecimiento vegetativo de una población. La pirámide de población, representación gráfica de la distribución de los habitantes de un territorio por edad y sexo en un momento determinado, permite identificar patrones demográficos característicos, como una estructura expansiva propia de poblaciones jóvenes y en crecimiento, o una estructura regresiva propia de poblaciones envejecidas y con natalidad decreciente.",
    "En España, la distribución de la población se caracteriza por una fuerte concentración en las zonas litorales y en las grandes áreas metropolitanas, como Madrid y Barcelona, frente a la baja densidad de amplias zonas del interior peninsular. Este desequilibrio territorial tiene su origen, en buena medida, en el éxodo rural experimentado durante las décadas centrales del siglo XX, cuando la mecanización de las labores agrarias y la búsqueda de empleo industrial y de servicios impulsaron un desplazamiento masivo de población desde el campo hacia las ciudades. El fenómeno ha dado lugar en las últimas décadas al debate en torno a la llamada «España vaciada» o «España vacía», expresión que designa a las zonas del interior —especialmente en Castilla y León, Aragón, Castilla-La Mancha o Extremadura— con una densidad de población muy baja y decreciente, un marcado envejecimiento demográfico y serias dificultades de reemplazo generacional.",
    "Este envejecimiento demográfico, entendido como el aumento del peso relativo de la población de mayor edad sobre el conjunto de la población total, es consecuencia principalmente del descenso sostenido de la tasa de natalidad y del incremento paralelo de la esperanza de vida, y plantea retos de primer orden para la organización territorial y social del país, entre ellos la mayor presión sobre el sistema de pensiones y de atención a la dependencia, y la necesidad de articular políticas específicas frente a la despoblación de las zonas rurales más afectadas.",
  ],
};
