import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 3/1981, de 6 de abril, desarrolla la institución del Defensor del Pueblo prevista en el artículo 54 de la Constitución: un alto comisionado de las Cortes Generales encargado de la defensa de los derechos del Título I, con capacidad para supervisar la actividad de la Administración. Es elegido por las Cortes Generales para un mandato de cinco años, mediante un procedimiento que exige mayoría de tres quintos en el Congreso y ratificación por idéntica mayoría en el Senado (o mayoría absoluta si no se alcanzan los tres quintos en una segunda vuelta). En su labor está auxiliado por un Adjunto Primero y un Adjunto Segundo, que lo sustituyen por su orden.",
    "Como garantía de su independencia, el Defensor del Pueblo no está sujeto a mandato imperativo ni recibe instrucciones de ninguna autoridad, goza de inviolabilidad por sus opiniones y actos en el ejercicio del cargo, y solo puede ser detenido en caso de flagrante delito, correspondiendo su enjuiciamiento a la Sala de lo Penal del Tribunal Supremo. Su cargo es incompatible con cualquier mandato representativo, cargo político, actividad profesional o mercantil.",
    "Cualquier persona física o jurídica que invoque un interés legítimo puede dirigirse a él mediante una queja, sin que la nacionalidad, la residencia o situaciones especiales de sujeción (como estar interno en un centro penitenciario) constituyan un obstáculo. El procedimiento es gratuito, no exige abogado ni procurador, y debe presentarse en el plazo de un año desde que se tuvo conocimiento de los hechos. Eso sí, ninguna autoridad administrativa puede presentar una queja sobre asuntos de su propia competencia.",
    "El Defensor del Pueblo carece de potestad para anular o modificar directamente los actos de la Administración, pero puede formular advertencias, recomendaciones y sugerencias a las autoridades, que están obligadas a responder por escrito en el plazo de un mes; y está legitimado para interponer recursos de inconstitucionalidad y de amparo ante el Tribunal Constitucional. Rinde cuentas de su gestión mediante un informe anual ante las Cortes Generales, y puede presentar informes extraordinarios en casos de especial gravedad o urgencia. Además, desde una reforma posterior, ejerce las funciones del Mecanismo Nacional de Prevención de la Tortura.",
  ],
};
