import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Título XIII del Libro II del Código Penal agrupa los delitos contra el patrimonio y contra el orden socioeconómico. El Capítulo I regula el hurto: el artículo 234.1 castiga a quien, con ánimo de lucro, tomare cosas muebles ajenas sin la voluntad de su dueño, con prisión de seis a dieciocho meses cuando la cuantía sustraída exceda de 400 euros, y con multa de uno a tres meses cuando no la exceda. El artículo 235 eleva la pena a prisión de uno a tres años cuando concurren determinadas circunstancias, como que se sustraigan bienes de valor artístico o cultural, cosas de primera necesidad, infraestructuras de suministro esencial, o —de particular interés práctico— cuando los objetos sustraídos sean teléfonos móviles u otros dispositivos de almacenamiento masivo de información digital.",
    "El Capítulo II tipifica el robo, que el artículo 237 define como el apoderamiento de cosas muebles ajenas, con ánimo de lucro, empleando fuerza en las cosas para acceder o abandonar el lugar, o violencia o intimidación en las personas. El robo con fuerza en las cosas exige que concurra alguna de las circunstancias del artículo 238 —escalamiento, rotura de pared, techo o suelo, fractura de puerta, ventana o mueble cerrado, uso de llaves falsas o inutilización de sistemas de alarma— y se castiga con prisión de uno a tres años conforme al artículo 240, agravándose a dos a cinco años cuando además concurre alguna circunstancia del artículo 235; si se comete en casa habitada o local abierto al público, el artículo 241 impone prisión de dos a cinco años. El robo con violencia o intimidación en las personas, regulado en el artículo 242, se castiga con prisión de dos a cinco años, elevada a tres años y seis meses a cinco años cuando tiene lugar en casa habitada, y en su mitad superior cuando el delincuente hace uso de armas u otros medios peligrosos.",
    "La estafa, definida en el artículo 248, consiste en utilizar engaño bastante para producir error en otro, induciéndole a realizar un acto de disposición patrimonial en perjuicio propio o ajeno, con ánimo de lucro; se castiga con prisión de seis meses a tres años. El artículo 249 asimila a la estafa dos modalidades de especial relevancia en el ámbito de la seguridad: la estafa informática, que consiste en obstaculizar o interferir en el funcionamiento de un sistema de información, o introducir, alterar o suprimir datos informáticos, para lograr una transferencia patrimonial no consentida en perjuicio de otro; y el uso fraudulento de tarjetas de crédito o débito u otros instrumentos de pago. El artículo 250 agrava la estafa —con prisión de uno a seis años y multa de seis a doce meses— en supuestos como que la defraudación supere los 50.000 euros, que recaiga sobre bienes de primera necesidad o de reconocida utilidad social, que se cometa estafa procesal, o que medie abuso de las relaciones personales o de la credibilidad profesional del defraudador.",
    "El Código castiga también otras formas de defraudación distintas de la estafa: la administración desleal del artículo 252, que sanciona a quien, teniendo facultades para administrar un patrimonio ajeno, se excede en su ejercicio causando un perjuicio al patrimonio administrado; y la apropiación indebida del artículo 253, que castiga a quien se apropia de dinero, efectos o cualquier cosa mueble recibida en depósito, comisión o custodia, o niega haberla recibido, con las mismas penas que la estafa básica o agravada según la cuantía. Fuera del ámbito estrictamente patrimonial de la estafa, el Capítulo IX del mismo título regula los daños, entre ellos los daños informáticos del artículo 264, que castiga a quien, sin autorización y de manera grave, borrase, dañase o hiciese inaccesibles datos, programas o documentos electrónicos ajenos, con prisión de seis meses a tres años, agravada a dos a cinco años cuando los hechos se cometan en el marco de una organización criminal o afecten a infraestructuras críticas o servicios públicos esenciales.",
  ],
};
