import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Título XXII del Libro II del Código Penal tipifica los delitos contra el orden público, entre los que destaca, por su directa relación con la actividad policial, el delito de atentado. El artículo 550.1 define como reos de atentado a quienes agredieren o, con intimidación grave o violencia, opusieren resistencia grave a la autoridad, a sus agentes o a funcionarios públicos, cuando se hallen en el ejercicio de las funciones de sus cargos o con ocasión de ellas, incluyendo en todo caso a los funcionarios docentes y sanitarios en el ejercicio de sus funciones. El artículo 550.2 castiga el atentado contra autoridad con prisión de uno a cuatro años y multa de tres a seis meses, y con prisión de seis meses a tres años en los demás casos, elevándose la pena a prisión de uno a seis años cuando la autoridad agredida sea miembro del Gobierno, parlamentario, integrante del Consejo General del Poder Judicial, magistrado del Tribunal Constitucional, juez, magistrado o miembro del Ministerio Fiscal.",
    "El artículo 551 impone la pena superior en grado cuando el atentado se comete haciendo uso de armas u otros objetos peligrosos, mediante actos potencialmente peligrosos para la vida de las personas, acometiendo con un vehículo de motor, o con ocasión de un motín en el interior de un centro penitenciario. El artículo 554 extiende esta misma protección penal a los miembros de las Fuerzas Armadas uniformados en servicio, a quienes acudan en auxilio de la autoridad o sus agentes, a los bomberos y personal sanitario que intervengan en situaciones de emergencia, y al personal de seguridad privada que actúe en cooperación y bajo el mando de las Fuerzas y Cuerpos de Seguridad. Cuando la conducta no alcanza la gravedad exigida por el atentado, el artículo 556.1 castiga como resistencia o desobediencia grave a la autoridad o sus agentes, con una pena sensiblemente inferior: prisión de tres meses a un año o multa de seis a dieciocho meses.",
    "El Capítulo III del mismo título regula los desórdenes públicos. El artículo 557.1 castiga con prisión de seis meses a tres años a quienes, actuando en grupo y con el fin de atentar contra la paz pública, ejecuten actos de violencia o intimidación sobre personas o cosas, obstaculicen vías públicas generando peligro, o invadan instalaciones alterando gravemente el funcionamiento de servicios esenciales. La pena se agrava sensiblemente —hasta prisión de tres a cinco años— cuando los hechos se cometen por una multitud cuyo número, organización y propósito sean idóneos para afectar gravemente el orden público, y se impone en su mitad superior, o incluso en grado superior si se portan armas de fuego, cuando los intervinientes portan instrumentos peligrosos o realizan actos de pillaje.",
    "El mismo capítulo castiga otras conductas que afectan a la paz y la seguridad colectivas: la invasión u ocupación en grupo de locales o despachos que cause una perturbación relevante de la paz pública (art. 557 bis), la perturbación grave del orden en tribunales, actos públicos o espectáculos (art. 558), los daños que interrumpan infraestructuras esenciales de telecomunicaciones, ferroviarias o de suministro de agua, gas o electricidad (art. 560), y la falsa alarma consistente en simular una situación de peligro que provoque la movilización de los servicios de policía, asistencia o salvamento (art. 561). Como disposición común a todos estos delitos, el artículo 562 establece que, si su autor se hallare constituido en autoridad, la pena de inhabilitación prevista se sustituye por la inhabilitación absoluta por tiempo de diez a quince años, salvo que dicha circunstancia ya esté específicamente contemplada en el tipo penal correspondiente.",
  ],
};
