import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Código Penal aborda la delincuencia informática desde varios títulos distintos, en función del bien jurídico afectado. El artículo 197, dentro del Título X dedicado a los delitos contra la intimidad, castiga en su apartado primero a quien, para descubrir los secretos o vulnerar la intimidad de otro sin su consentimiento, se apodere de sus papeles, cartas, mensajes de correo electrónico u otros documentos, o intercepte sus telecomunicaciones, con prisión de uno a cuatro años y multa de doce a veinticuatro meses. El apartado segundo extiende esta protección a los datos reservados de carácter personal registrados en ficheros o soportes informáticos, electrónicos o telemáticos, castigando tanto a quien se apodere, utilice o modifique dichos datos sin autorización como a quien simplemente acceda a ellos sin estarlo. Cuando esos datos o secretos descubiertos se difunden, revelan o ceden a terceros, el apartado tercero eleva la pena a prisión de dos a cinco años, y el apartado cuarto agrava aún más la respuesta penal —hasta prisión de tres a cinco años— cuando los hechos los cometen las personas encargadas o responsables de los propios ficheros, o se utilizan datos personales de la víctima sin autorización para facilitar el acceso.",
    "En el ámbito patrimonial, el artículo 249.1, dentro de la regulación de la estafa, tipifica de forma expresa la estafa informática: su letra a) castiga a quienes, con ánimo de lucro, obstaculizando o interfiriendo indebidamente en el funcionamiento de un sistema de información, o introduciendo, alterando, borrando o suprimiendo datos informáticos mediante cualquier manipulación, consigan una transferencia no consentida de un activo patrimonial en perjuicio de otro. La letra b) del mismo precepto castiga, con idéntica pena de prisión de seis meses a tres años, el uso fraudulento de tarjetas de crédito o débito, cheques de viaje o cualquier otro instrumento de pago distinto del efectivo, así como de los datos obrantes en ellos, en perjuicio de su titular o de un tercero. El apartado segundo del mismo artículo castiga además, con la misma pena, a quienes fabriquen, posean o faciliten a terceros los dispositivos, datos o programas informáticos específicamente diseñados para cometer estas estafas.",
    "Por último, el artículo 264, ya dentro del capítulo dedicado a los daños, tipifica los daños informáticos propiamente dichos: quien, por cualquier medio, sin autorización y de manera grave, borrase, dañase, deteriorase, alterase, suprimiese o hiciese inaccesibles datos informáticos, programas informáticos o documentos electrónicos ajenos, es castigado con prisión de seis meses a tres años cuando el resultado producido sea grave. La pena se eleva a prisión de dos a cinco años y multa del tanto al décuplo del perjuicio ocasionado cuando concurran circunstancias cualificadas, como la comisión en el marco de una organización criminal, daños de especial gravedad o que afecten a un número elevado de sistemas informáticos, un perjuicio grave al funcionamiento de servicios públicos esenciales, o la afectación al sistema informático de una infraestructura crítica o a la seguridad del Estado. Finalmente, las penas se imponen en su mitad superior cuando los hechos se cometen mediante la utilización ilícita de datos personales de otra persona para facilitar el acceso al sistema informático o para ganarse la confianza de un tercero.",
  ],
};
