import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Título I de la Constitución, \"De los derechos y deberes fundamentales\", se organiza en cinco capítulos: los españoles y los extranjeros; los derechos y libertades, divididos a su vez en derechos fundamentales y libertades públicas (arts. 15 a 29) y derechos y deberes de los ciudadanos (arts. 30 a 38); los principios rectores de la política social y económica; las garantías de las libertades y derechos; y la suspensión de los derechos y libertades.",
    "Entre los derechos fundamentales de la Sección 1ª destacan el derecho a la vida y a la integridad física y moral, con abolición de la pena de muerte salvo lo que puedan disponer las leyes penales militares para tiempos de guerra; la libertad y seguridad personal, con un límite máximo de 72 horas de detención preventiva y la garantía del habeas corpus; la inviolabilidad del domicilio y el secreto de las comunicaciones; las libertades de expresión e información; el derecho de reunión pacífica; el derecho a la tutela judicial efectiva; y los derechos de sindicación y huelga.",
    "Estos derechos vinculan a todos los poderes públicos, requieren ley orgánica para su desarrollo y cuentan con garantías reforzadas: un procedimiento judicial preferente y sumario, y el recurso de amparo ante el Tribunal Constitucional para los derechos comprendidos entre los artículos 15 y 29 (más la objeción de conciencia del art. 30.2). El Defensor del Pueblo, como alto comisionado de las Cortes Generales, supervisa la actividad de la Administración en defensa de estos derechos.",
    "El artículo 55 permite suspender determinados derechos en dos supuestos distintos: una suspensión general y colectiva durante la vigencia de los estados de excepción y de sitio (que afecta, entre otros, a la libertad, la inviolabilidad del domicilio, el secreto de las comunicaciones y la libertad de circulación), y una suspensión individual, aplicable a personas concretas en investigaciones relacionadas con bandas armadas o elementos terroristas, sujeta a la necesaria intervención judicial y al control parlamentario de la utilización de esta facultad.",
  ],
};
