import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El artículo 17 de la Constitución consagra el derecho a la libertad y a la seguridad, disponiendo que la detención preventiva no puede durar más del tiempo estrictamente necesario para realizar las averiguaciones dirigidas al esclarecimiento de los hechos y que, en todo caso, dentro del plazo máximo de setenta y dos horas, el detenido debe ser puesto en libertad o a disposición de la autoridad judicial. El mismo precepto garantiza a toda persona detenida el derecho a ser informada de forma inmediata y comprensible de sus derechos y de las razones de la detención, a no declarar contra sí misma ni confesarse culpable, y a la asistencia de abogado en las diligencias policiales y judiciales.",
    "En desarrollo del artículo 17.4 de la Constitución, la Ley Orgánica 6/1984 regula el procedimiento de habeas corpus, dirigido a obtener la inmediata puesta a disposición judicial de cualquier persona detenida ilegalmente. Pueden instarlo el propio detenido, su cónyuge o persona con análoga relación de afectividad, sus ascendientes, descendientes y hermanos, el Ministerio Fiscal y el Defensor del Pueblo, y también puede iniciarse de oficio por el juez competente, que normalmente es el del lugar en que se encuentra la persona privada de libertad. Se trata de un procedimiento sumario y urgente, sin las formalidades propias de otros procesos judiciales.",
    "El Ministerio Fiscal, conforme al artículo 124 de la Constitución, tiene por misión promover la acción de la justicia en defensa de la legalidad, de los derechos de los ciudadanos y del interés público tutelado por la ley, así como velar por la independencia de los Tribunales. Ejerce sus funciones conforme a los principios de unidad de actuación y dependencia jerárquica, si bien sometido en todo caso a los principios de legalidad e imparcialidad. Por su parte, el artículo 126 de la Constitución configura la Policía Judicial como la que, dependiendo de Jueces, Tribunales y del Ministerio Fiscal, tiene encomendada la averiguación del delito y el descubrimiento y aseguramiento del delincuente.",
    "En el ejercicio de esta función, la Policía Judicial recoge en el atestado las diligencias practicadas con ocasión de la investigación de un hecho delictivo, incluyendo los efectos, instrumentos o pruebas recogidos, que pone a disposición de la autoridad judicial o del Ministerio Fiscal. Conforme al artículo 297 de la Ley de Enjuiciamiento Criminal, el atestado tiene, con carácter general, el valor de una denuncia, por lo que para constituir prueba de cargo válida debe generalmente ser ratificado y sometido a contradicción en el acto del juicio oral, salvo en aquellos extremos objetivos que los propios agentes puedan constatar directamente. Según la gravedad del delito, el proceso penal se sustancia por el procedimiento ordinario, el procedimiento abreviado, el proceso ante el Tribunal del Jurado o el juicio por delitos leves.",
  ],
};
