import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Declaración Universal de los Derechos Humanos fue proclamada por la Asamblea General de las Naciones Unidas el 10 de diciembre de 1948, en el contexto de la reconstrucción del orden internacional tras la Segunda Guerra Mundial. Su artículo 1 sienta el principio sobre el que se construye todo el edificio de los derechos humanos: que todos los seres humanos nacen libres e iguales en dignidad y derechos. Aunque, por su naturaleza de resolución de la Asamblea General, la Declaración carece de fuerza vinculante equiparable a la de un tratado internacional, gran parte de su contenido se considera hoy derecho internacional consuetudinario, y fue desarrollada jurídicamente por el Pacto Internacional de Derechos Civiles y Políticos y el Pacto Internacional de Derechos Económicos, Sociales y Culturales, ambos de 1966, que junto con la propia Declaración conforman la llamada Carta Internacional de Derechos Humanos.",
    "La doctrina clasifica tradicionalmente los derechos humanos en tres generaciones: la primera agrupa los derechos civiles y políticos, vinculados a la libertad individual y a la participación política; la segunda, los derechos económicos, sociales y culturales, orientados a garantizar condiciones materiales de vida digna; y la tercera, los llamados derechos de solidaridad o de los pueblos, como el derecho a la paz, al desarrollo o a un medio ambiente sano, de titularidad más colectiva que individual. Estos derechos se caracterizan por su universalidad —corresponden a toda persona por su sola condición humana—, su carácter inalienable e irrenunciable, y su interdependencia e indivisibilidad, de modo que el disfrute efectivo de unos condiciona el de los demás.",
    "A nivel internacional, la protección de los derechos humanos se articula a través de distintos sistemas. En el ámbito universal, el Consejo de Derechos Humanos de Naciones Unidas, con sede en Ginebra y creado en 2006, supervisa su cumplimiento mediante mecanismos como el Examen Periódico Universal. En el ámbito europeo, el Convenio Europeo para la Protección de los Derechos Humanos y de las Libertades Fundamentales, adoptado en 1950 en el marco del Consejo de Europa, reconoce un catálogo de derechos y crea el Tribunal Europeo de Derechos Humanos, con sede en Estrasburgo, ante el que los particulares pueden demandar a los Estados parte por su vulneración; a ello se suma la Carta de los Derechos Fundamentales de la Unión Europea, jurídicamente vinculante desde la entrada en vigor del Tratado de Lisboa en 2009.",
    "En el ordenamiento español, el Título I de la Constitución de 1978, «De los derechos y deberes fundamentales», recoge en sus artículos 10 a 55 el catálogo constitucional de derechos, con distinta intensidad de protección según su ubicación: los derechos fundamentales y libertades públicas de la Sección 1.ª del Capítulo II gozan de la protección reforzada del recurso de amparo ante el Tribunal Constitucional, y el artículo 10.2 exige interpretar las normas relativas a derechos fundamentales de conformidad con la Declaración Universal y los tratados internacionales ratificados por España. Esta protección constitucional alcanza también a la actuación de las Fuerzas y Cuerpos de Seguridad, cuya Ley Orgánica reguladora, la LO 2/1986, exige entre sus principios básicos de actuación el pleno sometimiento a la Constitución y al resto del ordenamiento jurídico, evitando en todo caso cualquier práctica abusiva, arbitraria o discriminatoria en el ejercicio de la función policial.",
  ],
};
