import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El artículo 10 del Código Penal define los delitos como las acciones y omisiones dolosas o imprudentes penadas por la ley. Dogmáticamente, el delito se construye sobre tres elementos: la tipicidad (la conducta debe estar prevista como delito en la ley penal), la antijuridicidad (debe ser contraria al ordenamiento jurídico y no estar amparada por una causa de justificación) y la culpabilidad (debe poder reprocharse a su autor). Todo ello se asienta sobre el principio de legalidad penal, recogido en el artículo 25.1 de la Constitución y en el artículo 1 del Código Penal, conforme al cual nadie puede ser condenado por una acción u omisión que no constituya delito según la ley vigente en el momento de cometerse, exigiéndose además que esa ley sea previa, escrita y estricta.",
    "El dolo supone que el autor conoce y quiere realizar los elementos del tipo penal, o al menos acepta la probabilidad de su producción (dolo eventual); la imprudencia, regulada en el artículo 12 del Código Penal, consiste en causar el resultado típico por infracción del deber objetivo de cuidado, sin que el autor lo haya querido, y solo es punible cuando una norma penal expresamente lo castiga. En materia de autoría y participación, el artículo 28 del Código Penal considera autores a quienes realizan el hecho por sí solos, conjuntamente o por medio de otro del que se sirven como instrumento, así como a los inductores y a los cooperadores necesarios; el artículo 29 reserva la condición de cómplices a quienes cooperan con actos anteriores o simultáneos no esenciales, a los que corresponde, conforme al artículo 63, la pena inferior en grado a la de los autores.",
    "El artículo 20 del Código Penal recoge las causas que eximen de responsabilidad criminal, entre ellas las relativas a la inimputabilidad (anomalía psíquica, intoxicación plena, alteraciones graves de la percepción), la legítima defensa, el estado de necesidad, el miedo insuperable y el obrar en cumplimiento de un deber o en el ejercicio legítimo de un derecho, oficio o cargo. A ello se suma la minoría de edad penal: conforme al artículo 19, los menores de dieciocho años no responden con arreglo al Código Penal, sino a la Ley Orgánica 5/2000, reguladora de la responsabilidad penal de los menores. Junto a estas causas de exclusión, los artículos 21 a 23 regulan las circunstancias atenuantes, agravantes y la mixta de parentesco, que sin excluir el delito modulan la pena dentro del marco legal previsto.",
    "El artículo 33 del Código Penal clasifica las penas, según su gravedad, en graves, menos graves y leves, distinguiendo además entre penas privativas de libertad (prisión, prisión permanente revisable y responsabilidad personal subsidiaria por impago de multa), penas privativas de otros derechos (inhabilitaciones, suspensiones, alejamiento, trabajos en beneficio de la comunidad) y la pena de multa. Finalmente, el artículo 130 enumera las causas de extinción de la responsabilidad criminal: la muerte del reo, el cumplimiento de la condena, la remisión definitiva de la pena, la prescripción del delito, la prescripción de la pena, el indulto y el perdón del ofendido en los delitos en que la ley lo admite.",
  ],
};
