import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Código Penal dedica su Título I del Libro II al homicidio y sus formas. El artículo 138.1 castiga el homicidio básico, esto es, matar a otro, con prisión de diez a quince años. Cuando en la muerte concurren determinadas circunstancias que denotan una mayor gravedad —alevosía, precio, recompensa o promesa, ensañamiento aumentando deliberada e inhumanamente el dolor del ofendido, o la finalidad de facilitar la comisión de otro delito o evitar que se descubra—, el hecho se califica como asesinato conforme al artículo 139.1, con pena de prisión de quince a veinticinco años. El artículo 140.1 reserva la prisión permanente revisable para los asesinatos más graves: cuando la víctima sea menor de dieciséis años o una persona especialmente vulnerable, cuando el asesinato sea subsiguiente a un delito contra la libertad sexual cometido por el autor sobre la víctima, o cuando el culpable perteneciera a un grupo u organización criminal.",
    "El Título II regula el delito de aborto. Fuera de los supuestos legalmente permitidos, el artículo 145.2 castiga a la mujer que produjere su propio aborto o consintiera que otra persona se lo causare con la pena de multa de seis a veinticuatro meses, una pena sensiblemente inferior a la prevista para quien practica el aborto sin su consentimiento o fuera de los casos legales. El Título III, por su parte, tipifica el delito de lesiones: el artículo 147.1 castiga a quien, por cualquier medio, causare a otro una lesión que menoscabe su integridad corporal o su salud física o mental, siempre que la sanidad de dicha lesión requiera objetivamente, además de una primera asistencia facultativa, tratamiento médico o quirúrgico, con pena de prisión de tres meses a tres años o multa de seis a doce meses.",
    "El Título VI protege la libertad individual frente a las privaciones ilegítimas. El artículo 163 castiga al particular que encerrare o detuviere a otro privándole de su libertad, si bien su apartado segundo introduce un supuesto atenuado: si el culpable diera libertad al encerrado o detenido dentro de los tres primeros días de su detención, sin haber logrado el objeto que se había propuesto, se le impone la pena inferior en grado. Cuando la detención ilegal se acompaña de la exigencia de alguna condición para poner en libertad a la víctima, el hecho se convierte en secuestro conforme al artículo 164, con una pena de prisión de seis a diez años. El artículo 165 agrava ambas figuras cuando se ejecutan con simulación de autoridad o función pública, o cuando la víctima es menor de edad, persona con discapacidad necesitada de especial protección, o funcionario público en el ejercicio de sus funciones.",
    "El mismo título castiga las amenazas (art. 169) y las coacciones (art. 172.1): las primeras consisten en anunciar a otro un mal constitutivo de delito, con penas que varían según se exija o no una condición y según el culpable consiga o no su propósito; las segundas, en impedir a otro con violencia hacer lo que la ley no prohíbe, o en compelerle a efectuar lo que no quiere, sea justo o injusto. El artículo 172 ter tipifica de forma específica el delito de acoso o \"stalking\", consistente en llevar a cabo de forma insistente y reiterada, sin estar legítimamente autorizado, conductas como la vigilancia, la búsqueda de cercanía física o los intentos de contacto con la víctima, de modo que se altere gravemente el desarrollo de su vida cotidiana. Finalmente, la Parte General del Código, en su artículo 17, define la conspiración como el concierto de dos o más personas para ejecutar un delito, resolviendo llevarlo a cabo, y la proposición como la invitación que quien ha resuelto cometer un delito dirige a otra persona para que participe en él; ambas figuras solo se castigan en los casos en que la ley lo prevé expresamente para el delito concreto de que se trate.",
  ],
};
