import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El concepto de desarrollo sostenible se popularizó a partir del Informe «Nuestro futuro común», elaborado en 1987 por la Comisión Mundial sobre el Medio Ambiente y el Desarrollo de las Naciones Unidas, conocida como Comisión Brundtland, que lo definió como aquel desarrollo que satisface las necesidades del presente sin comprometer la capacidad de las generaciones futuras para satisfacer las suyas propias. Desde entonces, el desarrollo sostenible se articula sobre tres pilares interdependientes que deben perseguirse de forma equilibrada: la dimensión económica, vinculada al crecimiento y la prosperidad; la dimensión social, referida a la equidad y la cohesión; y la dimensión ambiental, centrada en la conservación de los recursos naturales y los ecosistemas.",
    "Este marco conceptual se plasmó institucionalmente en la Agenda 2030 para el Desarrollo Sostenible, aprobada por la Asamblea General de las Naciones Unidas en septiembre de 2015, que estableció los 17 Objetivos de Desarrollo Sostenible (ODS) como sucesores de los anteriores Objetivos de Desarrollo del Milenio. Estos objetivos fijan metas comunes para los Estados en ámbitos como la erradicación de la pobreza y el hambre, la igualdad de género, el acceso a la educación y la salud, la acción climática, o la promoción de sociedades pacíficas e inclusivas y de instituciones eficaces.",
    "En el ámbito específico del cambio climático, el Acuerdo de París, adoptado en diciembre de 2015 en el marco de la Convención Marco de las Naciones Unidas sobre el Cambio Climático, constituye el principal instrumento jurídico internacional de referencia, con el objetivo de limitar el aumento de la temperatura media global muy por debajo de los 2 °C respecto de los niveles preindustriales, prosiguiendo los esfuerzos para limitarlo a 1,5 °C. Para evaluar el impacto ambiental de personas, organizaciones o productos se recurre habitualmente a indicadores como la huella de carbono, que mide la cantidad total de gases de efecto invernadero emitidos de forma directa o indirecta, mientras que en el ámbito productivo se promueve cada vez más el modelo de la economía circular, orientado a alargar la vida útil de los bienes mediante la reutilización, la reparación y el reciclaje, frente al modelo económico lineal tradicional basado en extraer, producir, consumir y desechar.",
    "Los enfoques actuales de seguridad reconocen, además, una creciente interconexión entre el desarrollo sostenible y la seguridad: el deterioro ambiental y el cambio climático se identifican como factores que pueden agravar conflictos por el acceso a recursos escasos, generar desplazamientos forzados de población —los llamados migrantes climáticos— y afectar a la seguridad humana en un sentido amplio, lo que ha llevado a incorporar de forma creciente la dimensión ambiental al análisis contemporáneo de riesgos y amenazas, en coordinación con organismos como el Programa de las Naciones Unidas para el Medio Ambiente, creado en 1972 para coordinar las políticas ambientales dentro del sistema de Naciones Unidas.",
  ],
};
