import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Organización Mundial de la Salud define la droga como toda sustancia que, introducida en el organismo por cualquier vía, es capaz de actuar sobre el sistema nervioso central modificando una o varias de sus funciones, con capacidad de generar dependencia. Las sustancias psicoactivas se clasifican habitualmente, según su efecto predominante, en depresoras del sistema nervioso central —como el alcohol, los opiáceos o las benzodiacepinas—, estimulantes —como la cocaína, las anfetaminas o la cafeína— y perturbadoras o alucinógenas —como el LSD, el cannabis o el éxtasis—. Sobre esta base, la clínica distingue diversos grados de gravedad en la relación de una persona con una sustancia: el uso, entendido como un consumo ocasional sin consecuencias negativas relevantes; el abuso, que implica ya un patrón de consumo generador de problemas de salud, familiares, laborales o legales; y la dependencia, caracterizada por la pérdida de control sobre el consumo y por fenómenos como la tolerancia —la necesidad de aumentar progresivamente la dosis para lograr el mismo efecto— y el síndrome de abstinencia, esto es, el conjunto de síntomas físicos y psíquicos que aparecen al reducir o suprimir bruscamente el consumo habitual.",
    "En España, la coordinación de las políticas públicas en esta materia corresponde a la Delegación del Gobierno para el Plan Nacional sobre Drogas, adscrita al Ministerio de Sanidad, que impulsa y evalúa las estrategias de prevención, asistencia e inserción social relacionadas con las drogodependencias. Estas estrategias combinan distintos niveles de prevención —universal, dirigida a toda la población; selectiva, orientada a grupos de riesgo; e indicada, dirigida a personas con un consumo ya iniciado— con enfoques de reducción de daños, orientados a minimizar las consecuencias sanitarias y sociales negativas del consumo sin exigir necesariamente la abstinencia como condición previa, mediante medidas como los programas de intercambio de jeringuillas o las salas de consumo supervisado, junto con los recursos de tratamiento y reinserción social de las personas afectadas.",
    "Las Fuerzas y Cuerpos de Seguridad desempeñan en este ámbito una doble función. Por un lado, persiguen el tráfico ilícito de drogas, tipificado como delito en el Código Penal, y velan por el cumplimiento del régimen sancionador administrativo previsto en la Ley Orgánica 4/2015 para el consumo en la vía pública y otras conductas relacionadas. Por otro, colaboran activamente en la prevención del consumo, con especial atención a la población menor de edad, coordinándose para ello con los servicios sanitarios y sociales especializados en la atención a las drogodependencias, en el marco de una respuesta institucional que combina la vertiente de seguridad con la vertiente sanitaria y social del fenómeno.",
  ],
};
