import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Derecho puede entenderse en sentido objetivo, como el conjunto de normas jurídicas que rigen la convivencia social y cuyo cumplimiento puede exigirse de forma coactiva, y en sentido subjetivo, como la facultad que una norma reconoce a una persona para exigir algo de otra. El artículo 1.1 del Código Civil establece que las fuentes del ordenamiento jurídico español son la ley, la costumbre y los principios generales del derecho: la costumbre solo rige en defecto de ley aplicable, siempre que no sea contraria a la moral o al orden público y resulte probada, y los principios generales se aplican en defecto de ambas, sin perjuicio de su carácter informador de todo el ordenamiento. La jurisprudencia, por su parte, complementa el ordenamiento con la doctrina reiterada del Tribunal Supremo, aunque no se considera fuente del Derecho en sentido estricto.",
    "En cuanto a la aplicación de las normas, las leyes entran en vigor a los veinte días de su completa publicación en el Boletín Oficial del Estado, salvo que en ellas se disponga otro plazo (la llamada vacatio legis), y se derogan por leyes posteriores con el alcance que estas dispongan expresamente. La ignorancia de las leyes no excusa de su cumplimiento. El Código Civil regula también la analogía: cuando las normas no contemplan un supuesto específico pero regulan otro semejante entre los que existe identidad de razón, procede aplicar esa norma por analogía, salvo en el caso de las leyes penales, las excepcionales y las de ámbito temporal, que quedan excluidas de esta técnica por su carácter restrictivo.",
    "La interpretación de las normas jurídicas, conforme al artículo 3.1 del Código Civil, debe atender al sentido propio de sus palabras, en relación con el contexto, los antecedentes históricos y legislativos y la realidad social del momento en que se aplican, buscando fundamentalmente su espíritu y finalidad. La equidad puede ponderarse en la aplicación de las normas, pero una resolución solo puede basarse exclusivamente en ella cuando la ley lo permita de forma expresa.",
    "Por último, el artículo 9.3 de la Constitución garantiza un conjunto de principios que estructuran todo el ordenamiento jurídico: el principio de legalidad, la jerarquía normativa (una norma de rango inferior no puede contradecir a una de rango superior, y si lo hace es nula de pleno derecho), la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica, la responsabilidad de los poderes públicos y la interdicción de su arbitrariedad.",
  ],
};
