import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Reglamento General de Circulación, aprobado por Real Decreto 1428/2003, regula en su Capítulo III, Sección 4.ª, el régimen de los vehículos prioritarios. El artículo 67.1 reconoce a los vehículos de servicios de urgencia, públicos o privados, prioridad de paso sobre los demás vehículos y usuarios de la vía cuando se hallan en servicio de tal carácter, permitiéndoles circular por encima de los límites de velocidad y quedar exentos de otras normas o señales, en los términos que fija la propia sección. No obstante, el artículo 67.2 exige a sus conductores un uso ponderado de este régimen especial, únicamente cuando presten un servicio urgente, debiendo adoptar extremadas precauciones antes de vulnerar la prioridad de paso en intersecciones o semáforos, hasta cerciorarse de que no existe riesgo de atropello y de que los demás conductores han detenido su marcha o se disponen a facilitarla.",
    "El artículo 68 desarrolla las facultades y la responsabilidad de estos conductores: pueden dejar de cumplir, bajo su exclusiva responsabilidad y siempre que se hayan cerciorado de no poner en peligro a ningún usuario, las normas de los títulos II, III y IV del reglamento, si bien las órdenes y señales de los agentes de la autoridad son en todo caso de obligado cumplimiento. Con carácter excepcional, cuando circulan por autopista o autovía en servicio urgente sin comprometer la seguridad de nadie, pueden incluso dar media vuelta, circular en sentido contrario por el arcén, o penetrar en la mediana. El artículo 68.2 reserva el carácter de prioritarios a los vehículos de policía, extinción de incendios, protección civil y salvamento, y asistencia sanitaria, cuando circulan en servicio urgente advirtiendo su presencia mediante el uso simultáneo de la señal luminosa y del aparato emisor de señales acústicas especiales previsto en el anexo XI del Reglamento General de Vehículos, si bien puede prescindirse de la señal acústica cuando su omisión no entrañe peligro para los demás usuarios; las infracciones a estas normas se califican como graves.",
    "Correlativamente, el artículo 69 impone a los demás conductores el deber de adoptar las medidas adecuadas para facilitar el paso tan pronto perciban las señales de un vehículo prioritario, apartándose normalmente a su derecha o deteniéndose si fuera preciso; y, cuando un vehículo policial se sitúa detrás de otro y activa un dispositivo de luz roja intermitente, el conductor de este debe detenerse con las debidas precauciones en el lado derecho, delante del vehículo policial, permanecer en su interior y seguir las instrucciones que le imparta el agente. El artículo 70, por su parte, regula el supuesto excepcional del vehículo no prioritario forzado por circunstancias especialmente graves a efectuar un servicio de urgencia, exigiéndole advertir a los demás usuarios de su situación mediante el avisador acústico intermitente, la luz de emergencia o, en su defecto, un pañuelo u otro procedimiento similar, sin dejar de respetar las normas de circulación; los agentes pueden exigir en cualquier momento la justificación de tales circunstancias. Completando este régimen, el artículo 11.7 del Reglamento General de Vehículos reserva la instalación de aparatos emisores de señales acústicas especiales exclusivamente a los vehículos que tengan el carácter de prioritarios, siempre que cuenten con la debida autorización del órgano competente en materia de industria.",
  ],
};
