import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El texto refundido de la Ley del Estatuto Básico del Empleado Público (Real Decreto Legislativo 5/2015, de 30 de octubre) establece las bases del régimen estatutario de los funcionarios públicos y las normas aplicables al personal laboral al servicio de las Administraciones Públicas. Se aplica a la Administración General del Estado, a las comunidades autónomas, a las entidades locales y a los organismos públicos vinculados a ellas. Los Cuerpos de Policía Local se rigen también por el EBEP y por la legislación autonómica, salvo lo dispuesto para ellos en la Ley Orgánica 2/1986, de Fuerzas y Cuerpos de Seguridad.",
    "El EBEP clasifica a los empleados públicos en funcionarios de carrera, funcionarios interinos, personal laboral (fijo, indefinido o temporal) y personal eventual. Los funcionarios de carrera están vinculados a la Administración por una relación estatutaria permanente regulada por el Derecho Administrativo; los interinos cubren necesidades temporales y urgentes, con un límite general de tres años para la ocupación de una vacante; y el personal eventual desempeña funciones de confianza o asesoramiento, con nombramiento y cese libres.",
    "El acceso al empleo público se rige por los principios constitucionales de igualdad, mérito y capacidad, además de publicidad, transparencia e imparcialidad de los órganos de selección. Se exige, entre otros requisitos, tener 16 años cumplidos y la titulación correspondiente, reservándose al menos un 7% de las vacantes para personas con discapacidad. Los sistemas selectivos ordinarios para funcionarios de carrera son la oposición y el concurso-oposición. La condición de funcionario de carrera se adquiere de forma sucesiva: superación del proceso selectivo, nombramiento publicado, acatamiento de la Constitución y toma de posesión.",
    "La ley regula también la pérdida de la condición de funcionario (renuncia, pérdida de nacionalidad, jubilación, separación disciplinaria firme o inhabilitación firme), la jubilación forzosa a los 65 años, la clasificación de cuerpos y escalas en los grupos A1, A2, B, C1 y C2 según la titulación exigida, los procedimientos de provisión de puestos (concurso y libre designación), y las situaciones administrativas de los funcionarios de carrera: servicio activo, servicios especiales, servicio en otras Administraciones Públicas, excedencia (en sus distintas modalidades) y suspensión de funciones.",
  ],
};
