import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 4/2015, de 27 de abril, del Estatuto de la víctima del delito, es aplicable, según su artículo 1, a las víctimas de delitos cometidos en España o que puedan ser perseguidos en España, con independencia de su nacionalidad, de si son mayores o menores de edad o de si disfrutan de residencia legal. El artículo 2 distingue entre víctima directa —toda persona física que haya sufrido un daño o perjuicio sobre su propia persona o patrimonio directamente causado por un delito— y víctima indirecta, categoría reservada a los casos de muerte o desaparición de la víctima directa, que comprende al cónyuge no separado o a la pareja de análoga relación de afectividad, a los hijos convivientes, y a los progenitores y parientes hasta el tercer grado bajo su guarda. El artículo 3 reconoce a toda víctima el derecho a la protección, información, apoyo, asistencia, atención, reparación y participación activa en el proceso penal, con un trato respetuoso, profesional, individualizado y no discriminatorio, y veta expresamente la mediación y la conciliación en los supuestos de violencia sexual y de violencia de género.",
    "El Título I regula los derechos básicos de la víctima: el derecho a entender y ser entendida (art. 4), que impone comunicaciones en lenguaje claro y accesible y la posibilidad de estar acompañada desde el primer contacto con las autoridades; y el derecho a la información desde ese primer contacto (art. 5), que obliga a facilitar de manera inmediata información sobre medidas de asistencia, el procedimiento para denunciar, el asesoramiento jurídico gratuito, las medidas de protección disponibles, las indemnizaciones a las que pueda tener derecho y los servicios de interpretación y traducción, entre otros extremos que deben actualizarse en cada fase del procedimiento. El artículo 6 reconoce además, en el momento de presentar la denuncia, el derecho a obtener una copia certificada de la misma y a la asistencia lingüística gratuita cuando la víctima no entienda las lenguas oficiales del lugar.",
    "El Título III desarrolla el derecho de las víctimas a la protección. El artículo 19 obliga a las autoridades encargadas de la investigación, persecución y enjuiciamiento a garantizar la vida, la integridad física y psíquica, la libertad, la seguridad y la indemnidad sexual de la víctima y sus familiares, protegiendo su intimidad y dignidad, y evitando el riesgo de victimización secundaria o reiterada, con especial vigilancia de la Fiscalía en el caso de menores. El artículo 20 exige que las dependencias donde se desarrollan los actos del procedimiento eviten el contacto directo entre la víctima y el sospechoso o acusado, mientras que el artículo 21 impone que las declaraciones se reciban sin dilaciones injustificadas, el menor número de veces posible, y con la posibilidad de que la víctima esté acompañada de una persona de su elección.",
    "El artículo 23 exige realizar una evaluación individual de las víctimas para determinar sus necesidades especiales de protección, valorando sus características personales, la naturaleza del delito —con especial atención a los de terrorismo, organización criminal, violencia sobre el cónyuge o pareja, contra la libertad o indemnidad sexual, trata de seres humanos, desaparición forzada o motivados por razones discriminatorias— y las circunstancias del hecho, en particular su carácter violento. Dicha valoración corresponde, conforme al artículo 24, al Juez de Instrucción o al de Violencia sobre la Mujer durante la fase de investigación, sin perjuicio de la evaluación provisional del Fiscal o de los funcionarios de policía en la fase inicial, y al Juez o Tribunal competente durante el enjuiciamiento. Entre las medidas de protección del artículo 25 destacan la toma de declaración en dependencias adaptadas y por profesionales con formación especial, evitar el contacto visual con el investigado y la posibilidad de declarar sin estar presente en la sala mediante tecnologías de la comunicación; para menores, personas con discapacidad necesitada de especial protección y víctimas de violencia sexual, el artículo 26 añade medidas reforzadas como la grabación audiovisual de las declaraciones y, en su defecto de representación adecuada, la designación de un defensor judicial, estableciendo además que, ante la duda sobre la edad de la víctima, se presumirá su minoría de edad.",
  ],
};
