import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 4/1981, de 1 de junio, desarrolla el artículo 116 de la Constitución y regula los tres estados excepcionales que puede declarar el Estado cuando circunstancias extraordinarias impiden mantener la normalidad con los poderes ordinarios de las autoridades: el estado de alarma, el de excepción y el de sitio. En los tres casos, las medidas adoptadas deben ser las estrictamente indispensables y proporcionadas, y su declaración no interrumpe el funcionamiento de los poderes constitucionales del Estado.",
    "El estado de alarma lo declara el Gobierno mediante decreto en Consejo de Ministros, sin necesidad de autorización parlamentaria previa, ante catástrofes, crisis sanitarias, paralización de servicios esenciales o desabastecimiento. Su duración máxima es de quince días, y solo puede prorrogarse con autorización expresa del Congreso de los Diputados. Durante su vigencia, todas las autoridades civiles y los Cuerpos de Policía autonómicos y locales del territorio afectado quedan bajo las órdenes de la autoridad competente, que normalmente es el propio Gobierno.",
    "El estado de excepción es más grave: procede cuando el libre ejercicio de los derechos, el funcionamiento de las instituciones democráticas o el orden público están tan alterados que ni siquiera bastan las potestades ordinarias del estado de alarma. A diferencia de este, requiere la autorización previa del Congreso de los Diputados, que debe pronunciarse sobre qué derechos se suspenden, qué medidas se adoptan, el ámbito territorial y la duración, con un máximo de treinta días prorrogables por otro plazo igual. Durante el estado de excepción, la detención gubernativa puede prolongarse hasta diez días (frente a las 72 horas ordinarias), con obligación de comunicarlo al juez competente en veinticuatro horas.",
    "El estado de sitio, el más grave de los tres, se reserva para una insurrección o acto de fuerza contra la soberanía, la independencia, la integridad territorial o el ordenamiento constitucional que no pueda resolverse por otros medios. Lo declara el Congreso de los Diputados por mayoría absoluta, a propuesta exclusiva del Gobierno, que asume entonces todas las facultades extraordinarias y designa a la autoridad militar encargada de ejecutar las medidas necesarias en el territorio afectado.",
  ],
};
