import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Real Decreto 207/2024, de 27 de febrero, desarrolla la estructura orgánica básica del Ministerio del Interior, derogando el anterior Real Decreto 734/2020. Al Ministerio le corresponde la propuesta y ejecución de la política del Gobierno en materia de seguridad ciudadana, la promoción de las condiciones para el ejercicio de los derechos fundamentales, el mando superior de las Fuerzas y Cuerpos de Seguridad del Estado, la seguridad privada, la extranjería, la protección internacional y la apatridia, la administración penitenciaria, los procesos electorales, la protección civil, y el tráfico y la seguridad vial.",
    "El Ministerio se organiza en cuatro grandes órganos superiores: la Secretaría de Estado de Seguridad, la Secretaría General de Instituciones Penitenciarias, la Secretaría General de Protección Civil y Emergencias, y la Subsecretaría del Interior. De la Secretaría de Estado de Seguridad dependen la Dirección General de la Policía, la Dirección General de la Guardia Civil, la Dirección General de Relaciones Internacionales y Extranjería, y la Dirección General de Coordinación y Estudios, esta última encargada de coordinar y supervisar a las Fuerzas y Cuerpos de Seguridad del Estado y de colaborar con policías autonómicas y locales.",
    "La Dirección General de la Policía, cuyo titular ostenta rango de subsecretario, ejerce el mando directo de la Policía Nacional bajo la dependencia de la Secretaría de Estado de Seguridad. De ella dependen la Dirección Adjunta Operativa —que coordina, en el nivel central, las Comisarías Generales de Información, Policía Judicial, Seguridad Ciudadana, Extranjería y Fronteras, y Policía Científica—, así como las Subdirecciones Generales de Recursos Humanos y Formación y de Logística e Innovación. De forma paralela, la Dirección General de la Guardia Civil, también con titular de rango de subsecretario, ejerce el mando directo del Cuerpo, con Dirección Adjunta Operativa, Mando de Personal y Mando de Apoyo como órganos dependientes.",
    "Por su parte, la Subsecretaría del Interior asume la representación ordinaria del Departamento y la dirección de sus servicios comunes, con la Secretaría General Técnica, la Dirección General de Política Interior, la Dirección General de Tráfico, la Dirección General de Apoyo a Víctimas del Terrorismo y la Dirección General de Protección Internacional como órganos dependientes. Completan la estructura la Secretaría General de Instituciones Penitenciarias, responsable de la Dirección General de Ejecución Penal y Reinserción Social, y la Secretaría General de Protección Civil y Emergencias, de la que depende la Dirección General de Protección Civil y Emergencias.",
  ],
};
