import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El sistema operativo es el software base que gestiona los recursos hardware y software de un equipo informático, actuando como intermediario entre el usuario, las aplicaciones y el propio hardware. Entre sus funciones principales se encuentran la gestión del procesador, mediante la planificación del tiempo de ejecución asignado a cada proceso; la gestión de memoria, incluida la técnica de memoria virtual, que permite a los programas utilizar un espacio de direcciones mayor que la memoria física realmente disponible empleando el disco de almacenamiento como extensión de la memoria RAM; la gestión de los dispositivos de entrada y salida; y la gestión del sistema de archivos, que organiza y da acceso a la información almacenada. El componente central encargado de gestionar directamente estos recursos es el kernel o núcleo, sobre el que se construyen el resto de servicios y funcionalidades del sistema.",
    "Un proceso es una instancia de un programa en ejecución, a la que el sistema operativo asigna recursos propios —memoria, registros del procesador, un estado de ejecución— y que gestiona de forma independiente respecto de otros procesos que puedan ejecutarse de manera simultánea o concurrente. En función de su capacidad para gestionar usuarios y tareas, los sistemas operativos se clasifican en monousuario o multiusuario, según permitan el acceso de una única persona o de varias simultáneamente, cada una identificada con sus propias credenciales, y en monotarea o multitarea, según permitan ejecutar uno o varios procesos a la vez.",
    "La seguridad de un sistema operativo se apoya, entre otros mecanismos, en el sistema de permisos de archivos, que determina qué usuarios, grupos o procesos pueden leer, modificar o ejecutar un determinado archivo o directorio, constituyendo así un control de acceso básico a la información almacenada, junto con la autenticación de usuarios mediante credenciales como primera barrera de protección frente a accesos no autorizados.",
    "Desde el punto de vista de su modelo de licencia, el software se clasifica en propietario, cuando restringe el acceso a su código fuente y limita su modificación o redistribución conforme a licencias privativas, y libre o de código abierto, cuando permite ejecutar, estudiar, modificar y redistribuir tanto el programa como su código fuente, conforme a las llamadas cuatro libertades definidas por la Free Software Foundation, con independencia de que el software tenga o no un coste económico asociado a su adquisición.",
  ],
};
