import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La globalización se define como un proceso histórico de creciente interconexión e interdependencia entre las economías, sociedades y culturas de distintos países, impulsado fundamentalmente por la liberalización del comercio internacional y de los flujos de capital, el desarrollo acelerado de las tecnologías de la información y la comunicación, y el abaratamiento del transporte de mercancías y personas. Su análisis suele distinguir tres dimensiones interrelacionadas: una dimensión económica, que comprende el comercio internacional, la inversión extranjera directa y la deslocalización de la producción hacia países con costes laborales o fiscales más ventajosos; una dimensión cultural, vinculada a la difusión global de patrones de consumo, información y comunicación; y una dimensión política, relacionada con el papel creciente de organismos internacionales y con nuevas formas de gobernanza supranacional.",
    "En el plano institucional, la gobernanza económica de la globalización se asocia habitualmente a organismos como la Organización Mundial del Comercio, encargada de fijar las reglas del comercio internacional; el Fondo Monetario Internacional, orientado a preservar la estabilidad financiera global; y el Banco Mundial, centrado en la financiación del desarrollo. El Foro Económico Mundial, que se reúne anualmente en Davos (Suiza), constituye un espacio emblemático de encuentro entre líderes económicos y políticos vinculado a esta visión de la globalización.",
    "Frente a este proceso ha surgido un movimiento crítico, conocido como antiglobalización o, más propiamente, altermundista, que agrupa a organizaciones heterogéneas —sindicales, ecologistas, de derechos humanos, campesinas— críticas con determinados efectos de la globalización neoliberal, como el aumento de las desigualdades, la precarización laboral o el impacto ambiental de la producción y el transporte a escala global. Muchos de estos movimientos no rechazan la interconexión global en sí misma, sino que reclaman, bajo el lema «otro mundo es posible», un modelo alternativo más equitativo. Su expresión más visible es el Foro Social Mundial, celebrado por primera vez en Porto Alegre (Brasil) en enero de 2001 como contrapunto explícito al Foro de Davos.",
    "El debate sobre los efectos de la globalización combina el reconocimiento de beneficios como el crecimiento del comercio internacional, el acceso a nuevos mercados y la difusión de innovaciones tecnológicas, con críticas centradas en el aumento de la desigualdad entre países y dentro de ellos, la deslocalización de la actividad industrial hacia economías de menor coste laboral, y la presión a la baja sobre las condiciones de trabajo en determinados sectores productivos, un debate en el que las tecnologías de la información han actuado como uno de los principales catalizadores, al permitir la coordinación en tiempo real de cadenas productivas y mercados financieros a escala mundial.",
  ],
};
