import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Gobierno se compone del Presidente, los Vicepresidentes, en su caso, y los Ministros, y se reúne colegiadamente como Consejo de Ministros. Dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado, y ejerce la función ejecutiva y la potestad reglamentaria de acuerdo con la Constitución y las leyes. Tras cada renovación del Congreso de los Diputados, el Rey propone un candidato a la Presidencia, que debe obtener la confianza de la Cámara: mayoría absoluta en primera votación o mayoría simple en una segunda, 48 horas después; si transcurren dos meses desde la primera votación sin que ningún candidato obtenga la confianza, el Rey disuelve las Cortes y convoca nuevas elecciones.",
    "El control del Gobierno por parte de las Cortes se articula, sobre todo, a través de dos instrumentos: la moción de censura, de carácter constructivo (debe incluir un candidato alternativo a la Presidencia) y que requiere el apoyo de la mayoría absoluta del Congreso; y la cuestión de confianza, que plantea el propio Presidente sobre su programa y que se entiende otorgada por mayoría simple. El Gobierno responde solidariamente de su gestión política ante el Congreso de los Diputados.",
    "El Poder Judicial se rige por el principio de unidad jurisdiccional: la justicia emana del pueblo y se administra en nombre del Rey por Jueces y Magistrados independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley, quedando la jurisdicción militar limitada al ámbito estrictamente castrense y a los supuestos de estado de sitio.",
    "El Consejo General del Poder Judicial es el órgano de gobierno del Poder Judicial, compuesto por el Presidente del Tribunal Supremo, que lo preside, y veinte vocales nombrados por el Rey por un periodo de cinco años (doce entre Jueces y Magistrados y ocho entre juristas de reconocida competencia). El Tribunal Supremo, con jurisdicción en toda España, es el órgano jurisdiccional superior en todos los órdenes, salvo lo dispuesto en materia de garantías constitucionales, que corresponde al Tribunal Constitucional.",
  ],
};
