import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La gramática del español distingue, en primer lugar, entre categorías variables e invariables. Son variables aquellas palabras que admiten flexión: el sustantivo y el adjetivo, que se flexionan en género y número; el determinante y el pronombre, que además de género y número pueden distinguir persona; y el verbo, que se conjuga en persona, número, tiempo, modo y aspecto, distinguiendo tres modos —el indicativo, que presenta la acción como real; el subjuntivo, que la presenta como posible o deseada; y el imperativo, reservado a órdenes e instrucciones—. Son, en cambio, invariables el adverbio, la preposición, la conjunción y la interjección, que no admiten ningún tipo de flexión.",
    "En el plano sintáctico, la oración simple se organiza en torno a un conjunto de funciones básicas: el sujeto, que concuerda en persona y número con el verbo; el complemento directo, que recibe la acción verbal y puede sustituirse por los pronombres átonos «lo, la, los, las»; el complemento indirecto, conmutable por «le, les»; el atributo, propio de las oraciones construidas con verbos copulativos como «ser», «estar» o «parecer», que expresa una cualidad o estado referido al sujeto; y los complementos circunstanciales, que aportan información sobre lugar, tiempo, modo, causa o finalidad, entre otras circunstancias.",
    "La oración compuesta se articula mediante tres procedimientos de relación entre oraciones: la coordinación, en la que dos o más oraciones mantienen su independencia sintáctica y su misma jerarquía, uniéndose mediante conjunciones copulativas, disyuntivas o adversativas; la subordinación, en la que una oración subordinada depende sintácticamente de una oración principal, desempeñando dentro de ella una función propia de un sustantivo, un adjetivo o un adverbio; y la yuxtaposición, en la que las oraciones se unen sin nexo explícito, separadas únicamente por signos de puntuación. Por su parte, la formación de nuevas palabras se produce fundamentalmente mediante derivación —la adición de afijos a una base, como en la formación de adverbios de modo en «-mente» a partir de la forma femenina de un adjetivo— y mediante composición, que une dos o más lexemas en una sola palabra.",
    "Entre los fenómenos gramaticales de uso que con más frecuencia se someten a examen destacan el leísmo, el laísmo y el loísmo, desviaciones respecto del sistema etimológico de pronombres átonos de complemento directo e indirecto, de las cuales la Real Academia Española admite como uso culto extendido el leísmo referido a persona de sexo masculino en singular; y ciertos pares de palabras que se prestan a confusión ortográfica y gramatical, como «sino» —conjunción adversativa que contrapone dos elementos tras una negación previa— frente a «si no» —combinación de la conjunción condicional «si» con el adverbio de negación «no»—, o el conjunto formado por «porque» (conjunción causal), «por qué» (interrogativo o exclamativo), «porqué» (sustantivo, sinónimo de motivo o causa) y «por que» (preposición seguida de pronombre relativo).",
  ],
};
