import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Título III de la Ley Orgánica 4/2000 regula las infracciones en materia de extranjería y su régimen sancionador. El artículo 51.2 clasifica las infracciones en leves, graves y muy graves. Son infracciones leves, entre otras, la omisión o el retraso en comunicar cambios de nacionalidad, estado civil o domicilio, o el retraso de hasta tres meses en solicitar la renovación de una autorización caducada. Son infracciones graves, entre otras, encontrarse irregularmente en España por carecer de autorización de residencia o tenerla caducada más de tres meses sin haber solicitado su renovación, o trabajar sin la autorización correspondiente. Son infracciones muy graves, entre otras, inducir, promover, favorecer o facilitar con ánimo de lucro la inmigración clandestina o la permanencia irregular en España, cuando el hecho no constituya delito, y las conductas de discriminación racial, étnica o religiosa que tampoco constituyan delito.",
    "Las sanciones, reguladas en el artículo 55, consisten en multa: hasta 500 euros para las infracciones leves, de 501 a 10.000 euros para las graves, y de 10.001 a 100.000 euros para las muy graves (con cuantías específicas más elevadas para determinadas infracciones de transportistas). La competencia sancionadora corresponde, con carácter general, al Subdelegado del Gobierno o al Delegado del Gobierno en las comunidades autónomas uniprovinciales, salvo para las infracciones relacionadas con actividades contrarias a la seguridad nacional, cuya competencia recae en el Secretario de Estado de Seguridad. Las infracciones prescriben a los tres años (muy graves), dos años (graves) y seis meses (leves).",
    "Frente a la multa, el artículo 57 permite imponer la expulsión del territorio español por la comisión de infracciones muy graves o de determinadas infracciones graves, así como cuando el extranjero haya sido condenado por un delito doloso con pena privativa de libertad superior a un año. En ningún caso pueden imponerse conjuntamente las sanciones de expulsión y multa. La ley protege frente a la expulsión a determinados colectivos, como los nacidos en España con residencia legal en los últimos cinco años o los residentes de larga duración. La expulsión conlleva, con carácter general, una prohibición de entrada de hasta cinco años, que excepcionalmente puede alcanzar los diez años cuando el extranjero suponga una amenaza grave para el orden público, la seguridad pública, la seguridad nacional o la salud pública.",
    "Durante la tramitación de un expediente sancionador que pueda concluir en expulsión, el instructor puede adoptar medidas cautelares como la presentación periódica, la residencia obligatoria en un lugar determinado, la retirada del pasaporte, la detención cautelar por un máximo de setenta y dos horas o, previa autorización judicial, el internamiento preventivo en un Centro de Internamiento de Extranjeros (CIE), cuya duración máxima es de sesenta días. Los CIE no tienen carácter penitenciario y solo privan al interno del derecho ambulatorio; los menores no pueden ser internados. Por último, la ley protege especialmente a las víctimas de tráfico ilícito de personas y de trata de seres humanos, que pueden quedar exentas de responsabilidad administrativa y no ser expulsadas si denuncian a los responsables o cooperan con las autoridades, disponiendo las víctimas de trata, además, de un período mínimo de noventa días de restablecimiento y reflexión.",
  ],
};
