import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 31/1995, de 8 de noviembre, de Prevención de Riesgos Laborales, desarrolla el mandato del artículo 40.2 de la Constitución, que encomienda a los poderes públicos velar por la seguridad e higiene en el trabajo, y traspone al ordenamiento español la Directiva 89/391/CEE. Su ámbito de aplicación, según el artículo 3, comprende tanto las relaciones laborales reguladas por el Estatuto de los Trabajadores como las de carácter administrativo o estatutario del personal al servicio de las Administraciones públicas, si bien la propia Ley prevé peculiaridades para determinadas actividades de la función pública, entre ellas expresamente las de las Fuerzas Armadas, la Policía y los servicios operativos de protección civil, cuando sus particularidades resulten incompatibles con su aplicación directa.",
    "El artículo 4 de la Ley fija las definiciones básicas de la materia: la prevención es el conjunto de actividades o medidas adoptadas en todas las fases de actividad de la empresa para evitar o disminuir los riesgos derivados del trabajo; el riesgo laboral es la posibilidad de que un trabajador sufra un daño derivado del trabajo, valorándose conjuntamente su probabilidad y severidad; los daños derivados del trabajo son las enfermedades, patologías o lesiones sufridas con motivo u ocasión del trabajo; y el riesgo laboral grave e inminente es aquel que resulte racionalmente probable que se materialice en un futuro inmediato con un daño grave para la salud. El mismo precepto define también el equipo de trabajo, la condición de trabajo y el equipo de protección individual, entendido este último como cualquier equipo destinado a ser llevado o sujetado por el trabajador para protegerle de uno o varios riesgos que amenacen su seguridad o su salud.",
    "El artículo 14 reconoce a los trabajadores el derecho a una protección eficaz en materia de seguridad y salud en el trabajo, derecho que tiene como correlato un deber de protección del empresario —y, respecto del personal a su servicio, también de las Administraciones públicas— que engloba los derechos de información, consulta y participación, formación preventiva, paralización de la actividad ante un riesgo grave e inminente y vigilancia del estado de salud; el coste de estas medidas no puede recaer en ningún caso sobre los trabajadores. El artículo 15 desarrolla los principios que deben inspirar toda la acción preventiva: evitar los riesgos, evaluar los que no se puedan evitar, combatirlos en su origen, adaptar el trabajo a la persona, tener en cuenta la evolución de la técnica, sustituir lo peligroso por lo que entrañe poco o ningún peligro, planificar la prevención de forma coherente y anteponer la protección colectiva a la individual.",
    "Para la Policía Nacional, el Real Decreto 2/2006, de 16 de enero, adapta estos principios generales a las peculiaridades de la función policial. Su artículo 1 tiene por objeto adoptar las medidas necesarias para promover la seguridad y salud en el trabajo de los funcionarios del Cuerpo Nacional de Policía, aplicando los principios y criterios de la Ley 31/1995 a las peculiaridades organizativas y a las especiales características de las funciones que tienen encomendadas. El artículo 3 reconoce a estos funcionarios el derecho a una protección eficaz que comprende la información, la formación preventiva, la posibilidad de realizar propuestas y participar en la prevención de los riesgos de su puesto, y la vigilancia periódica de la salud, sin perjuicio de los riesgos específicos que deben asumir en situaciones de riesgo grave, catástrofe y emergencia social. El artículo 4 recoge los mismos principios generales de acción preventiva de la Ley 31/1995, añadiendo el de estimular el interés de los funcionarios por la seguridad y la salud en el trabajo mediante mecanismos de formación e información adaptados a la actividad policial.",
  ],
};
