import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Título II de la Constitución regula la Corona. El Rey es definido como el Jefe del Estado, símbolo de su unidad y permanencia, que arbitra y modera el funcionamiento regular de las instituciones y asume la más alta representación del Estado español en las relaciones internacionales. La Corona es hereditaria en los sucesores de la dinastía histórica, y el orden de sucesión sigue la primogenitura y representación, con preferencia de la línea anterior sobre las posteriores, del grado más próximo sobre el más remoto, del varón sobre la mujer en el mismo grado, y de la persona de más edad sobre la de menos en el mismo sexo.",
    "Cuando el Rey es menor de edad, ejerce la regencia el padre o la madre del Rey, o el pariente mayor de edad más próximo a suceder; si el Rey queda inhabilitado, la regencia corresponde al Príncipe heredero, si es mayor de edad. Si no hay nadie a quien corresponda la regencia, la nombran las Cortes Generales, y puede estar compuesta de una, tres o cinco personas. La tutela del Rey menor recae en la persona designada en su testamento por el Rey difunto, o en su defecto en el padre o madre mientras permanezcan viudos, sin que el cargo de tutor pueda acumularse con el de regente salvo en los padres o ascendientes directos del Rey.",
    "El artículo 62 enumera las funciones del Rey: sancionar y promulgar las leyes; convocar y disolver las Cortes Generales y convocar elecciones y referendos; proponer y nombrar al Presidente del Gobierno; nombrar y separar a los ministros a propuesta del Presidente; expedir los decretos acordados en Consejo de Ministros; ostentar el mando supremo de las Fuerzas Armadas; ejercer el derecho de gracia; y el Alto Patronazgo de las Reales Academias, entre otras.",
    "La persona del Rey es inviolable y no está sujeta a responsabilidad. Para que sus actos sean válidos necesitan el refrendo del Presidente del Gobierno o, en su caso, de los ministros competentes (y el nombramiento del Presidente del Gobierno y la disolución de las Cortes, del Presidente del Congreso), de manera que la responsabilidad de esos actos recae precisamente en quien los refrenda, no en el Rey.",
  ],
};
