import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La migración se define como el desplazamiento de personas desde un lugar de origen a otro de destino, con vocación de cierta permanencia, y suele explicarse mediante el llamado modelo push-pull: de un lado, factores de expulsión en el país de origen, como la pobreza, el desempleo, los conflictos armados o la persecución política, étnica o religiosa; de otro, factores de atracción en el país de destino, como las oportunidades laborales, la estabilidad institucional o la posibilidad de reagrupación familiar. Los términos emigrante e inmigrante designan a la misma persona desde las dos perspectivas de un mismo proceso: emigrante desde la óptica del país que abandona, e inmigrante desde la óptica del país al que llega.",
    "La incorporación de las personas inmigrantes a la sociedad de acogida puede articularse conforme a distintos modelos. El modelo de asimilación exige la adopción plena de la cultura y los valores de la sociedad receptora, con la consiguiente pérdida de la identidad cultural de origen. Frente a él, el modelo de integración concibe este proceso como bidireccional, en el que tanto la persona inmigrante como la sociedad de acogida se adaptan mutuamente, sin que ello implique renunciar necesariamente a los propios rasgos culturales; un tercer modelo, el multiculturalismo, aboga por la coexistencia de distintas comunidades culturales dentro de una misma sociedad, reconociendo expresamente su diversidad.",
    "En España, la gestión de la inmigración se articula institucionalmente a través del Ministerio del Interior —que, por medio de la Dirección General de la Policía, ejerce el control de fronteras, el régimen documental de los extranjeros y la tramitación de expulsiones— y del Ministerio de Inclusión, Seguridad Social y Migraciones, competente en materia de integración, régimen general de la inmigración y protección internacional. Este marco institucional se apoya en la normativa ya analizada en otros temas del Bloque I, como la Ley Orgánica 4/2000, sobre derechos y libertades de los extranjeros en España, la Ley 12/2009, reguladora del derecho de asilo, y el Real Decreto 240/2007, relativo a la entrada y residencia de ciudadanos de la Unión Europea. A escala europea, la Agencia Europea de la Guardia de Fronteras y Costas (Frontex) apoya a los Estados miembros en la vigilancia de las fronteras exteriores comunes y en la gestión coordinada de los flujos migratorios, en el marco del Sistema Europeo Común de Asilo.",
    "Entre los fenómenos sociales característicos de los procesos migratorios contemporáneos destacan los llamados flujos migratorios mixtos, en los que se desplazan conjuntamente personas con perfiles y motivaciones muy distintas —migrantes económicos, solicitantes de protección internacional, víctimas de trata de seres humanos o menores no acompañados—, lo que exige una identificación individualizada de cada situación para articular la respuesta institucional adecuada. Frente a estos procesos, persisten actitudes de xenofobia, entendida como el rechazo, temor o aversión hacia las personas extranjeras por razón de su origen o nacionalidad, cuya prevención constituye uno de los principales retos de las políticas de integración, junto con el acceso equitativo al mercado laboral, la educación y la vivienda.",
  ],
};
