import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "En el ámbito de la seguridad, la inteligencia se entiende como el producto resultante de un proceso de recogida, evaluación, análisis e interpretación de información, cuya finalidad es apoyar la toma de decisiones de las autoridades competentes en materia de seguridad, defensa o persecución del delito. Este producto se distingue de la mera información, entendida como los datos en bruto sin procesar recogidos de las distintas fuentes disponibles, ya que la inteligencia añade valor a esos datos a través de un proceso sistemático de evaluación, contraste e interpretación que los hace útiles para la toma de decisiones.",
    "Este proceso se articula clásicamente a través del denominado ciclo de inteligencia, estructurado en cuatro fases: la dirección o planificación, en la que se determinan las necesidades de información que deben satisfacerse; la obtención, en la que se recogen los datos a través de fuentes de naturaleza diversa, como las fuentes abiertas u OSINT —información disponible públicamente y de acceso lícito, como medios de comunicación, redes sociales o registros públicos—, las fuentes humanas o HUMINT, o la interceptación de comunicaciones y señales o SIGINT; la elaboración o análisis, en la que la información recogida se evalúa, contrasta e interpreta para producir inteligencia propiamente dicha; y la difusión, en la que el producto final se traslada a los destinatarios encargados de tomar las decisiones correspondientes.",
    "En el ámbito específicamente policial, el análisis de inteligencia criminal permite identificar patrones, tendencias, relaciones y vínculos entre los datos disponibles sobre actividades delictivas —personas, grupos organizados, modus operandi—, desempeñando un papel preventivo fundamental frente a fenómenos como el terrorismo y el crimen organizado, al permitir anticipar amenazas e identificar redes y estructuras criminales, complementando así a la investigación reactiva que se desarrolla tras la comisión de un delito concreto y orientando la actuación operativa de las Fuerzas y Cuerpos de Seguridad.",
    "En España, el Centro Nacional de Inteligencia (CNI), regulado por la Ley 11/2002 y adscrito al Ministerio de la Presidencia, es el organismo público encargado de facilitar al Presidente del Gobierno y al Gobierno las informaciones, análisis, estudios o propuestas necesarios para prevenir y evitar cualquier riesgo o amenaza que afecte a la seguridad, la defensa o los intereses de España. Junto a la actividad de inteligencia propiamente dicha, la contrainteligencia agrupa el conjunto de actividades orientadas a detectar, prevenir y neutralizar las actividades de espionaje, sabotaje o infiltración que servicios extranjeros u otros actores hostiles puedan dirigir contra los propios intereses de seguridad y defensa del Estado.",
  ],
};
