import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 12/2009, de 30 de octubre, reguladora del derecho de asilo y de la protección subsidiaria, desarrolla el artículo 13.4 de la Constitución y establece los términos en que las personas nacionales de países no comunitarios y las apátridas pueden gozar en España de protección internacional. Esta protección adopta dos formas: el derecho de asilo, dispensado a quienes se reconoce la condición de refugiado por tener fundados temores de ser perseguidos por motivos de raza, religión, nacionalidad, opiniones políticas, pertenencia a determinado grupo social, género, orientación o identidad sexual; y la protección subsidiaria, para quienes, sin reunir los requisitos del asilo, se enfrentarían a un riesgo real de sufrir alguno de los daños graves definidos en la ley —la condena a pena de muerte, la tortura o los tratos inhumanos o degradantes, o las amenazas graves contra la vida por violencia indiscriminada en un conflicto— si regresaran a su país. La protección concedida consiste fundamentalmente en la no devolución ni expulsión de la persona beneficiaria.",
    "Tanto el asilo como la protección subsidiaria quedan excluidos, entre otros supuestos, para quienes hayan cometido delitos contra la paz, de guerra o contra la humanidad, o un delito grave común antes de ser admitidos como refugiados; y se deniegan en todo caso a quienes constituyan, por razones fundadas, un peligro para la seguridad de España, o a quienes, tras una condena firme por delito grave, representen una amenaza para la comunidad.",
    "El procedimiento se inicia con la comparecencia personal del solicitante, que debe realizarse sin demora y, en todo caso, en el plazo máximo de un mes desde la entrada en España o desde los hechos que motiven el temor fundado; la entrada ilegal no puede sancionarse si la realiza quien reúne los requisitos para la protección internacional. Presentada la solicitud, el solicitante tiene derecho a asistencia jurídica gratuita e intérprete, a que se comunique su solicitud al ACNUR, y sobre todo a no ser devuelto, retornado ni expulsado mientras se resuelve, salvo la adopción de medidas cautelares por motivos de salud o seguridad públicas.",
    "El Ministro del Interior, a propuesta de la Oficina de Asilo y Refugio, puede acordar la no admisión a trámite de una solicitud presentada en territorio español mediante resolución motivada, que debe notificarse en el plazo máximo de un mes; si transcurre este plazo sin notificación, la solicitud se entiende admitida a trámite y el solicitante permanece provisionalmente en España. Cuando la solicitud se presenta en un puesto fronterizo, el plazo para notificar la inadmisión o denegación se reduce a cuatro días (ampliable a diez si el ACNUR lo solicita motivadamente), pudiendo el interesado pedir el reexamen de la decisión en el plazo de dos días, lo que suspende sus efectos.",
  ],
};
