import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La seguridad ciudadana se entiende como la situación en la que las personas pueden ejercer con normalidad sus derechos y libertades y desarrollar su vida cotidiana, protegidas frente a los riesgos y amenazas que puedan afectar a su integridad, a sus bienes o a la convivencia social. No se concibe, por tanto, como un fin en sí misma, sino como un presupuesto necesario para el ejercicio efectivo de derechos y libertades y para el desarrollo de una convivencia social pacífica, lo que exige que su protección se articule siempre de forma compatible y proporcionada con el respeto a esos mismos derechos. En el ordenamiento español, la Ley Orgánica 4/2015 configura la protección de la seguridad ciudadana como una competencia del Estado, ejercida sin perjuicio de las que corresponden a las Comunidades Autónomas y a las Corporaciones Locales, a través de las Fuerzas y Cuerpos de Seguridad y bajo la dirección del Gobierno.",
    "El análisis de la seguridad distingue habitualmente entre su dimensión objetiva, medida mediante indicadores estadísticos como las tasas de criminalidad o de victimización, y su dimensión subjetiva o percepción de inseguridad, que refleja el sentimiento de temor de la ciudadanía frente al delito y que no siempre coincide con los datos objetivos disponibles. A este enfoque tradicional, centrado en el Estado y en el orden público, se ha sumado en las últimas décadas el concepto de seguridad humana, impulsado especialmente desde el Programa de las Naciones Unidas para el Desarrollo en su Informe sobre Desarrollo Humano de 1994, que desplaza el foco hacia la protección de la persona frente a amenazas que comprometen su supervivencia, sus medios de vida y su dignidad, abarcando dimensiones como la seguridad económica, alimentaria, sanitaria, ambiental, personal, comunitaria y política.",
    "En cuanto a las estrategias de intervención, se distingue entre la prevención social, orientada a actuar sobre las causas estructurales del comportamiento delictivo —educación, empleo, cohesión social—, y la prevención situacional, que busca reducir las oportunidades de comisión de delitos mediante la intervención sobre el entorno físico, a través de medidas como la mejora de la iluminación, la videovigilancia, el diseño urbano o el control de accesos. En esta línea se enmarca también el modelo de policía de proximidad o policía comunitaria, que persigue establecer una relación estable y de confianza entre la institución policial y la comunidad a la que sirve, priorizando la prevención, la resolución de problemas locales de convivencia y la colaboración activa de la ciudadanía frente a un modelo puramente reactivo o represivo.",
    "Finalmente, las nuevas tecnologías —videovigilancia inteligente, analítica de datos masivos e inteligencia artificial aplicada a la detección de patrones delictivos— se han incorporado progresivamente como herramientas de apoyo a las estrategias de prevención, detección e investigación policial. Su implantación plantea, no obstante, retos de primer orden relacionados con la protección de los datos personales y el respeto a los derechos fundamentales de la ciudadanía, lo que exige contar con un marco normativo y de garantías adecuado, como el que ofrece la Ley Orgánica 7/2021 para el tratamiento de datos con fines policiales, ya analizada en otros temas de este temario.",
  ],
};
