import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La construcción europea arranca con el Tratado de París de 1951, que crea la Comunidad Europea del Carbón y del Acero, y continúa con los Tratados de Roma de 1957, que crean la Comunidad Económica Europea y el Euratom. El Tratado de Maastricht de 1992 da origen a la Unión Europea propiamente dicha, articulada inicialmente en tres pilares. Tras las reformas de Ámsterdam y Niza, el Tratado de Lisboa, firmado en 2007 y en vigor desde el 1 de diciembre de 2009, suprime la estructura de pilares, dota a la Unión de personalidad jurídica propia y deja como tratados vigentes el Tratado de la Unión Europea (TUE) y el Tratado de Funcionamiento de la Unión Europea (TFUE), con idéntico valor jurídico. España ingresó en las entonces Comunidades Europeas el 1 de enero de 1986.",
    "El artículo 13 del TUE enumera las siete instituciones de la Unión: el Parlamento Europeo, elegido cada cinco años por sufragio universal directo; el Consejo Europeo, formado por los Jefes de Estado o de Gobierno, que fija las grandes orientaciones políticas sin ejercer función legislativa; el Consejo de la Unión Europea, que representa a los gobiernos y comparte con el Parlamento la función legislativa y presupuestaria; la Comisión Europea, guardiana de los Tratados y titular, con carácter general, del monopolio de la iniciativa legislativa; el Tribunal de Justicia de la Unión Europea, que garantiza el respeto del Derecho de la Unión; el Banco Central Europeo; y el Tribunal de Cuentas. Conviene no confundir el TJUE, con sede en Luxemburgo, con el Tribunal Europeo de Derechos Humanos, que pertenece al Consejo de Europa, organización internacional distinta de la Unión Europea.",
    "El Derecho de la Unión se divide en Derecho originario, formado por los Tratados, y Derecho derivado, regulado en el artículo 288 del TFUE, que comprende los reglamentos, las directivas, las decisiones, las recomendaciones y los dictámenes. El reglamento tiene alcance general y es directamente aplicable en todos los Estados miembros sin necesidad de norma interna que lo desarrolle; la directiva, en cambio, obliga en cuanto al resultado que debe alcanzarse, dejando a cada Estado la elección de la forma y los medios, por lo que exige una transposición posterior. Las decisiones son obligatorias en todos sus elementos para sus destinatarios, mientras que recomendaciones y dictámenes carecen de fuerza vinculante.",
    "En el ámbito de la cooperación policial y judicial destaca Europol, la Agencia de la Unión Europea para la Cooperación Policial, con sede en La Haya, que apoya a los Estados miembros en la prevención y lucha contra la delincuencia grave, organizada y el terrorismo, sin disponer de competencias ejecutivas propias sobre el terreno. Junto a ella operan Eurojust, que coordina la cooperación judicial penal, y Frontex, la Agencia Europea de la Guardia de Fronteras y Costas. Estos organismos pertenecen a la Unión Europea y deben distinguirse de otras entidades ajenas a ella, como la Interpol o el propio Consejo de Europa.",
  ],
};
