import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "Las Cortes Generales representan al pueblo español, son inviolables y están formadas por dos Cámaras: el Congreso de los Diputados y el Senado. Ejercen la potestad legislativa del Estado, aprueban sus presupuestos, controlan la acción del Gobierno y ejercen las demás competencias que les atribuye la Constitución. El Congreso se compone de entre 300 y 400 diputados (350 en la práctica), elegidos por sufragio universal mediante listas cerradas y sistema proporcional, con la provincia como circunscripción electoral. El Senado es la Cámara de representación territorial: la mayoría de sus miembros se eligen directamente por provincias, y el resto son designados por los Parlamentos autonómicos.",
    "El mandato de Diputados y Senadores dura cuatro años. No están sujetos a mandato imperativo, gozan de inviolabilidad por las opiniones expresadas en el ejercicio de sus funciones y de inmunidad, de modo que solo pueden ser detenidos en caso de flagrante delito y no pueden ser inculpados ni procesados sin la autorización previa de la Cámara a la que pertenecen. Las Cámaras funcionan en Pleno y en Comisiones, y se reúnen en dos periodos ordinarios de sesiones cada año.",
    "En el procedimiento legislativo, la iniciativa corresponde al Gobierno (proyectos de ley), al Congreso y al Senado (proposiciones de ley) y, dentro de ciertos límites, a la iniciativa popular. Los textos se tramitan primero en el Congreso y después en el Senado, que puede vetarlos por mayoría absoluta —veto que el Congreso puede levantar— o introducir enmiendas que el Congreso acepta o rechaza por mayoría simple.",
    "En su función de control al Gobierno, las Cortes disponen de preguntas e interpelaciones, de la moción de censura —de carácter constructivo, ya que exige proponer un candidato alternativo a la Presidencia y se aprueba por mayoría absoluta del Congreso— y de la cuestión de confianza, planteada por el propio Presidente del Gobierno y que se entiende otorgada por mayoría simple. El Rey disuelve las Cortes a propuesta del Presidente del Gobierno, aunque no cabe la disolución mientras esté en trámite una moción de censura, ni antes de que transcurra un año desde la disolución anterior, ni durante la vigencia de los estados de alarma, excepción o sitio.",
  ],
};
