import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 9/2015, de 28 de julio, de Régimen de Personal de la Policía Nacional, reúne en un único texto con rango de ley orgánica el régimen estatutario de los funcionarios de carrera de la Policía Nacional, actualizando la regulación dispersa que hasta entonces procedía de la Ley Orgánica 2/1986 y de normas reglamentarias. La Policía Nacional se define como un instituto armado de naturaleza civil, con estructura jerarquizada, cuyo mando superior corresponde al Ministro del Interior —a través del Secretario de Estado de Seguridad— y cuyo mando directo ejerce el Director General de la Policía. La condición de funcionario de carrera se adquiere mediante la superación del proceso selectivo, el nombramiento, el acatamiento de la Constitución y la toma de posesión, y se pierde por jubilación, renuncia, pérdida de la nacionalidad, separación del servicio o inhabilitación firmes.",
    "La ley recoge un amplio catálogo de derechos individuales —dignidad en el trabajo, no discriminación, defensa jurídica, progresión en la carrera, formación permanente, conciliación de la vida personal y laboral— y de derechos de ejercicio colectivo, como la sindicación en organizaciones formadas exclusivamente por Policías Nacionales, sin que en ningún caso puedan ejercer el derecho de huelga. Entre los deberes destacan la fidelidad a la Constitución, la obediencia debida, el secreto profesional y el deber de residencia, completados por un estricto régimen de incompatibilidades que impide compatibilizar un segundo puesto de trabajo cuando ello comprometa la imparcialidad o el prestigio de la institución.",
    "En cuanto a su organización, el Cuerpo Nacional de Policía se estructura en cuatro escalas —Superior, Ejecutiva, de Subinspección y Básica—, cada una con funciones propias de dirección, mando, supervisión y ejecución material, respectivamente, y clasificadas en los subgrupos A1, A2 y C1. El ingreso se realiza mediante oposición libre a las categorías de Inspector y Policía, exigiendo título de grado o de bachiller según el caso, y comprende una fase de oposición, un curso de formación y un módulo de formación práctica en puesto de trabajo, todo ello desarrollado con detalle por el Reglamento de procesos selectivos y formación de la Policía Nacional, aprobado por el Real Decreto 853/2022. La carrera profesional se articula en carrera vertical, mediante ascenso por promoción interna en las modalidades de concurso-oposición y antigüedad selectiva, y carrera horizontal, mediante la progresión en la estructura de puestos de trabajo.",
    "La ley regula igualmente las situaciones administrativas —servicio activo, servicios especiales, excedencia en sus distintas modalidades, suspensión de funciones y segunda actividad—, siendo esta última una situación específica de la Policía Nacional orientada a garantizar la aptitud psicofísica adecuada para el servicio, a la que se puede acceder por insuficiencia de aptitudes, por petición propia al alcanzar la edad fijada para cada escala o por veinticinco años de servicios efectivos.",
    "Completa este marco normativo la Ley Orgánica 4/2010, del Régimen disciplinario del Cuerpo Nacional de Policía, que tipifica las faltas muy graves, graves y leves en que pueden incurrir los Policías Nacionales —como el abandono de servicio, el abuso de atribuciones o la insubordinación— y establece las sanciones correspondientes, desde la separación del servicio hasta el apercibimiento, así como los plazos de prescripción de las faltas (tres años las muy graves, dos las graves y un mes las leves) y el procedimiento disciplinario aplicable, presidido por los principios de legalidad, contradicción y presunción de inocencia.",
  ],
};
