import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 2/1986, de 13 de marzo, de Fuerzas y Cuerpos de Seguridad, desarrolla el mandato del artículo 104 de la Constitución y regula de forma conjunta a las Fuerzas y Cuerpos de Seguridad del Estado, de las Comunidades Autónomas y de las Corporaciones Locales. La Seguridad Pública es competencia exclusiva del Estado, correspondiendo su mantenimiento al Gobierno de la Nación, sin perjuicio de la participación de comunidades autónomas y corporaciones locales en los términos que la propia ley establece.",
    "La ley fija los principios básicos de actuación de todos los miembros de las Fuerzas y Cuerpos de Seguridad: adecuación al ordenamiento jurídico, relaciones con la comunidad presididas por la proporcionalidad y el uso excepcional de armas, tratamiento respetuoso de los detenidos, dedicación profesional permanente, secreto profesional y responsabilidad personal por sus actos. También establece disposiciones estatutarias comunes, como la incompatibilidad con otras actividades y la prohibición absoluta del derecho de huelga.",
    "Las Fuerzas y Cuerpos de Seguridad del Estado están integradas por el Cuerpo Nacional de Policía, Instituto Armado de naturaleza civil, y la Guardia Civil, Instituto Armado de naturaleza militar; ambos dependen del Ministro del Interior, si bien la Guardia Civil también depende del Ministro de Defensa en el cumplimiento de misiones militares. La ley distribuye tanto el ámbito territorial (el CNP en capitales de provincia y núcleos urbanos determinados, la Guardia Civil en el resto del territorio) como las competencias materiales entre ambos cuerpos, reservando al CNP funciones como el DNI, pasaportes y extranjería, y a la Guardia Civil el resguardo fiscal, tráfico interurbano y custodia de fronteras, entre otras.",
    "Un capítulo específico regula las Unidades Orgánicas de Policía Judicial, que dependen orgánicamente del Ministerio del Interior pero funcionalmente de Jueces, Tribunales y Ministerio Fiscal, desarrolladas con detalle por el Real Decreto 769/1987. La ley regula también la creación de Cuerpos de Policía por las Comunidades Autónomas cuyos Estatutos lo prevean, los mecanismos de coordinación (destacando el Consejo de Política de Seguridad), y las funciones de las Policías Locales, centradas en el tráfico urbano, la policía administrativa municipal y la colaboración con el resto de cuerpos policiales.",
  ],
};
