import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 40/2015, de 1 de octubre, de Régimen Jurídico del Sector Público, regula las bases del funcionamiento interno de las Administraciones Públicas: su organización y funcionamiento, los principios del sistema de responsabilidad de las Administraciones y de la potestad sancionadora, y la organización y funcionamiento de la Administración General del Estado y su sector público institucional para el desarrollo de sus actividades. Se aplica a la Administración General del Estado, a las Administraciones de las Comunidades Autónomas, a las Entidades que integran la Administración Local y al sector público institucional, entendido como el conjunto de organismos y entidades de derecho público vinculados a una Administración, las entidades de derecho privado vinculadas o dependientes de ellas y las Universidades públicas.",
    "En materia de órganos administrativos, la ley define el órgano como la unidad administrativa a la que se atribuyen funciones con efectos jurídicos frente a terceros o cuya actuación tiene carácter preceptivo, y regula las técnicas de alteración del ejercicio de competencias: delegación, avocación y encomienda de gestión. La competencia es irrenunciable y se ejerce por el órgano que la tenga atribuida como propia, salvo estas excepciones; quedan excluidas de la delegación materias como las atribuidas a la Jefatura del Estado, a la Presidencia del Gobierno o a las Cortes Generales, y la adopción de disposiciones de carácter general.",
    "La ley establece también los principios de la potestad sancionadora —legalidad, tipicidad, responsabilidad, proporcionalidad y prescripción, con plazos generales de tres años para las infracciones muy graves, dos para las graves y seis meses para las leves— y del sistema de responsabilidad patrimonial de las Administraciones Públicas, que indemnizan a los particulares por toda lesión que sufran en sus bienes y derechos como consecuencia del funcionamiento normal o anormal de los servicios públicos, salvo fuerza mayor o deber jurídico de soportar el daño.",
    "Por último, la norma regula la organización de la Administración General del Estado, distinguiendo entre órganos superiores (Ministros y Secretarios de Estado) y órganos directivos (Subsecretarios, Directores generales, Subdirectores generales), la organización territorial mediante los Delegados y Subdelegados del Gobierno, y el sector público institucional estatal, clasificado en organismos autónomos, entidades públicas empresariales, agencias estatales, sociedades mercantiles estatales, consorcios y fundaciones del sector público. Regula además las relaciones interadministrativas basadas en la cooperación voluntaria y la coordinación obligatoria, y los órganos de cooperación entre el Estado y las Comunidades Autónomas, entre los que destaca la Conferencia de Presidentes.",
  ],
};
