import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 4/2015, de 30 de marzo, de protección de la seguridad ciudadana, sustituyó a la anterior LO 1/1992 y tiene por objeto regular un conjunto de actuaciones de las Administraciones Públicas y de las Fuerzas y Cuerpos de Seguridad dirigidas a proteger la seguridad ciudadana, entendida como un requisito esencial para el pleno ejercicio de los derechos y libertades reconocidos en la Constitución. La ley combina normas de organización, actuaciones policiales concretas y un régimen sancionador administrativo.",
    "Entre las actuaciones policiales reguladas destacan las relativas a la identificación de personas: los agentes pueden requerir la identificación cuando existan indicios de que una persona ha participado en la comisión de una infracción, o cuando, de forma razonable y proporcionada, resulte necesario para el ejercicio de las funciones de protección de la seguridad. Si la identificación no puede lograrse por otro medio, la persona puede ser requerida para acompañar a los agentes a dependencias próximas. La ley regula también los registros corporales externos y superficiales, que deben practicarse respetando la dignidad de la persona y, cuando impliquen actos de reconocimiento corporal, por un agente del mismo sexo. Los miembros de las Fuerzas y Cuerpos de Seguridad, por su parte, están obligados a identificarse en sus actuaciones mediante el carné profesional o el número de identificación visible.",
    "El régimen sancionador clasifica las infracciones en muy graves, graves y leves. Son infracciones muy graves, entre otras, la fabricación, tenencia o uso de armas prohibidas sin la documentación exigible; son infracciones graves, por ejemplo, el consumo o la tenencia de drogas tóxicas en lugares públicos cuando no constituya delito; y son infracciones leves las faltas de respeto a los agentes de la autoridad en el ejercicio de sus funciones, entre otras conductas. Las infracciones muy graves prescriben a los dos años, las graves al año y las leves a los seis meses.",
    "Las sanciones consisten fundamentalmente en multas graduadas según la gravedad de la infracción, pudiendo imponerse además sanciones accesorias como el comiso de las armas, sustancias o instrumentos relacionados con la infracción. La competencia para imponer las sanciones corresponde, con carácter general, a los Delegados y Subdelegados del Gobierno según el ámbito territorial afectado y la gravedad de la infracción, sin perjuicio de las competencias específicas que la propia ley u otras normas atribuyan a distintos órganos o a las Comunidades Autónomas y Entidades Locales.",
  ],
};
