import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 50/1997, de 27 de noviembre, del Gobierno, desarrolla el Título IV de la Constitución y regula la composición, organización y funcionamiento del Gobierno de la Nación. El Gobierno se compone del Presidente, del Vicepresidente o Vicepresidentes en su caso, y de los Ministros, y dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado, ejerciendo la función ejecutiva y la potestad reglamentaria de acuerdo con la Constitución y las leyes. Actúa de forma colegiada, si bien cada Ministro tiene competencia y responsabilidad propia en la esfera de su Departamento.",
    "Son órganos del Gobierno el Consejo de Ministros y las Comisiones Delegadas del Gobierno. El Consejo de Ministros aprueba los proyectos de ley, los decretos-leyes y los decretos legislativos; las Comisiones Delegadas, creadas por Real Decreto a propuesta del Presidente, coordinan la elaboración de directrices en materias comunes a varios Ministerios. Como órganos de colaboración y apoyo, la ley regula los Secretarios de Estado, la Comisión General de Secretarios de Estado y Subsecretarios, el Secretariado del Gobierno y los Gabinetes. En el territorio autonómico, los Delegados del Gobierno representan ordinariamente al Gobierno y dirigen la Administración General del Estado en la Comunidad Autónoma correspondiente.",
    "La norma regula también el estatuto personal de los miembros del Gobierno: requisitos para el cargo (ser español, mayor de edad y disfrutar de los derechos de sufragio activo y pasivo), su nombramiento y cese por el Rey a propuesta del Presidente, el régimen de suplencia, un estricto régimen de incompatibilidades con cualquier otra actividad representativa, función pública o actividad profesional o mercantil, y su responsabilidad penal ante la Sala de lo Penal del Tribunal Supremo. Regula asimismo la figura del Gobierno en funciones tras elecciones generales, la pérdida de la confianza parlamentaria, la dimisión o el fallecimiento del Presidente, limitando sus facultades al despacho ordinario de los asuntos públicos.",
    "Por último, la ley establece el procedimiento de elaboración de anteproyectos de ley y reglamentos, con fases de consulta pública previa, memoria de análisis de impacto normativo, audiencia e información pública e informes y dictámenes preceptivos, enmarcado en la planificación normativa anual del Gobierno. Cierra la norma la regulación del control del Gobierno, sujeto al control político de las Cortes Generales, al control jurisdiccional de Jueces y Tribunales, y al control económico-presupuestario del Tribunal de Cuentas.",
  ],
};
