import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Real Decreto 240/2007, de 16 de febrero, regula las condiciones para el ejercicio de los derechos de entrada, salida, libre circulación, estancia, residencia, residencia permanente y trabajo en España de los ciudadanos de otros Estados miembros de la Unión Europea y de los Estados parte en el Espacio Económico Europeo. Su ámbito de aplicación se extiende también a determinados familiares de estos ciudadanos —cónyuge o pareja registrada, descendientes menores de veintiún años o a cargo, y ascendientes a cargo— aunque no tengan la nacionalidad de un Estado miembro. El artículo 3 reconoce a todas estas personas el derecho a entrar, salir, circular y residir libremente en España, y a acceder a cualquier actividad por cuenta propia o ajena en las mismas condiciones que los ciudadanos españoles.",
    "La entrada se efectúa con el pasaporte o documento de identidad válido y en vigor, sin necesidad de visado para el ciudadano de la Unión, aunque sus familiares sin esa nacionalidad pueden necesitarlo. Una estancia inferior a tres meses no exige más trámite que la posesión de dicho documento, y no computa a efectos de residencia. Para permanecer más de tres meses es necesario acreditar alguno de los supuestos del artículo 7 —ser trabajador por cuenta propia o ajena, o disponer de recursos suficientes y de un seguro de enfermedad que cubra todos los riesgos, entre otros— y solicitar el correspondiente certificado de registro o, en el caso de los familiares sin nacionalidad de un Estado miembro, la tarjeta de residencia de familiar de ciudadano de la Unión.",
    "Transcurridos cinco años de residencia legal continuada en España, se adquiere el derecho a residir con carácter permanente, sin que a partir de entonces sea necesario acreditar los requisitos de recursos o actividad exigidos para la residencia temporal. El artículo 10 permite además adquirir este derecho antes de los cinco años en determinados supuestos, como el de los trabajadores que se jubilan tras un mínimo de doce meses de actividad y tres años de residencia continuada, o quienes cesan su actividad por incapacidad permanente. El derecho de residencia permanente se pierde por una ausencia de España superior a dos años consecutivos.",
    "Por razones de orden público, seguridad pública o salud pública, el artículo 15 permite impedir la entrada en España, denegar la inscripción registral o la tarjeta de residencia, o acordar la expulsión o devolución. Sin embargo, expulsar a quien ya ha adquirido el derecho de residencia permanente exige que existan motivos graves de orden público o seguridad pública, y la decisión debe fundarse exclusivamente en la conducta personal del interesado —que ha de constituir una amenaza real, actual y suficientemente grave para un interés fundamental de la sociedad—, sin que la mera existencia de condenas penales anteriores baste por sí sola para justificarla. Quienes han residido en España durante los diez años anteriores gozan de una protección reforzada frente a la expulsión, que solo cede ante motivos imperiosos de seguridad pública.",
  ],
};
