import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El Capítulo IV de la Ley 31/1995 regula la organización de los servicios de prevención: conforme al artículo 30.1, el empresario cumple su deber de prevenir los riesgos profesionales designando uno o varios trabajadores para dicha actividad, constituyendo un servicio de prevención propio, o concertándolo con una entidad especializada ajena a la empresa, si bien en empresas de hasta diez trabajadores —o veinticinco, si cuentan con un único centro de trabajo— el propio empresario puede asumir personalmente esta función. El artículo 31.2 define el servicio de prevención como el conjunto de medios humanos y materiales necesarios para realizar las actividades preventivas, asesorando y asistiendo al empresario, a los trabajadores y a sus representantes.",
    "El Capítulo V regula la participación de los trabajadores a través de dos órganos. Los Delegados de Prevención, definidos en el artículo 35.1 como los representantes de los trabajadores con funciones específicas en materia de prevención, se designan por y entre los representantes del personal conforme a una escala legal que va de dos delegados en empresas de 50 a 100 trabajadores hasta ocho en las de más de 4.000. El artículo 36 les atribuye competencias como colaborar con la dirección en la mejora de la acción preventiva, ser consultados con carácter previo a las decisiones empresariales relevantes, y ejercer una labor de vigilancia y control sobre el cumplimiento de la normativa, pudiendo incluso acompañar a los Inspectores de Trabajo en sus visitas. El Comité de Seguridad y Salud, regulado en el artículo 38, es el órgano paritario y colegiado de consulta regular sobre las actuaciones de la empresa en materia de prevención, de constitución obligatoria en empresas o centros de trabajo con 50 o más trabajadores, formado por los Delegados de Prevención y por representantes del empresario en igual número, y que se reúne con periodicidad trimestral. Como medida extrema, el artículo 53 permite al Gobierno acordar la suspensión de las actividades laborales o el cierre del centro de trabajo cuando concurran infracciones de excepcional gravedad en materia de seguridad y salud.",
    "Para el Cuerpo Nacional de Policía, el Real Decreto 2/2006 adapta este esquema de participación a las peculiaridades de la función policial mediante tres órganos propios. Los Delegados de prevención (art. 14) son los representantes de los funcionarios del CNP en materia de prevención de riesgos de la función policial, designados por las organizaciones sindicales con representación en el Consejo de Policía, conforme a una escala proporcional al número de electores en cada Jefatura Superior y en los servicios centrales. La Comisión de seguridad y salud laboral policial (art. 15) es el órgano nacional paritario y colegiado de participación, integrado por representantes sindicales en el mismo número que ostentan en el Consejo de Policía y por representantes de la Administración, encargado de conocer y participar en la elaboración de los planes nacionales de prevención y de analizar los daños producidos en la salud de los funcionarios. Los Comités de seguridad y salud (art. 16), por su parte, son órganos paritarios de ámbito territorial constituidos en cada Jefatura Superior de Policía y en los servicios centrales.",
    "Completando este esquema institucional, el artículo 18 del Real Decreto 2/2006 constituye, en la Subdirección General de Gestión y Recursos Humanos de la Dirección General de la Policía, un Servicio de Prevención propio de ámbito nacional, con funciones de diseño y coordinación de los planes de acción preventiva, evaluación de los riesgos propios de la actividad policial, formación de los funcionarios, prestación de primeros auxilios y planes de emergencia, y vigilancia de la salud. Finalmente, el artículo 19 somete todo este sistema de prevención a un control periódico mediante auditorías y evaluaciones realizadas cada cinco años por la Inspección de Personal y Servicios de Seguridad de la Secretaría de Estado de Seguridad, que puede requerir el asesoramiento del Instituto Nacional de Seguridad e Higiene en el Trabajo, comunicándose con carácter urgente cualquier situación de riesgo grave e inminente que se detecte.",
  ],
};
