import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "El régimen legal de las armas de fuego en España se recoge en el Real Decreto 137/1993, de 29 de enero, por el que se aprueba el Reglamento de Armas, que desarrolla, según su artículo 1.1, lo dispuesto en los artículos 6, 7 y 23 y siguientes de la Ley Orgánica 1/1992, de Protección de la Seguridad Ciudadana. El Reglamento regula los requisitos y condiciones de la fabricación, reparación, circulación, almacenamiento, comercio, adquisición, enajenación, tenencia y utilización de las armas y sus componentes esenciales, con el objeto de salvaguardar la seguridad pública. El artículo 1.4 excluye expresamente de su ámbito de aplicación la adquisición, tenencia y uso de armas por las Fuerzas Armadas, las Fuerzas y Cuerpos de Seguridad y el Centro Nacional de Inteligencia, que se rigen por su normativa especial.",
    "El artículo 2 define los conceptos esenciales de la materia: el arma de fuego es toda arma portátil que tenga cañón y que lance, esté concebida para lanzar o pueda transformarse fácilmente para lanzar un perdigón, una bala o un proyectil por la acción de un combustible propulsor; se considera arma de fuego corta aquella cuyo cañón no exceda de 30 centímetros o cuya longitud total no exceda de 60 centímetros, siendo arma larga cualquier otra. El artículo 3 clasifica las armas reglamentadas en nueve categorías según sus características y peligrosidad: la 1.ª comprende las armas de fuego cortas (pistolas y revólveres); la 2.ª, las armas largas de vigilancia y guardería y las rayadas para caza mayor; la 3.ª, entre otras, las escopetas y armas deportivas de calibre .22; y así sucesivamente hasta la 9.ª categoría, reservada a las armas inutilizadas.",
    "Los artículos 4 y 5 establecen un doble régimen de restricción. El artículo 4.1 prohíbe en todo caso, entre otras, las armas de fabricación ilícita, las armas simuladas bajo la apariencia de otro objeto, los bastones-estoque, los puñales de cualquier clase —entendiendo por tales las armas blancas de hoja menor de 11 centímetros, de dos filos y puntiaguda— y las navajas llamadas automáticas. El artículo 5.1 reserva a funcionarios especialmente habilitados, entre otras armas, las de fuego cortas semiautomáticas de gran capacidad de carga, los cañones recortados, los cargadores de gran capacidad y los silenciadores adaptables a armas de fuego.",
    "El Capítulo V regula el régimen de licencias: conforme al artículo 96.1, nadie puede llevar ni poseer armas de fuego en territorio español sin la correspondiente autorización, y la tenencia de las armas de las categorías 1.ª, 2.ª y 3.ª exige licencia de armas —existiendo distintos tipos según el titular y el uso (A, B, C, D, E y F)—, mientras que las de categoría 4.ª exigen tarjeta de armas. El artículo 97 exige presentar la solicitud ante la Intervención de Armas de la Guardia Civil del domicilio del interesado, acompañada del certificado de antecedentes penales, el documento nacional de identidad y el informe de aptitudes psicofísicas, y el artículo 98 excluye de la posesión y uso de armas a quienes, por sus condiciones psíquicas o físicas, representen un riesgo, considerando indicativa de dicho riesgo una condena previa por delito doloso violento. La licencia de armas B, destinada a las armas cortas de particulares, es competencia de la Dirección General de la Guardia Civil, tiene carácter restrictivo —pues la mera defensa de personas o bienes no justifica por sí sola su concesión—, una validez de cinco años, y exige que el arma se guarde en el domicilio del titular en lugar seguro bajo llave, separada de su munición; conforme al artículo 102.1, estas licencias solo pueden expedirse a españoles y extranjeros residentes en España que sean mayores de edad.",
  ],
};
