import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "Las reglas generales de acentuación gráfica del español dependen de la posición de la sílaba tónica y de la letra en que termina la palabra. Las palabras agudas llevan tilde cuando terminan en vocal, en «n» o en «s» no precedida de otra consonante, como en «café», «camión» o «autobús», pero no en casos como «robots» o «reloj». Las palabras llanas o graves, por el contrario, llevan tilde cuando terminan en consonante distinta de «n» o «s», o en «s» precedida de otra consonante, como en «árbol», «fácil» o «bíceps», mientras que no la llevan si terminan en vocal, «n» o «s» sin consonante previa, como en «casa», «joven» o «crisis». Las palabras esdrújulas y sobresdrújulas, en cambio, llevan siempre tilde sin excepción alguna, con independencia de la letra en que terminen, como ocurre en «música», «rápido» o «cómetelo».",
    "Junto a estas reglas generales, existe la tilde diacrítica, que no responde a la posición del acento sino a una función distintiva entre palabras de idéntica forma pero distinta categoría gramatical o significado: así se distinguen «sí» (afirmación o pronombre reflexivo tónico) de «si» (conjunción condicional), «él» (pronombre personal) de «el» (artículo), o «tú» (pronombre) de «tu» (posesivo). La Ortografía de la lengua española de 2010 estableció además que el adverbio «solo» y los pronombres demostrativos («este», «ese», «aquel» y sus femeninos y plurales) se escriben sin tilde en todos los casos, permitiendo su acentuación excepcional únicamente cuando exista un riesgo real de ambigüedad en un contexto concreto; los pronombres interrogativos y exclamativos («qué», «quién», «cómo», «cuándo», «dónde», «cuánto»), por su parte, llevan siempre tilde, a diferencia de sus homófonos relativos o conjuntivos.",
    "Las reglas relativas al uso de determinadas letras completan el sistema ortográfico: se escribe «b», entre otros casos, ante consonante («obstante», «blanco»), en los verbos terminados en «-bir» —con las excepciones de «hervir», «servir» y «vivir»— y en las desinencias del pretérito imperfecto de indicativo de los verbos de la primera conjugación y del verbo «ir». En cuanto a «g» y «j» ante «e», «i», se escriben con «g» las palabras que contienen el elemento «geo-» o que terminan en «-gia», «-gio» o «-logía», mientras que se escriben con «j» las formas de los verbos terminados en «-jar» y «-jear», así como los sustantivos terminados en «-aje» y «-eje».",
    "Por último, los signos de puntuación cumplen funciones bien diferenciadas: la coma separa los elementos de una enumeración e introduce incisos y vocativos; el punto y coma se emplea para separar los elementos de una enumeración compleja que ya contiene comas internas, o para unir proposiciones relacionadas semánticamente entre sí; y los dos puntos anuncian una enumeración, una explicación, una consecuencia o una cita que desarrolla, resume o cierra la idea expresada previamente. A ello se suma una peculiaridad propia del español frente a otras lenguas: los signos de interrogación y exclamación se escriben tanto al principio como al final del enunciado correspondiente («¿…?», «¡…!»).",
  ],
};
