import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 1/2004, de 28 de diciembre, de Medidas de Protección Integral contra la Violencia de Género, tiene por objeto, según su artículo 1, actuar contra la violencia que, como manifestación de la discriminación y de las relaciones de poder de los hombres sobre las mujeres, se ejerce sobre éstas por parte de quienes sean o hayan sido sus cónyuges o de quienes estén o hayan estado ligados a ellas por relaciones similares de afectividad, aun sin convivencia. Esta violencia comprende todo acto de violencia física y psicológica, incluidas las agresiones a la libertad sexual, las amenazas, las coacciones o la privación arbitraria de libertad, y se extiende también a la violencia ejercida sobre los menores con el objetivo de causar perjuicio a la mujer. De especial relevancia para la actuación policial es el artículo 31, que ordena al Gobierno establecer, en las Fuerzas y Cuerpos de Seguridad del Estado, unidades especializadas en la prevención de la violencia de género y en el control de la ejecución de las medidas judiciales, y que prevé la cooperación de las Policías Locales para asegurar el cumplimiento de dichas medidas, todo ello conforme al Protocolo de Actuación de las Fuerzas y Cuerpos de Seguridad y de Coordinación con los Órganos Judiciales.",
    "La misma Ley regula, en su Capítulo IV, un catálogo de medidas judiciales de protección y seguridad de las víctimas: la orden de protección del artículo 62, que remite al artículo 544 ter de la Ley de Enjuiciamiento Criminal; las medidas de salida del domicilio, prohibición de aproximación y de comunicaciones del artículo 64, que permiten al Juez fijar una distancia mínima infranqueable e incluso autorizar el uso de dispositivos tecnológicos de verificación inmediata del cumplimiento; la suspensión de la patria potestad o custodia de los menores del artículo 65 y del régimen de visitas del artículo 66; y la suspensión del derecho a la tenencia, porte y uso de armas del artículo 67, con obligación de depositarlas. El artículo 68 exige que todas estas medidas restrictivas de derechos se adopten mediante auto motivado que aprecie su proporcionalidad y necesidad, con intervención del Ministerio Fiscal y pleno respeto de los principios de contradicción, audiencia y defensa.",
    "Por su parte, la Ley Orgánica 3/2007, de 22 de marzo, para la Igualdad Efectiva de Mujeres y Hombres, tiene por objeto, conforme a su artículo 1, hacer efectivo el derecho de igualdad de trato y de oportunidades entre mujeres y hombres mediante la eliminación de la discriminación de la mujer en cualquier ámbito de la vida, en desarrollo de los artículos 9.2 y 14 de la Constitución. El artículo 3 define el principio de igualdad de trato como la ausencia de toda discriminación, directa o indirecta, por razón de sexo, y el artículo 6 distingue la discriminación directa —un trato menos favorable por razón de sexo— de la indirecta, que se produce cuando una disposición aparentemente neutra pone a personas de un sexo en desventaja particular sin justificación objetiva legítima. El artículo 7 tipifica además el acoso sexual y el acoso por razón de sexo como comportamientos que atentan contra la dignidad de la persona creando un entorno intimidatorio, degradante u ofensivo, calificándolos en todo caso como discriminatorios.",
    "Finalmente, la Ley 4/2023, de 28 de febrero, para la Igualdad Real y Efectiva de las Personas Trans y para la Garantía de los Derechos de las Personas LGTBI, tiene por finalidad, según su artículo 1, garantizar y promover el derecho a la igualdad real y efectiva de las personas lesbianas, gais, trans, bisexuales e intersexuales y de sus familias, definiendo en su artículo 3 conceptos como persona trans —aquella cuya identidad sexual no se corresponde con el sexo asignado al nacer—, intersexualidad, orientación e identidad sexual, y las distintas formas de LGTBIfobia. La Ley regula, en sus artículos 43 a 47, el procedimiento de rectificación registral del sexo: toda persona de nacionalidad española mayor de dieciséis años puede solicitarla por sí misma ante el Registro Civil, mientras que entre los catorce y los dieciséis años puede hacerlo asistida por sus representantes legales; el artículo 44.3 establece expresamente que este derecho no puede condicionarse en ningún caso a la previa exhibición de informe médico o psicológico ni a la previa modificación de la apariencia o función corporal mediante procedimientos médicos o quirúrgicos, y el artículo 47 permite revertir la rectificación transcurridos seis meses desde su inscripción.",
  ],
};
