import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La prevención de riesgos laborales en seguridad vial no constituye un régimen jurídico autónomo, sino la aplicación específica, al contexto concreto de la actuación policial junto al tráfico rodado, de los principios generales ya estudiados en los temas dedicados a la Ley 31/1995 y a su desarrollo para el Cuerpo Nacional de Policía en el Real Decreto 2/2006. Los principios de la acción preventiva del artículo 15 de la Ley 31/1995 —evitar los riesgos, combatirlos en su origen y anteponer la protección colectiva a la individual— se proyectan sobre esta actividad mediante medidas concretas de evaluación de riesgos, planificación preventiva, formación específica y dotación de equipos de protección adecuados.",
    "Entre los riesgos específicos de la actuación en vía pública destaca, en primer lugar, el riesgo de atropello, derivado de la proximidad inevitable al tráfico rodado durante controles, intervenciones en accidentes o cualquier otra actuación a pie de calzada. A este riesgo principal se suman otros de menor gravedad pero también relevantes: la exposición a condiciones meteorológicas adversas, como el frío, el calor, la lluvia o la escasa visibilidad; la inhalación de gases y partículas contaminantes procedentes del tráfico; la exposición al ruido; y la fatiga o el estrés psicológico derivados de una exposición prolongada a un entorno de riesgo constante.",
    "Frente a estos riesgos, la buena praxis preventiva recomienda diversas medidas de actuación. Las prendas de alta visibilidad, como los chalecos con tejidos reflectantes, aumentan la visibilidad del agente frente a los conductores que se aproximan, especialmente en condiciones de baja luminosidad. La señalización previa del área de actuación, mediante conos, balizas luminosas u otras señales de peligro colocadas con suficiente antelación, permite que los conductores dispongan de tiempo y distancia adecuados para percibir la situación, reducir la velocidad y reaccionar con seguridad. El posicionamiento estratégico del vehículo policial, de forma que actúe como barrera física frente a un posible impacto, contribuye igualmente a reducir el riesgo de atropello del agente que actúa a pie de calzada. Finalmente, cuando resulta operativamente posible, se recomienda rotar o relevar periódicamente a los agentes expuestos a un punto de riesgo continuado, con el fin de limitar el tiempo de exposición individual.",
    "Todas estas medidas se apoyan, además, en una formación preventiva específica en materia de seguridad vial —protocolos de señalización, técnicas de posicionamiento seguro y gestión de situaciones de riesgo en carretera—, en coherencia con el derecho a la formación preventiva reconocido con carácter general en el artículo 19 de la Ley 31/1995 y desarrollado específicamente para el Cuerpo Nacional de Policía en el Real Decreto 2/2006, cerrando así el círculo entre el marco normativo general de la prevención de riesgos laborales y su aplicación práctica a uno de los entornos de mayor exposición al riesgo en el ejercicio cotidiano de la función policial.",
  ],
};
