import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "Aunque en el lenguaje cotidiano suelen emplearse como sinónimos, la filosofía distingue la moral de la ética: la moral es el conjunto de normas, costumbres y valores efectivamente vigentes en una sociedad o época concreta, mientras que la ética constituye la reflexión racional y filosófica sobre esos valores, indagando sus fundamentos y su justificación. Dentro de esta reflexión, la ética aplicada se ocupa de los dilemas morales concretos que surgen en ámbitos específicos de la actividad humana, como la bioética, la ética empresarial, la ética ambiental o la deontología de las distintas profesiones, entendida esta última como el conjunto de principios y normas éticas que orientan la conducta de quienes ejercen una profesión determinada, más allá de sus obligaciones estrictamente legales.",
    "Los códigos deontológicos cumplen una función complementaria respecto de la regulación jurídica de una profesión, al establecer estándares de conducta más exigentes que los estrictamente legales, orientados a la excelencia profesional y al mantenimiento de la confianza social en la institución o colectivo de que se trate; su incumplimiento, a diferencia de la infracción de una norma legal, no siempre lleva aparejada una sanción jurídica directa. En el ámbito de la función pública española, el Estatuto Básico del Empleado Público recoge en su Título III un catálogo de principios éticos y de conducta —objetividad, integridad, neutralidad, responsabilidad, imparcialidad, confidencialidad, dedicación al servicio público y transparencia, entre otros— que deben inspirar la actuación de todo empleado público.",
    "En el ámbito específicamente policial, el Comité de Ministros del Consejo de Europa adoptó en 2001 el Código Europeo de Ética de la Policía, mediante la Recomendación Rec(2001)10, que recoge principios y estándares comunes sobre los objetivos, el funcionamiento y la responsabilidad de la policía en un Estado democrático de derecho. Sin constituir una norma jurídicamente vinculante, el Código subraya principios como el respeto y la protección de los derechos humanos, el sometimiento pleno a la legalidad, la proporcionalidad en el uso de la fuerza, la rendición de cuentas ante mecanismos de control internos y externos, y la actuación imparcial y no discriminatoria hacia toda la ciudadanía.",
    "La relevancia de la ética en el ejercicio de la función policial se explica por la propia naturaleza de esta actividad: implica el ejercicio legítimo de facultades coercitivas del Estado —el uso de la fuerza, la detención de personas, la limitación de derechos y libertades—, lo que exige a quienes la desempeñan un plus de responsabilidad ética que va más allá del mero cumplimiento formal de la legalidad. Este exceso de exigencia ética, articulado tanto en instrumentos internacionales como en el propio ordenamiento interno, tiene como finalidad última preservar la confianza social en la institución policial, condición imprescindible para el correcto ejercicio de sus funciones en una sociedad democrática.",
  ],
};
