import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La protección de datos de carácter personal se rige en España por el Reglamento (UE) 2016/679, general de protección de datos (RGPD), de aplicación directa desde el 25 de mayo de 2018, y por la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales (LOPDGDD), que adapta el ordenamiento español al Reglamento y deroga la anterior Ley Orgánica 15/1999. De forma complementaria, la Ley Orgánica 7/2021, de 26 de mayo, traspone la Directiva (UE) 2016/680 y establece un régimen especial para el tratamiento de datos personales por las autoridades competentes, entre ellas las Fuerzas y Cuerpos de Seguridad, cuando actúan con fines de prevención, detección, investigación y enjuiciamiento de infracciones penales, ejecución de sanciones penales, o protección y prevención frente a amenazas para la seguridad pública.",
    "El RGPD define el dato personal como toda información sobre una persona física identificada o identificable, y somete su tratamiento a un conjunto de principios recogidos en su artículo 5: licitud, lealtad y transparencia; limitación de la finalidad; minimización de datos; exactitud; limitación del plazo de conservación; integridad y confidencialidad; y responsabilidad proactiva del responsable del tratamiento. Determinadas categorías de datos, calificadas como especiales por el artículo 9 (origen étnico o racial, opiniones políticas, convicciones religiosas, afiliación sindical, datos genéticos, biométricos, de salud o relativos a la vida u orientación sexual), están sujetas a garantías reforzadas por su especial sensibilidad.",
    "Frente al responsable del tratamiento, las personas disponen de un conjunto de derechos regulados en los artículos 15 a 22 del RGPD: el derecho de acceso a sus datos, el derecho de rectificación de los datos inexactos, el derecho de supresión o \"derecho al olvido\", el derecho a la limitación del tratamiento, el derecho a la portabilidad de los datos y el derecho de oposición. En España, la Agencia Española de Protección de Datos (AEPD) es la autoridad de control independiente encargada de velar por el cumplimiento de esta normativa, mientras que el Delegado de Protección de Datos, de designación obligatoria en las Administraciones Públicas entre otros supuestos, informa, asesora y supervisa el cumplimiento normativo dentro de cada organización.",
    "El incumplimiento de la normativa puede dar lugar a sanciones administrativas: el artículo 83 del RGPD prevé multas de hasta 10.000.000 de euros o el 2% de la facturación anual para determinadas infracciones, y de hasta 20.000.000 de euros o el 4% de la facturación anual para las más graves, aplicándose en el caso de empresas la cifra que resulte mayor. Además, el responsable del tratamiento debe notificar a la autoridad de control cualquier violación de la seguridad de los datos personales en el plazo máximo de setenta y dos horas desde que tenga constancia de ella, salvo que sea improbable que dicha violación suponga un riesgo para los derechos y libertades de los afectados.",
  ],
};
