import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 8/2011, de 28 de abril, establece las estrategias y estructuras que permiten dirigir y coordinar a las Administraciones Públicas en materia de protección de infraestructuras críticas frente a atentados terroristas u otras amenazas. Su artículo 2 define los conceptos clave: el servicio esencial, necesario para las funciones sociales básicas, la salud, la seguridad y el bienestar de los ciudadanos o el funcionamiento de las Instituciones del Estado; la infraestructura estratégica, sobre la que descansa el funcionamiento de esos servicios; y la infraestructura crítica, aquella infraestructura estratégica cuyo funcionamiento es indispensable y no admite soluciones alternativas, de modo que su perturbación o destrucción tendría un grave impacto sobre los servicios esenciales. Quedan fuera del ámbito de la ley las infraestructuras dependientes del Ministerio de Defensa y de las Fuerzas y Cuerpos de Seguridad, que se rigen por su propia normativa.",
    "El Ministerio del Interior, a través de la Secretaría de Estado de Seguridad, es responsable del Catálogo Nacional de Infraestructuras Estratégicas, que recoge la información sobre estas infraestructuras, incluidas las clasificadas como críticas. Para el desarrollo operativo de esta función se crea el Centro Nacional para la Protección de las Infraestructuras Críticas (CNPIC), órgano ministerial encargado del impulso, la coordinación y la supervisión de las actividades de protección, que realiza las altas, bajas y modificaciones del Catálogo. El Sistema de Protección de Infraestructuras Críticas se completa con la Comisión Nacional para la Protección de las Infraestructuras Críticas, que aprueba los Planes Estratégicos Sectoriales y designa a los operadores críticos, y el Grupo de Trabajo Interdepartamental, que elabora dichos planes y propone la designación de esos operadores.",
    "Los operadores críticos —las entidades responsables del funcionamiento de una infraestructura designada como crítica— asumen obligaciones específicas: elaborar el Plan de Seguridad del Operador y un Plan de Protección Específico por cada infraestructura crítica, designar un Responsable de Seguridad y Enlace con la Administración (que debe contar con la habilitación de Director de Seguridad de la normativa de seguridad privada, o equivalente) y un Delegado de Seguridad por cada infraestructura, y facilitar las inspecciones de las autoridades competentes. Junto a estos planes elaborados por los operadores, la ley prevé el Plan Nacional de Protección de las Infraestructuras Críticas y los Planes de Apoyo Operativo, estos últimos a cargo del cuerpo policial competente en cada demarcación.",
    "En materia de ciberseguridad, la Estrategia Nacional de Ciberseguridad de 2019 fija como objetivo general que España garantice el uso seguro y fiable del ciberespacio, protegiendo los derechos y libertades de los ciudadanos y promoviendo el progreso socioeconómico. De ese objetivo general se derivan cinco objetivos específicos: la seguridad y resiliencia de las redes y sistemas del sector público y de los servicios esenciales; el uso seguro del ciberespacio frente a su uso ilícito o malicioso, distinguiendo el ciberespacio como objetivo directo de los delitos, como medio para su comisión y como medio de investigación; la protección del ecosistema empresarial, social y de los ciudadanos, como responsabilidad compartida entre el Estado y los actores privados; el fomento de la cultura de ciberseguridad y de las capacidades humanas y tecnológicas; y la proyección de la seguridad del ciberespacio en el ámbito internacional, en cooperación con la Unión Europea, la OTAN y Naciones Unidas, entre otros foros.",
  ],
};
