import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "Las redes informáticas se clasifican, según su extensión geográfica, en redes de área local o LAN, limitadas a un edificio o campus; redes de área metropolitana o MAN, que cubren el ámbito de una ciudad; y redes de área extensa o WAN, que abarcan grandes distancias geográficas, siendo Internet el ejemplo más representativo de esta última categoría. Atendiendo al medio de transmisión empleado, se distinguen las redes cableadas, que transmiten la información a través de un medio físico como el cable de cobre o la fibra óptica, de las redes inalámbricas, como las basadas en el estándar Wi-Fi, que transmiten los datos mediante ondas de radiofrecuencia sin necesidad de una conexión física entre los dispositivos y el punto de acceso.",
    "El funcionamiento de Internet se apoya en el modelo TCP/IP, el conjunto de protocolos de comunicación organizado en cuatro capas —aplicación, transporte, internet y acceso a la red— que permite la interconexión y el intercambio de datos entre equipos de distintos fabricantes y sistemas operativos. Dentro de este modelo, cada dispositivo conectado a una red que utiliza el protocolo de Internet recibe una dirección IP, un identificador numérico único empleado para su localización, ya sea en el formato tradicional IPv4, de 32 bits, o en el más reciente IPv6, de 128 bits, diseñado para ampliar el espacio de direcciones disponible ante el crecimiento del número de dispositivos conectados. Para facilitar la navegación, el sistema de nombres de dominio o DNS traduce los nombres legibles por las personas, como «www.ejemplo.es», en las direcciones IP numéricas que realmente identifican a los servidores dentro de la red.",
    "La interconexión física y lógica de los equipos se articula mediante dispositivos como el router o encaminador, que interconecta redes distintas —por ejemplo, la red local doméstica con la red del proveedor de acceso a Internet— y dirige el tráfico entre ellas en función de las direcciones IP de destino, y el switch o conmutador, que interconecta los dispositivos dentro de una misma red local dirigiendo el tráfico entre los distintos puertos conectados a él según las direcciones físicas o MAC de los equipos.",
    "En materia de seguridad de redes, el cortafuegos o firewall es el sistema, implementado en hardware, software o ambos, que controla el tráfico de red entrante y saliente conforme a un conjunto de reglas de seguridad predefinidas, permitiendo o bloqueando conexiones según criterios como su origen, destino o tipo de tráfico. Junto a él, la tecnología de red privada virtual o VPN establece una conexión cifrada y segura a través de una red pública como Internet, de modo que el tráfico de datos del dispositivo circula como si este estuviera conectado directamente a una red privada, protegiendo así la confidencialidad de las comunicaciones frente a terceros no autorizados.",
  ],
};
