import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley 5/2014, de 4 de abril, de Seguridad Privada, regula la prestación por personas físicas o jurídicas privadas de actividades y servicios de seguridad privada, que la propia ley califica de complementarios y subordinados respecto de la seguridad pública. Su artículo 2.1 define la seguridad privada como el conjunto de actividades, servicios, funciones y medidas de seguridad prestadas por empresas de seguridad, despachos de detectives privados y personal habilitado, con la finalidad de proteger a las personas y sus bienes. Quedan fuera de su ámbito las actuaciones de autoprotección, es decir, las cautelas que los propios interesados adoptan directamente para sí mismos sin contraprestación ni prestación de un servicio a terceros.",
    "El personal de seguridad privada, regulado en el Título III de la ley, comprende a los vigilantes de seguridad (y su especialidad de vigilantes de explosivos), los escoltas privados, los guardas rurales (y sus especialidades de guardas de caza y guardapescas marítimos), los jefes de seguridad, los directores de seguridad y los detectives privados. Todos ellos precisan una habilitación previa del Ministerio del Interior, que en la práctica concede la Dirección General de la Policía, salvo la de los guardas rurales, que corresponde a la Dirección General de la Guardia Civil. Los requisitos generales para obtenerla incluyen la nacionalidad de un Estado de la Unión Europea o del Espacio Económico Europeo, la mayoría de edad, la capacidad física y psicológica adecuada, la formación exigida y carecer de antecedentes penales por delitos dolosos.",
    "Cada categoría profesional tiene funciones delimitadas por la ley. Los vigilantes de seguridad pueden efectuar controles de identidad y de objetos, y detener a quien sorprendan cometiendo un delito, poniéndolo inmediatamente a disposición de las Fuerzas y Cuerpos de Seguridad sin poder interrogarlo. Los escoltas privados solo pueden impedir o restringir la libre circulación de las personas cuando resulte imprescindible por una agresión o un intento manifiesto de agresión a la persona protegida o a ellos mismos, debiendo actuar con el mismo límite frente al detenido. Los detectives privados, por su parte, tienen expresamente prohibido investigar delitos perseguibles de oficio: si conocen hechos de esta naturaleza, deben denunciarlos de inmediato ante la autoridad competente.",
    "El régimen sancionador, recogido en el Título VI de la ley, clasifica las infracciones en leves, graves y muy graves, con plazos de prescripción de seis meses, un año y dos años respectivamente. Pueden ser sancionadas las empresas de seguridad y los despachos de detectives, el personal de seguridad privada, y los usuarios y centros de formación. Las multas más elevadas corresponden a las empresas por infracciones muy graves, de entre 30.001 y 600.000 euros, pudiendo acompañarse de la extinción de la autorización; para el personal, la multa por infracciones muy graves oscila entre 6.001 y 30.000 euros, con posible extinción de la habilitación. La potestad sancionadora se reparte entre el Ministro del Interior, el Secretario de Estado de Seguridad, el Director General de la Policía y los Delegados y Subdelegados del Gobierno, según la gravedad de la infracción.",
  ],
};
