import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La conducción de un vehículo prioritario en servicio urgente se rige por un principio que debe prevalecer sobre cualquier otra consideración: la seguridad propia, de los ocupantes y de terceros usuarios de la vía. Aunque el Reglamento General de Circulación reconoce a estos vehículos prioridad de paso y determinadas exenciones normativas, un accidente durante el desplazamiento no solo impide completar el servicio para el que se circula, sino que añade nuevas víctimas y agrava la situación que se pretendía atender. Por ello, la buena praxis policial insiste en que la rapidez nunca debe obtenerse a costa de asumir riesgos innecesarios.",
    "Una de las técnicas fundamentales es la conducción anticipativa, que consiste en explorar de forma constante el entorno —cruces, pasos de peatones, colegios, vehículos que puedan invadir el carril— para detectar con antelación posibles conflictos y disponer así de más tiempo y opciones de reacción. Resulta especialmente importante no presuponer que los demás conductores han percibido la señal acústica o luminosa del vehículo prioritario, ya que factores como el aislamiento acústico de otros vehículos, la música o la simple distracción pueden impedir su percepción; por ello conviene reducir la velocidad de forma preventiva al aproximarse a intersecciones, semáforos en rojo o pasos de peatones, comprobando visualmente que el resto de usuarios han detenido su marcha antes de proseguir.",
    "La gestión de la velocidad exige tener presente que la distancia de frenado crece de forma no lineal a medida que aumenta la velocidad, de modo que la exención de los límites genéricos reconocida al vehículo prioritario debe compensarse con una mayor distancia de seguridad y un margen de reacción más amplio. En las curvas, la técnica recomendada consiste en reducir la velocidad antes de entrar en ellas —nunca frenar bruscamente en su interior, donde puede desestabilizarse el vehículo—, aprovechar el ancho disponible de la calzada y acelerar de forma progresiva a la salida.",
    "Finalmente, el factor humano resulta determinante en este tipo de conducción: el estrés y la tensión emocional inherentes a un servicio urgente pueden estrechar el campo de atención del conductor y ralentizar su tiempo de reacción. Técnicas como el control de la respiración, la verbalización de los riesgos detectados en voz alta y el reparto de funciones con el copiloto —quien puede encargarse de la radio, la navegación y la vigilancia de puntos ciegos mientras el conductor se concentra en el control del vehículo— contribuyen a mantener la seguridad durante la intervención. Concluido el servicio, es recomendable restablecer cuanto antes un patrón de conducción normal, siendo consciente de que la tensión acumulada puede persistir y seguir afectando a la atención durante el trayecto de regreso.",
  ],
};
