import type { Resumen } from "@/lib/temaContenido";

export const resumen: Resumen = {
  parrafos: [
    "La Ley Orgánica 2/1979, de 3 de octubre, desarrolla el Tribunal Constitucional previsto en el Título IX de la Constitución. Lo define como el intérprete supremo de la Constitución, independiente de los demás órganos del Estado y sometido únicamente a la Constitución y a su propia Ley Orgánica. Está compuesto por doce Magistrados nombrados por el Rey a propuesta del Congreso (cuatro, por mayoría de tres quintos), el Senado (cuatro, con idéntica mayoría), el Gobierno (dos) y el Consejo General del Poder Judicial (dos), con un mandato de nueve años renovable por terceras partes cada tres. El Tribunal actúa en Pleno, en dos Salas de seis Magistrados y en Secciones.",
    "Sus competencias principales son cuatro: el control de constitucionalidad de las leyes (mediante el recurso y la cuestión de inconstitucionalidad), la protección de los derechos fundamentales frente a actuaciones de los poderes públicos (recurso de amparo), la resolución de conflictos de competencia entre el Estado y las Comunidades Autónomas o entre órganos constitucionales, y el control previo de los Estatutos de Autonomía y sus reformas.",
    "El recurso de inconstitucionalidad puede interponerlo el Presidente del Gobierno, el Defensor del Pueblo, cincuenta Diputados o Senadores, y los órganos ejecutivos o legislativos de las Comunidades Autónomas, dentro de los tres meses siguientes a la publicación de la norma (nueve meses en determinados supuestos de negociación previa entre el Estado y una Comunidad Autónoma). El recurso de amparo, por su parte, protege los derechos y libertades reconocidos en los artículos 14 a 29 de la Constitución (y la objeción de conciencia del art. 30), exige haber agotado previamente la vía judicial ordinaria, y solo se admite a trámite si el asunto reviste 'especial trascendencia constitucional', un filtro introducido para evitar que el Tribunal actúe como una tercera instancia judicial ordinaria.",
    "Las sentencias del Tribunal Constitucional tienen valor de cosa juzgada, vinculan a todos los poderes públicos y no admiten recurso alguno (solo cabe solicitar aclaración en dos días). Cuando declaran la inconstitucionalidad de una norma, esta queda anulada con efectos generales desde la publicación de la sentencia en el BOE.",
  ],
};
