import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "ebep-01",
    enunciado: "¿Qué texto legal aprueba el Estatuto Básico del Empleado Público (EBEP)?",
    opciones: [
      "La Ley 7/2007, de 12 de abril",
      "El Real Decreto Legislativo 5/2015, de 30 de octubre",
      "La Ley 40/2015, de 1 de octubre",
      "El Real Decreto 364/1995, de 10 de marzo",
    ],
    correcta: 1,
    explicacion: "El art. 1 se enmarca en el Real Decreto Legislativo 5/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley del Estatuto Básico del Empleado Público.",
  },
  {
    id: "ebep-02",
    enunciado: "Según el artículo 8, ¿en cuántas clases se clasifican los empleados públicos?",
    opciones: [
      "En dos: funcionarios y laborales",
      "En tres: funcionarios de carrera, interinos y laborales",
      "En cuatro: funcionarios de carrera, funcionarios interinos, personal laboral y personal eventual",
      "En cinco categorías según su grupo de titulación",
    ],
    correcta: 2,
    explicacion: "El art. 8.2 distingue funcionarios de carrera, funcionarios interinos, personal laboral (fijo, indefinido o temporal) y personal eventual.",
  },
  {
    id: "ebep-03",
    enunciado: "¿Cómo define el artículo 9 a los funcionarios de carrera?",
    opciones: [
      "Quienes prestan servicios de carácter temporal por necesidad y urgencia",
      "Quienes, por nombramiento legal, están vinculados a una Administración Pública por una relación estatutaria regulada por el Derecho Administrativo para servicios profesionales retribuidos de carácter permanente",
      "Quienes prestan servicios mediante contrato laboral por tiempo indefinido",
      "Quienes desempeñan funciones de confianza o asesoramiento especial",
    ],
    correcta: 1,
    explicacion: "El art. 9.1 recoge exactamente esta definición de funcionario de carrera.",
  },
  {
    id: "ebep-04",
    enunciado: "Según el artículo 10, ¿cuál es el plazo máximo, con carácter general, para la ocupación de una plaza vacante por un funcionario interino?",
    opciones: ["Un año", "Dos años", "Tres años", "Cinco años"],
    correcta: 2,
    explicacion: "El art. 10.1.a) y 10.4 fijan en tres años el plazo máximo, transcurrido el cual la vacante solo podrá ser cubierta por personal funcionario de carrera, salvo proceso selectivo desierto.",
  },
  {
    id: "ebep-05",
    enunciado: "¿Qué edad mínima exige el artículo 56 para participar en los procesos selectivos de acceso al empleo público?",
    opciones: ["Dieciséis años", "Dieciocho años", "Diecisiete años", "Veintiún años"],
    correcta: 0,
    explicacion: "El art. 56.1.c) exige tener cumplidos dieciséis años y no exceder, en su caso, de la edad máxima de jubilación forzosa.",
  },
  {
    id: "ebep-06",
    enunciado: "¿Qué porcentaje mínimo de las vacantes de las ofertas de empleo público debe reservarse para personas con discapacidad según el artículo 59?",
    opciones: ["El dos por ciento", "El cinco por ciento", "El siete por ciento", "El diez por ciento"],
    correcta: 2,
    explicacion: "El art. 59.1 reserva un cupo no inferior al siete por ciento de las vacantes, del que al menos el dos por ciento debe destinarse a personas con discapacidad intelectual.",
  },
  {
    id: "ebep-07",
    enunciado: "Según el artículo 61, ¿cuáles son los sistemas selectivos ordinarios para el acceso a la condición de funcionario de carrera?",
    opciones: [
      "Únicamente el concurso de méritos",
      "La oposición y el concurso-oposición",
      "La libre designación",
      "El nombramiento directo por la Administración",
    ],
    correcta: 1,
    explicacion: "El art. 61.6 establece que los sistemas selectivos de funcionarios de carrera serán los de oposición y concurso-oposición; el concurso puro solo procede excepcionalmente y por ley.",
  },
  {
    id: "ebep-08",
    enunciado: "¿Cuáles son los requisitos que, según el artículo 62, deben cumplirse sucesivamente para adquirir la condición de funcionario de carrera?",
    opciones: [
      "Superación del proceso selectivo, nombramiento, acatamiento de la Constitución y toma de posesión",
      "Nombramiento, jura de bandera y superación de un periodo de prácticas",
      "Superación del proceso selectivo y publicación en el Boletín Oficial únicamente",
      "Toma de posesión y superación de un curso selectivo posterior",
    ],
    correcta: 0,
    explicacion: "El art. 62.1 enumera: a) superación del proceso selectivo, b) nombramiento publicado en el Diario Oficial, c) acto de acatamiento de la Constitución y d) toma de posesión.",
  },
  {
    id: "ebep-09",
    enunciado: "¿Cuál de las siguientes NO es una causa de pérdida de la condición de funcionario de carrera según el artículo 63?",
    opciones: [
      "La renuncia a la condición de funcionario",
      "La excedencia voluntaria por interés particular",
      "La jubilación total del funcionario",
      "La sanción disciplinaria firme de separación del servicio",
    ],
    correcta: 1,
    explicacion: "El art. 63 recoge la renuncia, la pérdida de nacionalidad, la jubilación total, la separación del servicio firme y la inhabilitación firme; la excedencia voluntaria no extingue la relación de servicio, solo la suspende.",
  },
  {
    id: "ebep-10",
    enunciado: "¿A qué edad se declara de oficio, con carácter general, la jubilación forzosa según el artículo 67?",
    opciones: ["A los sesenta años", "A los sesenta y tres años", "A los sesenta y cinco años", "A los setenta años"],
    correcta: 2,
    explicacion: "El art. 67.3 fija la jubilación forzosa de oficio al cumplir el funcionario los sesenta y cinco años, sin perjuicio de poder solicitar prolongación hasta los setenta.",
  },
  {
    id: "ebep-11",
    enunciado: "Según el artículo 76, ¿qué titulación se exige para el acceso al Subgrupo C1?",
    opciones: [
      "Título de Graduado en Educación Secundaria Obligatoria",
      "Título de Bachiller o Técnico",
      "Título de Técnico Superior",
      "Título universitario de Grado",
    ],
    correcta: 1,
    explicacion: "El art. 76 exige para el Subgrupo C1 el título de Bachiller o Técnico, mientras que el C2 exige el título de Graduado en Educación Secundaria Obligatoria.",
  },
  {
    id: "ebep-12",
    enunciado: "¿Cuáles son, según el artículo 85, las situaciones administrativas en que pueden hallarse los funcionarios de carrera?",
    opciones: [
      "Servicio activo, servicios especiales, servicio en otras Administraciones Públicas, excedencia y suspensión de funciones",
      "Activo, pasivo y jubilado",
      "En plantilla, en prácticas y en comisión de servicios",
      "Titular, interino y sustituto",
    ],
    correcta: 0,
    explicacion: "El art. 85.1 enumera estas cinco situaciones administrativas básicas de los funcionarios de carrera.",
  },
  {
    id: "ebep-13",
    enunciado: "¿Cuántos años de servicios efectivos se exigen, con carácter general, para solicitar la excedencia voluntaria por interés particular según el artículo 89?",
    opciones: ["Un año", "Tres años", "Cinco años", "Diez años"],
    correcta: 2,
    explicacion: "El art. 89.2 exige haber prestado servicios efectivos durante un periodo mínimo de cinco años inmediatamente anteriores, salvo que las leyes de Función Pública reduzcan ese periodo.",
  },
  {
    id: "ebep-14",
    enunciado: "Según el artículo 90, ¿cuándo determina la suspensión de funciones la pérdida del puesto de trabajo?",
    opciones: [
      "Cuando exceda de tres meses",
      "Cuando exceda de seis meses",
      "Cuando exceda de un año",
      "En todo caso, desde el primer día",
    ],
    correcta: 1,
    explicacion: "El art. 90.1 establece que la suspensión determinará la pérdida del puesto de trabajo cuando exceda de seis meses.",
  },
  {
    id: "ebep-15",
    enunciado: "¿Qué procedimientos son, según el artículo 78, los procedimientos ordinarios de provisión de puestos de trabajo del personal funcionario de carrera?",
    opciones: [
      "El concurso y la libre designación con convocatoria pública",
      "La oposición y el concurso-oposición",
      "El sorteo entre los candidatos con mayor antigüedad",
      "La designación directa por el superior jerárquico",
    ],
    correcta: 0,
    explicacion: "El art. 78.2 establece que la provisión de puestos de trabajo se llevará a cabo por los procedimientos de concurso y de libre designación con convocatoria pública.",
  },
];
