import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "ebep-01",
    enunciado: "¿Qué texto legal aprueba el Estatuto Básico del Empleado Público (EBEP)?",
    opciones: [
      "La Ley 7/2007, de 12 de abril",
      "El Real Decreto Legislativo 5/2015, de 30 de octubre",
      "La Ley 40/2015, de 1 de octubre",
      "El Real Decreto 364/1995, de 10 de marzo",
    ],
    correcta: 1,
    explicacion: "El art. 1 se enmarca en el Real Decreto Legislativo 5/2015, de 30 de octubre, por el que se aprueba el texto refundido de la Ley del Estatuto Básico del Empleado Público.",
  },
  {
    id: "ebep-02",
    enunciado: "Según el artículo 8, ¿en cuántas clases se clasifican los empleados públicos?",
    opciones: [
      "En dos: funcionarios y laborales",
      "En tres: funcionarios de carrera, interinos y laborales",
      "En cuatro: funcionarios de carrera, funcionarios interinos, personal laboral y personal eventual",
      "En cinco categorías según su grupo de titulación",
    ],
    correcta: 2,
    explicacion: "El art. 8.2 distingue funcionarios de carrera, funcionarios interinos, personal laboral (fijo, indefinido o temporal) y personal eventual.",
  },
  {
    id: "ebep-03",
    enunciado: "¿Cómo define el artículo 9 a los funcionarios de carrera?",
    opciones: [
      "Quienes prestan servicios de carácter temporal por necesidad y urgencia",
      "Quienes, por nombramiento legal, están vinculados a una Administración Pública por una relación estatutaria regulada por el Derecho Administrativo para servicios profesionales retribuidos de carácter permanente",
      "Quienes prestan servicios mediante contrato laboral por tiempo indefinido",
      "Quienes desempeñan funciones de confianza o asesoramiento especial",
    ],
    correcta: 1,
    explicacion: "El art. 9.1 recoge exactamente esta definición de funcionario de carrera.",
  },
  {
    id: "ebep-04",
    enunciado: "Según el artículo 10, ¿cuál es el plazo máximo, con carácter general, para la ocupación de una plaza vacante por un funcionario interino?",
    opciones: ["Un año", "Dos años", "Tres años", "Cinco años"],
    correcta: 2,
    explicacion: "El art. 10.1.a) y 10.4 fijan en tres años el plazo máximo, transcurrido el cual la vacante solo podrá ser cubierta por personal funcionario de carrera, salvo proceso selectivo desierto.",
  },
  {
    id: "ebep-05",
    enunciado: "¿Qué edad mínima exige el artículo 56 para participar en los procesos selectivos de acceso al empleo público?",
    opciones: ["Dieciséis años", "Dieciocho años", "Diecisiete años", "Veintiún años"],
    correcta: 0,
    explicacion: "El art. 56.1.c) exige tener cumplidos dieciséis años y no exceder, en su caso, de la edad máxima de jubilación forzosa.",
  },
  {
    id: "ebep-06",
    enunciado: "¿Qué porcentaje mínimo de las vacantes de las ofertas de empleo público debe reservarse para personas con discapacidad según el artículo 59?",
    opciones: ["El dos por ciento", "El cinco por ciento", "El siete por ciento", "El diez por ciento"],
    correcta: 2,
    explicacion: "El art. 59.1 reserva un cupo no inferior al siete por ciento de las vacantes, del que al menos el dos por ciento debe destinarse a personas con discapacidad intelectual.",
  },
  {
    id: "ebep-07",
    enunciado: "Según el artículo 61, ¿cuáles son los sistemas selectivos ordinarios para el acceso a la condición de funcionario de carrera?",
    opciones: [
      "Únicamente el concurso de méritos",
      "La oposición y el concurso-oposición",
      "La libre designación",
      "El nombramiento directo por la Administración",
    ],
    correcta: 1,
    explicacion: "El art. 61.6 establece que los sistemas selectivos de funcionarios de carrera serán los de oposición y concurso-oposición; el concurso puro solo procede excepcionalmente y por ley.",
  },
  {
    id: "ebep-08",
    enunciado: "¿Cuáles son los requisitos que, según el artículo 62, deben cumplirse sucesivamente para adquirir la condición de funcionario de carrera?",
    opciones: [
      "Superación del proceso selectivo, nombramiento, acatamiento de la Constitución y toma de posesión",
      "Nombramiento, jura de bandera y superación de un periodo de prácticas",
      "Superación del proceso selectivo y publicación en el Boletín Oficial únicamente",
      "Toma de posesión y superación de un curso selectivo posterior",
    ],
    correcta: 0,
    explicacion: "El art. 62.1 enumera: a) superación del proceso selectivo, b) nombramiento publicado en el Diario Oficial, c) acto de acatamiento de la Constitución y d) toma de posesión.",
  },
  {
    id: "ebep-09",
    enunciado: "¿Cuál de las siguientes NO es una causa de pérdida de la condición de funcionario de carrera según el artículo 63?",
    opciones: [
      "La renuncia a la condición de funcionario",
      "La excedencia voluntaria por interés particular",
      "La jubilación total del funcionario",
      "La sanción disciplinaria firme de separación del servicio",
    ],
    correcta: 1,
    explicacion: "El art. 63 recoge la renuncia, la pérdida de nacionalidad, la jubilación total, la separación del servicio firme y la inhabilitación firme; la excedencia voluntaria no extingue la relación de servicio, solo la suspende.",
  },
  {
    id: "ebep-10",
    enunciado: "¿A qué edad se declara de oficio, con carácter general, la jubilación forzosa según el artículo 67?",
    opciones: ["A los sesenta años", "A los sesenta y tres años", "A los sesenta y cinco años", "A los setenta años"],
    correcta: 2,
    explicacion: "El art. 67.3 fija la jubilación forzosa de oficio al cumplir el funcionario los sesenta y cinco años, sin perjuicio de poder solicitar prolongación hasta los setenta.",
  },
  {
    id: "ebep-11",
    enunciado: "Según el artículo 76, ¿qué titulación se exige para el acceso al Subgrupo C1?",
    opciones: [
      "Título de Graduado en Educación Secundaria Obligatoria",
      "Título de Bachiller o Técnico",
      "Título de Técnico Superior",
      "Título universitario de Grado",
    ],
    correcta: 1,
    explicacion: "El art. 76 exige para el Subgrupo C1 el título de Bachiller o Técnico, mientras que el C2 exige el título de Graduado en Educación Secundaria Obligatoria.",
  },
  {
    id: "ebep-12",
    enunciado: "¿Cuáles son, según el artículo 85, las situaciones administrativas en que pueden hallarse los funcionarios de carrera?",
    opciones: [
      "Servicio activo, servicios especiales, servicio en otras Administraciones Públicas, excedencia y suspensión de funciones",
      "Activo, pasivo y jubilado",
      "En plantilla, en prácticas y en comisión de servicios",
      "Titular, interino y sustituto",
    ],
    correcta: 0,
    explicacion: "El art. 85.1 enumera estas cinco situaciones administrativas básicas de los funcionarios de carrera.",
  },
  {
    id: "ebep-13",
    enunciado: "¿Cuántos años de servicios efectivos se exigen, con carácter general, para solicitar la excedencia voluntaria por interés particular según el artículo 89?",
    opciones: ["Un año", "Tres años", "Cinco años", "Diez años"],
    correcta: 2,
    explicacion: "El art. 89.2 exige haber prestado servicios efectivos durante un periodo mínimo de cinco años inmediatamente anteriores, salvo que las leyes de Función Pública reduzcan ese periodo.",
  },
  {
    id: "ebep-14",
    enunciado: "Según el artículo 90, ¿cuándo determina la suspensión de funciones la pérdida del puesto de trabajo?",
    opciones: [
      "Cuando exceda de tres meses",
      "Cuando exceda de seis meses",
      "Cuando exceda de un año",
      "En todo caso, desde el primer día",
    ],
    correcta: 1,
    explicacion: "El art. 90.1 establece que la suspensión determinará la pérdida del puesto de trabajo cuando exceda de seis meses.",
  },
  {
    id: "ebep-15",
    enunciado: "¿Qué procedimientos son, según el artículo 78, los procedimientos ordinarios de provisión de puestos de trabajo del personal funcionario de carrera?",
    opciones: [
      "El concurso y la libre designación con convocatoria pública",
      "La oposición y el concurso-oposición",
      "El sorteo entre los candidatos con mayor antigüedad",
      "La designación directa por el superior jerárquico",
    ],
    correcta: 0,
    explicacion: "El art. 78.2 establece que la provisión de puestos de trabajo se llevará a cabo por los procedimientos de concurso y de libre designación con convocatoria pública.",
  },
  {
    id: "ebep-16",
    enunciado: "Según el artículo 11 del EBEP, ¿qué es el personal laboral?",
    opciones: [
      "El que en virtud de contrato de trabajo formalizado por escrito, en cualquiera de las modalidades de contratación de personal previstas en la legislación laboral, presta servicios retribuidos por las Administraciones Públicas",
      "El que ocupa un puesto de confianza o asesoramiento especial, no reservado a funcionarios de carrera",
      "El que, por razones de urgencia, ocupa plazas de funcionarios de carrera de forma temporal",
      "El que desempeña funciones exclusivamente honoríficas, sin retribución",
    ],
    correcta: 0,
    explicacion: "El art. 11.1 del EBEP define al personal laboral como aquel que, en virtud de contrato de trabajo formalizado por escrito en cualquiera de las modalidades de contratación previstas en la legislación laboral, presta servicios retribuidos por las Administraciones Públicas, pudiendo ser fijo, por tiempo indefinido o temporal.",
  },
  {
    id: "ebep-17",
    enunciado: "Según el artículo 12 del EBEP, ¿qué es el personal eventual?",
    opciones: [
      "El que, en virtud de nombramiento y con carácter no permanente, solo realiza funciones expresamente calificadas como de confianza o asesoramiento especial, siendo retribuido con cargo a los créditos presupuestarios consignados para este fin",
      "El que ha superado un proceso selectivo y ha sido nombrado funcionario de carrera",
      "El que ocupa interinamente una plaza vacante hasta su cobertura definitiva",
      "El personal directivo profesional de las Administraciones Públicas",
    ],
    correcta: 0,
    explicacion: "El art. 12.1 del EBEP define al personal eventual como aquel que, en virtud de nombramiento y con carácter no permanente, solo realiza funciones expresamente calificadas como de confianza o asesoramiento especial, siendo retribuido con cargo a los créditos presupuestarios consignados para este fin, y cesando automáticamente cuando se produzca el cese de la autoridad a la que preste su función de confianza o asesoramiento.",
  },
  {
    id: "ebep-18",
    enunciado: "Según el artículo 13 del EBEP, ¿qué es el personal directivo profesional?",
    opciones: [
      "El que desarrolla funciones directivas profesionales en las Administraciones Públicas, definidas como tales en las normas específicas de cada Administración, cuya designación atenderá a principios de mérito y capacidad y a criterios de idoneidad",
      "Un sinónimo exacto del personal eventual de confianza",
      "Exclusivamente los altos cargos con nombramiento político del Gobierno",
      "El personal laboral con mayor antigüedad en la Administración",
    ],
    correcta: 0,
    explicacion: "El art. 13 del EBEP regula el personal directivo profesional, que desarrolla funciones directivas profesionales en las Administraciones Públicas, definidas como tales en las normas específicas de cada Administración, debiendo su designación atender a principios de mérito y capacidad y a criterios de idoneidad, y llevarse a cabo mediante procedimientos que garanticen la publicidad y concurrencia.",
  },
  {
    id: "ebep-19",
    enunciado: "Según el artículo 14 del EBEP, ¿cuál de los siguientes es un derecho individual reconocido a los empleados públicos?",
    opciones: [
      "A la inamovilidad en la condición de funcionario de carrera, entre otros derechos como la formación continua, la progresión en la carrera profesional o el respeto de su intimidad",
      "Al ejercicio libre de cualquier actividad privada incompatible, sin ninguna limitación",
      "A no someterse a ninguna evaluación del desempeño",
      "A la libre elección del destino, sin ningún procedimiento de provisión",
    ],
    correcta: 0,
    explicacion: "El art. 14 del EBEP enumera un amplio catálogo de derechos individuales de los empleados públicos, entre ellos la inamovilidad en la condición de funcionario de carrera, la formación continua, la progresión en la carrera profesional, la percepción de las retribuciones correspondientes, y el respeto de su intimidad, orientación sexual, propia imagen y dignidad en el trabajo.",
  },
  {
    id: "ebep-20",
    enunciado: "Según el artículo 15 del EBEP, ¿qué derechos individuales se ejercen de forma colectiva por los empleados públicos?",
    opciones: [
      "Entre otros, la libertad sindical, la negociación colectiva y participación en la determinación de las condiciones de trabajo, y el ejercicio del derecho de huelga con garantía del mantenimiento de los servicios esenciales",
      "Únicamente el derecho a la formación continua",
      "El derecho a la inamovilidad en el puesto de trabajo",
      "El derecho a la evaluación del desempeño",
    ],
    correcta: 0,
    explicacion: "El art. 15 del EBEP reconoce como derechos individuales ejercidos colectivamente, entre otros, la libertad sindical, la negociación colectiva y la participación en la determinación de las condiciones de trabajo, y el ejercicio del derecho de huelga, con la garantía del mantenimiento de los servicios esenciales de la comunidad.",
  },
  {
    id: "ebep-21",
    enunciado: "Según el artículo 20 del EBEP, ¿qué es la evaluación del desempeño?",
    opciones: [
      "El procedimiento mediante el cual se mide y valora la conducta profesional y el rendimiento o el logro de resultados de los empleados públicos, aplicado con criterios de transparencia, objetividad, imparcialidad y no discriminación",
      "Un sinónimo exacto del procedimiento disciplinario",
      "Un trámite exclusivamente aplicable al personal eventual",
      "Un procedimiento que solo se aplica una vez, en el momento del ingreso en la Administración",
    ],
    correcta: 0,
    explicacion: "El art. 20 del EBEP regula la evaluación del desempeño como el procedimiento mediante el cual se mide y valora la conducta profesional y el rendimiento o el logro de resultados de los empleados públicos, debiendo su aplicación tener efectos en la carrera profesional, en la formación, en la provisión de puestos y en la percepción de determinadas retribuciones complementarias, con sujeción a los principios de transparencia, objetividad, imparcialidad y no discriminación.",
  },
  {
    id: "ebep-22",
    enunciado: "Según el artículo 52 del EBEP, ¿a qué están obligados los empleados públicos en relación con sus deberes y el Código de Conducta?",
    opciones: [
      "A desempeñar con diligencia las tareas que tengan asignadas y a velar por los intereses generales con sujeción y observancia de la Constitución y del resto del ordenamiento jurídico, debiendo actuar conforme a los principios recogidos en dicho Código de Conducta",
      "Únicamente a cumplir el horario laboral establecido, sin ninguna otra obligación",
      "A obedecer cualquier orden de un superior, sin ninguna excepción posible",
      "A afiliarse obligatoriamente a un sindicato representativo",
    ],
    correcta: 0,
    explicacion: "El art. 52 del EBEP dispone que los empleados públicos deben desempeñar con diligencia las tareas que tengan asignadas y velar por los intereses generales con sujeción y observancia de la Constitución y del resto del ordenamiento jurídico, debiendo además actuar con arreglo a los principios éticos y de conducta recogidos en el propio Código de Conducta (arts. 53 y 54).",
  },
  {
    id: "ebep-23",
    enunciado: "¿Cuál de los siguientes es, según el artículo 53 del EBEP, un principio ético que debe regir la actuación de los empleados públicos?",
    opciones: [
      "La objetividad, integridad, neutralidad, responsabilidad, imparcialidad, confidencialidad, dedicación al servicio público, transparencia, ejemplaridad, austeridad, accesibilidad, eficacia, honradez, promoción del entorno cultural y medioambiental, y respeto a la igualdad entre mujeres y hombres",
      "Únicamente la lealtad personal hacia el superior jerárquico inmediato",
      "El principio de máxima discrecionalidad, sin ninguna limitación ética",
      "La primacía del interés particular del empleado sobre el interés general",
    ],
    correcta: 0,
    explicacion: "El art. 53 del EBEP enumera un amplio catálogo de principios éticos que deben regir la actuación de los empleados públicos, entre ellos la objetividad, integridad, neutralidad, responsabilidad, imparcialidad, confidencialidad, dedicación al servicio público, transparencia, ejemplaridad, austeridad, accesibilidad, eficacia, honradez, la promoción del entorno cultural y medioambiental, y el respeto a la igualdad entre mujeres y hombres.",
  },
  {
    id: "ebep-24",
    enunciado: "¿Qué naturaleza tienen los principios de conducta recogidos en el artículo 54 del EBEP, en relación con el régimen disciplinario?",
    opciones: [
      "Informarán la interpretación y aplicación del régimen disciplinario de los empleados públicos, sin perjuicio de su carácter orientador de su actuación profesional cotidiana",
      "Carecen de cualquier eficacia jurídica, siendo meras recomendaciones sin ninguna consecuencia práctica",
      "Sustituyen íntegramente al régimen disciplinario regulado en el propio EBEP",
      "Solo resultan aplicables al personal directivo profesional, no al resto de empleados públicos",
    ],
    correcta: 0,
    explicacion: "El art. 54 del EBEP, tras enumerar los principios de conducta de los empleados públicos (tratar con atención a los ciudadanos, el respeto a la Constitución, la igualdad de trato, la fundamentación de las resoluciones, entre otros), establece que dichos principios informarán la interpretación y aplicación del régimen disciplinario de los empleados públicos.",
  },
  {
    id: "ebep-25",
    enunciado: "Según el artículo 55 del EBEP, ¿qué principios rectores deben regir el acceso al empleo público?",
    opciones: [
      "Igualdad, mérito y capacidad, así como el respeto a los principios de publicidad, transparencia, imparcialidad y profesionalidad de los órganos de selección, entre otros",
      "Únicamente el principio de antigüedad en la Administración",
      "El principio de libre designación discrecional por la autoridad competente, sin ningún otro criterio",
      "El principio de sorteo puro entre todos los aspirantes que presenten solicitud",
    ],
    correcta: 0,
    explicacion: "El art. 55 del EBEP establece que todos los ciudadanos tienen derecho al acceso al empleo público de acuerdo con los principios constitucionales de igualdad, mérito y capacidad, así como con el respeto a los principios de publicidad, transparencia, imparcialidad y profesionalidad de los órganos de selección, entre otros que enumera el propio precepto.",
  },
  {
    id: "ebep-26",
    enunciado: "Según el artículo 60 del EBEP, ¿qué características deben reunir los órganos de selección del personal funcionario?",
    opciones: [
      "Ser colegiados y su composición deberá ajustarse a los principios de imparcialidad y profesionalidad de sus miembros, tendiéndose asimismo a la paridad entre mujer y hombre",
      "Estar compuestos exclusivamente por un único miembro designado a dedo por la autoridad convocante",
      "Carecer de cualquier requisito de imparcialidad o profesionalidad",
      "Estar compuestos únicamente por personal eventual de confianza",
    ],
    correcta: 0,
    explicacion: "El art. 60 del EBEP exige que los órganos de selección sean colegiados y que su composición se ajuste a los principios de imparcialidad y profesionalidad de sus miembros, tendiéndose asimismo a la paridad entre mujer y hombre, no pudiendo formar parte de ellos el personal de elección o de designación política, los funcionarios interinos ni el personal eventual.",
  },
  {
    id: "ebep-27",
    enunciado: "Según el artículo 69 del EBEP, ¿qué objetivo persigue la planificación de los recursos humanos en las Administraciones Públicas?",
    opciones: [
      "Contribuir a la consecución de la eficacia en la prestación de los servicios y de la eficiencia en la utilización de los recursos económicos disponibles, mediante la dimensión adecuada de sus efectivos, su mejor distribución, formación, promoción profesional y movilidad",
      "Maximizar exclusivamente el número total de empleados públicos, sin ningún otro criterio",
      "Eliminar por completo cualquier proceso de evaluación del desempeño",
      "Sustituir a todo el personal funcionario por personal laboral en el plazo de un año",
    ],
    correcta: 0,
    explicacion: "El art. 69 del EBEP establece que la planificación de los recursos humanos en las Administraciones Públicas tiene como objetivo contribuir a la consecución de la eficacia en la prestación de los servicios y de la eficiencia en la utilización de los recursos económicos disponibles, mediante la dimensión adecuada de sus efectivos, su mejor distribución, formación, promoción profesional y movilidad.",
  },
  {
    id: "ebep-28",
    enunciado: "Según el artículo 74 del EBEP, ¿qué es la relación de puestos de trabajo (RPT)?",
    opciones: [
      "El instrumento técnico a través del cual se realiza la ordenación del personal, de acuerdo con las necesidades de los servicios, y se precisan los requisitos para el desempeño de cada puesto en los términos que establezcan las respectivas normas de desarrollo",
      "Un sinónimo exacto de la oferta de empleo público anual",
      "Un listado meramente informativo sin ningún efecto jurídico vinculante",
      "Un documento exclusivamente aplicable al personal laboral, nunca al funcionario",
    ],
    correcta: 0,
    explicacion: "El art. 74 del EBEP establece que las Administraciones Públicas estructurarán su organización a través de relaciones de puestos de trabajo u otros instrumentos organizativos similares, que constituyen el instrumento técnico a través del cual se realiza la ordenación del personal de acuerdo con las necesidades de los servicios, precisando los requisitos exigidos para el desempeño de cada puesto.",
  },
  {
    id: "ebep-29",
    enunciado: "Según el artículo 93 del EBEP, ¿a qué principios se sujeta el ejercicio de la potestad disciplinaria sobre los empleados públicos?",
    opciones: [
      "A los principios de la potestad sancionadora recogidos en la legislación de régimen jurídico de las Administraciones Públicas y del procedimiento administrativo común",
      "Al principio de discrecionalidad absoluta del superior jerárquico, sin ningún límite legal",
      "Exclusivamente al Código Penal, con exclusión de cualquier otra normativa",
      "A ningún principio específico, tratándose de una potestad completamente libre",
    ],
    correcta: 0,
    explicacion: "El art. 93 del EBEP dispone que los empleados públicos quedan sujetos al régimen disciplinario establecido en el propio Estatuto y en las normas que las Leyes de Función Pública dicten en su desarrollo, sujetándose el ejercicio de la potestad disciplinaria a los principios de la potestad sancionadora recogidos en la legislación de régimen jurídico de las Administraciones Públicas y del procedimiento administrativo común.",
  },
  {
    id: "ebep-30",
    enunciado: "Según el artículo 95 del EBEP, ¿cómo se clasifican las faltas disciplinarias de los funcionarios públicos?",
    opciones: [
      "En muy graves, graves y leves",
      "Únicamente en graves y leves",
      "En faltas administrativas y faltas penales",
      "No existe ninguna clasificación de las faltas disciplinarias en el EBEP",
    ],
    correcta: 0,
    explicacion: "El art. 95 del EBEP clasifica las faltas disciplinarias de los funcionarios públicos en muy graves, graves y leves, enumerando el propio precepto, en su apartado 2, las conductas que en todo caso tienen la consideración de faltas muy graves (como el incumplimiento del deber de respeto a la Constitución, el abandono del servicio, o la discriminación por razón de origen racial o étnico, entre otras).",
  },
];
