import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "emi-01",
    enunciado: "¿Qué norma desarrolla actualmente la estructura orgánica básica del Ministerio del Interior?",
    opciones: [
      "El Real Decreto 734/2020, de 4 de agosto",
      "El Real Decreto 207/2024, de 27 de febrero",
      "La Ley Orgánica 2/1986, de 13 de marzo",
      "El Real Decreto 1009/2023, de 5 de diciembre",
    ],
    correcta: 1,
    explicacion: "El art. 1 se enmarca en el Real Decreto 207/2024, de 27 de febrero, que deroga expresamente el Real Decreto 734/2020 (disposición derogatoria única).",
  },
  {
    id: "emi-02",
    enunciado: "Según el artículo 1, ¿en cuántos órganos superiores y directivos se estructura el Ministerio del Interior?",
    opciones: [
      "Únicamente en la Secretaría de Estado de Seguridad y la Subsecretaría",
      "En la Secretaría de Estado de Seguridad, la Secretaría General de Instituciones Penitenciarias, la Secretaría General de Protección Civil y Emergencias, y la Subsecretaría del Interior",
      "En tres Direcciones Generales exclusivamente",
      "En dos Secretarías de Estado",
    ],
    correcta: 1,
    explicacion: "El art. 1.5 estructura el Ministerio en estos cuatro órganos superiores: Secretaría de Estado de Seguridad, Secretaría General de Instituciones Penitenciarias, Secretaría General de Protección Civil y Emergencias, y Subsecretaría del Interior.",
  },
  {
    id: "emi-03",
    enunciado: "¿Qué órganos directivos dependen de la Secretaría de Estado de Seguridad según el artículo 1.5.a)?",
    opciones: [
      "La Dirección General de la Policía y la Dirección General de Tráfico",
      "La Dirección General de la Policía, la Dirección General de la Guardia Civil, la Dirección General de Relaciones Internacionales y Extranjería, y la Dirección General de Coordinación y Estudios",
      "Solo la Dirección General de la Policía y la Dirección General de la Guardia Civil",
      "La Dirección General de Política Interior y la Dirección General de Protección Internacional",
    ],
    correcta: 1,
    explicacion: "El art. 1.5.a) enumera estos cuatro órganos directivos dependientes de la Secretaría de Estado de Seguridad.",
  },
  {
    id: "emi-04",
    enunciado: "Según el artículo 3, ¿qué rango administrativo tiene el titular de la Dirección General de la Policía?",
    opciones: ["Rango de director general", "Rango de subsecretario", "Rango de secretario de Estado", "Rango de subdirector general"],
    correcta: 1,
    explicacion: "El art. 3.1 establece que el titular de la Dirección General de la Policía tiene rango de subsecretario y ejerce el mando directo de la Policía Nacional bajo la dependencia de la Secretaría de Estado de Seguridad.",
  },
  {
    id: "emi-05",
    enunciado: "¿Qué órgano, dependiente directamente del titular de la Dirección General de la Policía, se encarga del mantenimiento del orden público y la seguridad ciudadana, dirigiendo las unidades centrales y territoriales?",
    opciones: [
      "El Gabinete Técnico",
      "La Dirección Adjunta Operativa",
      "La Subdirección General de Logística e Innovación",
      "La División de Cooperación Internacional",
    ],
    correcta: 1,
    explicacion: "El art. 3.2.a) atribuye a la Dirección Adjunta Operativa la dirección, coordinación y supervisión de las unidades centrales, supraterritoriales y territoriales de la Policía Nacional.",
  },
  {
    id: "emi-06",
    enunciado: "Según el artículo 3.3, ¿qué Comisaría General se encarga de la investigación y persecución de infracciones supraterritoriales, especialmente drogas y delincuencia organizada?",
    opciones: [
      "La Comisaría General de Información",
      "La Comisaría General de Seguridad Ciudadana",
      "La Comisaría General de Policía Judicial",
      "La Comisaría General de Policía Científica",
    ],
    correcta: 2,
    explicacion: "El art. 3.3.b) atribuye a la Comisaría General de Policía Judicial la investigación y persecución de infracciones supraterritoriales relacionadas con drogas, delincuencia organizada, económica, financiera y tecnológica.",
  },
  {
    id: "emi-07",
    enunciado: "¿Qué órgano corresponde al control de entrada y salida del territorio nacional, y al régimen policial de extranjería, refugio y asilo, según el artículo 3.3?",
    opciones: [
      "La Comisaría General de Extranjería y Fronteras",
      "La Comisaría General de Seguridad Ciudadana",
      "La Dirección General de Relaciones Internacionales y Extranjería",
      "La División de Cooperación Internacional",
    ],
    correcta: 0,
    explicacion: "El art. 3.3.d) atribuye estas funciones a la Comisaría General de Extranjería y Fronteras.",
  },
  {
    id: "emi-08",
    enunciado: "Según el artículo 4, ¿bajo la dependencia de quién ejerce el titular de la Dirección General de la Guardia Civil el mando directo del Cuerpo?",
    opciones: [
      "Directamente del Consejo de Ministros",
      "De la persona titular de la Secretaría de Estado de Seguridad",
      "De la persona titular de la Subsecretaría del Interior",
      "Del Ministerio de Defensa exclusivamente",
    ],
    correcta: 1,
    explicacion: "El art. 4.1 establece que, bajo la dependencia de la persona titular de la Secretaría de Estado de Seguridad, el titular de la Dirección General de la Guardia Civil ejerce el mando directo del Cuerpo.",
  },
  {
    id: "emi-09",
    enunciado: "¿Qué órgano, con nivel orgánico de subdirección general, tiene encomendada la recepción, integración y análisis de la información estratégica en la lucha contra el crimen organizado y el terrorismo?",
    opciones: [
      "El CITCO (Centro de Inteligencia contra el Terrorismo y el Crimen Organizado)",
      "La Oficina de Coordinación y Ciberseguridad (OCC)",
      "El Centro Nacional de Protección de Infraestructuras Críticas (CNPIC)",
      "La Inspección de Personal y Servicios de Seguridad",
    ],
    correcta: 0,
    explicacion: "El art. 2.3 atribuye estas funciones al CITCO, dependiente de la persona titular de la Secretaría de Estado de Seguridad.",
  },
  {
    id: "emi-10",
    enunciado: "Según el artículo 9, ¿qué órganos directivos dependen de la Subsecretaría del Interior?",
    opciones: [
      "La Secretaría General Técnica, la Dirección General de Política Interior, la Dirección General de Tráfico, la Dirección General de Apoyo a Víctimas del Terrorismo y la Dirección General de Protección Internacional",
      "Únicamente la Dirección General de la Policía y la Dirección General de la Guardia Civil",
      "La Secretaría General de Instituciones Penitenciarias y la Secretaría General de Protección Civil y Emergencias",
      "El CITCO y la Oficina de Coordinación y Ciberseguridad",
    ],
    correcta: 0,
    explicacion: "El art. 9.5 enumera estos cinco órganos directivos dependientes de la Subsecretaría del Interior.",
  },
  {
    id: "emi-11",
    enunciado: "¿Qué Comisaría General presta los servicios de criminalística, identificación, analítica e investigación técnica, según el artículo 3.3?",
    opciones: [
      "La Comisaría General de Policía Científica",
      "La Comisaría General de Información",
      "La Comisaría General de Policía Judicial",
      "La Comisaría General de Seguridad Ciudadana",
    ],
    correcta: 0,
    explicacion: "El art. 3.3.e) atribuye estos servicios a la Comisaría General de Policía Científica.",
  },
  {
    id: "emi-12",
    enunciado: "Según el artículo 1.1, ¿qué materia NO corresponde al Ministerio del Interior entre las que se enumeran?",
    opciones: [
      "La seguridad ciudadana",
      "El régimen de protección internacional, apatridia y protección de personas desplazadas",
      "La política exterior y de relaciones diplomáticas con terceros países",
      "La administración y régimen de las instituciones penitenciarias",
    ],
    correcta: 2,
    explicacion: "El art. 1.1 no atribuye al Ministerio del Interior la política exterior general, que corresponde al Ministerio de Asuntos Exteriores; sí le atribuye seguridad ciudadana, protección internacional e instituciones penitenciarias.",
  },
  {
    id: "emi-13",
    enunciado: "¿A qué órgano corresponde, según el artículo 2, la propuesta y ejecución de la política del Gobierno en materia de protección civil y gestión de emergencias?",
    opciones: [
      "A la Secretaría de Estado de Seguridad",
      "A la Secretaría General de Protección Civil y Emergencias",
      "A la Dirección General de la Policía",
      "A la Subsecretaría del Interior",
    ],
    correcta: 1,
    explicacion: "El art. 2 atribuye a la Secretaría General de Protección Civil y Emergencias, como órgano superior del Ministerio, la propuesta y ejecución de la política del Gobierno en materia de protección civil y gestión de emergencias.",
  },
  {
    id: "emi-14",
    enunciado: "¿Qué órgano directivo, dependiente de la Secretaría de Estado de Seguridad, ejerce las funciones de coordinación e impulso de las actuaciones del Departamento en materia de relaciones internacionales policiales?",
    opciones: [
      "La Comisaría General de Extranjería y Fronteras",
      "La Dirección General de Relaciones Internacionales y Extranjería",
      "La Dirección Adjunta Operativa",
      "El CITCO",
    ],
    correcta: 1,
    explicacion: "El art. 1.5.a) atribuye a la Dirección General de Relaciones Internacionales y Extranjería, entre otras funciones, la coordinación e impulso de las relaciones internacionales del Departamento en materia policial y de extranjería.",
  },
  {
    id: "emi-15",
    enunciado: "¿A quién corresponde, con rango de Ministro, la superior dirección del Ministerio del Interior?",
    opciones: [
      "Al Secretario de Estado de Seguridad",
      "Al titular del Ministerio del Interior",
      "Al Subsecretario del Interior",
      "Al Director General de la Policía",
    ],
    correcta: 1,
    explicacion: "Conforme a la estructura orgánica del Real Decreto 207/2024, corresponde al titular del Ministerio del Interior, como órgano superior del Departamento, su superior dirección, impulso y gestión, correspondiéndole las competencias generales previstas en la Ley 40/2015 para los Ministros.",
  },
  {
    id: "emi-16",
    enunciado: "¿Qué órgano directivo del Ministerio del Interior se encarga de la política de circulación, la seguridad vial y la gestión del Registro de Vehículos y del Registro de Conductores e Infractores?",
    opciones: [
      "La Dirección General de Tráfico",
      "La Comisaría General de Seguridad Ciudadana",
      "La Dirección Adjunta Operativa",
      "La Subsecretaría del Interior",
    ],
    correcta: 0,
    explicacion: "La Dirección General de Tráfico (DGT), integrada en la estructura del Ministerio del Interior, tiene encomendada la ejecución de la política del Gobierno en materia de tráfico, circulación de vehículos a motor y seguridad vial, así como la gestión de los registros correspondientes.",
  },
  {
    id: "emi-17",
    enunciado: "¿El Centro Nacional de Inteligencia (CNI) forma parte de la estructura orgánica del Ministerio del Interior?",
    opciones: [
      "Sí, depende directamente de la Secretaría de Estado de Seguridad",
      "No; el CNI es un organismo público adscrito al Ministerio de la Presidencia, no al Ministerio del Interior",
      "Sí, es una Comisaría General más de la Dirección General de la Policía",
      "Sí, sustituyó al CITCO en sus funciones",
    ],
    correcta: 1,
    explicacion: "El Centro Nacional de Inteligencia (CNI), regulado por la Ley 11/2002, es un organismo público adscrito al Ministerio de la Presidencia, distinto del Ministerio del Interior y de los servicios de información policial (como el CITCO, que sí forma parte de este último).",
  },
  {
    id: "emi-18",
    enunciado: "Según la Ley Orgánica 2/1986, ¿de qué Ministerio depende la Guardia Civil para el desempeño de las misiones de carácter militar?",
    opciones: [
      "Exclusivamente del Ministerio del Interior",
      "Del Ministerio de Defensa, sin perjuicio de su dependencia del Ministerio del Interior para el desempeño de las funciones que la ley le atribuye en materia de seguridad ciudadana",
      "De la Presidencia del Gobierno directamente",
      "Del Ministerio de Asuntos Exteriores",
    ],
    correcta: 1,
    explicacion: "La Guardia Civil, por su naturaleza militar, depende del Ministerio de Defensa en el desempeño de las misiones de carácter militar, y del Ministerio del Interior cuando ejerce funciones propias de seguridad ciudadana, conforme a la doble dependencia prevista en la LO 2/1986.",
  },
  {
    id: "emi-19",
    enunciado: "¿Qué órgano superior del Ministerio del Interior tiene encomendada la ordenación, dirección y coordinación de los servicios penitenciarios en el territorio de gestión estatal?",
    opciones: [
      "La Secretaría de Estado de Seguridad",
      "La Secretaría General de Instituciones Penitenciarias",
      "La Subsecretaría del Interior",
      "La Dirección General de la Policía",
    ],
    correcta: 1,
    explicacion: "La Secretaría General de Instituciones Penitenciarias, uno de los órganos superiores del Departamento, tiene encomendada la dirección, ordenación, coordinación y ejecución de la política penitenciaria en el ámbito de gestión estatal (algunas Comunidades Autónomas, como Cataluña, tienen competencias propias transferidas).",
  },
  {
    id: "emi-20",
    enunciado: "¿Qué diferencia hay entre la Secretaría de Estado de Seguridad y la Subsecretaría del Interior en cuanto a su ámbito funcional?",
    opciones: [
      "Son órganos idénticos con distinto nombre",
      "La Secretaría de Estado de Seguridad dirige la actividad operativa policial (Policía Nacional y Guardia Civil); la Subsecretaría se encarga de los servicios comunes, régimen interior y apoyo técnico y administrativo del Departamento",
      "La Subsecretaría manda directamente sobre la Guardia Civil, y la Secretaría de Estado solo sobre la Policía Nacional",
      "Ambas dependen jerárquicamente una de la otra en todo caso",
    ],
    correcta: 1,
    explicacion: "La Secretaría de Estado de Seguridad asume la dirección superior de la actividad operativa de la Policía Nacional y la Guardia Civil, mientras que la Subsecretaría del Interior desempeña funciones de gestión de los servicios comunes, régimen interior, personal, informática, inspección y apoyo técnico y administrativo del Departamento.",
  },
  {
    id: "emi-21",
    enunciado: "¿Qué unidad del Ministerio del Interior tiene atribuidas las funciones de protección de altas personalidades del Estado y de otras personas que determine el Gobierno?",
    opciones: [
      "El Servicio de Protección de Altas Personalidades (Policía Nacional), integrado en la estructura de la Dirección General de la Policía",
      "La Guardia Civil, en exclusiva",
      "La Comisaría General de Extranjería y Fronteras",
      "La Secretaría General Técnica",
    ],
    correcta: 0,
    explicacion: "Dentro de la Dirección General de la Policía, el Servicio de Protección de Altas Personalidades (integrado en las unidades operativas de la Dirección Adjunta Operativa) tiene atribuida la protección de altas instituciones y personalidades del Estado y otras que el Gobierno determine.",
  },
  {
    id: "emi-22",
    enunciado: "¿Qué son los Delegados y Subdelegados del Gobierno en relación con el Ministerio del Interior?",
    opciones: [
      "Órganos periféricos que, sin perjuicio de su dependencia orgánica de la Presidencia del Gobierno, dirigen las Fuerzas y Cuerpos de Seguridad del Estado en su ámbito territorial y coordinan la actuación de la Administración General del Estado",
      "Cargos que dependen exclusivamente del Ministerio del Interior sin relación con la Presidencia",
      "Órganos exclusivamente consultivos sin funciones ejecutivas",
      "Unidades integradas en la Dirección General de la Policía",
    ],
    correcta: 0,
    explicacion: "Los Delegados y Subdelegados del Gobierno, regulados en la Ley 40/2015, dirigen y coordinan las Fuerzas y Cuerpos de Seguridad del Estado en su ámbito territorial y actúan en estrecha coordinación con el Ministerio del Interior en materia de seguridad ciudadana, sin perjuicio de su dependencia orgánica de la Presidencia del Gobierno.",
  },
  {
    id: "emi-23",
    enunciado: "¿Qué órgano colegiado, presidido por el Ministro del Interior, coordina las políticas de seguridad entre el Estado y las Comunidades Autónomas con Policía propia?",
    opciones: [
      "El Consejo de Política de Seguridad, previsto en la Ley Orgánica 2/1986",
      "El Consejo Nacional de Seguridad",
      "La Junta de Seguridad de cada Comunidad Autónoma, presidida siempre por el Delegado del Gobierno",
      "El Consejo de Ministros",
    ],
    correcta: 0,
    explicacion: "El Consejo de Política de Seguridad, regulado en el art. cuarenta y ocho de la LO 2/1986, está presidido por el Ministro del Interior e integrado por los Consejeros de Interior o Gobernación de las Comunidades Autónomas con Policía propia, para coordinar la política de seguridad pública.",
  },
  {
    id: "emi-24",
    enunciado: "¿Qué órgano del Ministerio del Interior tiene encomendadas las funciones de gestión de los recursos humanos, formación, régimen retributivo y acción social del personal del Departamento?",
    opciones: [
      "La Subsecretaría del Interior, a través de sus órganos competentes en materia de personal",
      "La Secretaría de Estado de Seguridad, en exclusiva",
      "El CITCO",
      "La Comisaría General de Policía Científica",
    ],
    correcta: 0,
    explicacion: "Corresponde a la Subsecretaría del Interior, como órgano encargado de los servicios comunes del Departamento, la gestión de los recursos humanos, la formación, el régimen retributivo y la acción social del personal, sin perjuicio de las especialidades de la Policía Nacional y la Guardia Civil.",
  },
  {
    id: "emi-25",
    enunciado: "¿Qué es la Escuela Nacional de Policía, dependiente de la Dirección General de la Policía?",
    opciones: [
      "Un centro docente dedicado a la selección, formación básica, promoción y perfeccionamiento del personal de la Policía Nacional",
      "Un órgano exclusivamente de investigación criminal",
      "Un servicio de inteligencia interior",
      "Un cuerpo de intervención en catástrofes",
    ],
    correcta: 0,
    explicacion: "La Escuela Nacional de Policía (integrada en la Comisaría General correspondiente o en el órgano de formación de la Dirección General de la Policía) es el centro docente encargado de la formación básica, promoción y perfeccionamiento profesional de los miembros de la Policía Nacional.",
  },
  {
    id: "emi-26",
    enunciado: "¿Depende del Ministerio del Interior la Fiscalía General del Estado?",
    opciones: [
      "Sí, orgánicamente",
      "No; el Ministerio Fiscal tiene autonomía funcional propia y no se integra en la estructura del Poder Ejecutivo ni del Ministerio del Interior, aunque colabora con las Fuerzas y Cuerpos de Seguridad",
      "Sí, a través de la Secretaría de Estado de Seguridad",
      "Solo en materia de extranjería",
    ],
    correcta: 1,
    explicacion: "El Ministerio Fiscal, regulado por su Estatuto Orgánico (Ley 50/1981), tiene autonomía funcional dentro del Poder Judicial y no forma parte de la estructura del Ministerio del Interior, sin perjuicio de la estrecha colaboración funcional entre el Ministerio Fiscal y las Fuerzas y Cuerpos de Seguridad en la investigación de los delitos.",
  },
  {
    id: "emi-27",
    enunciado: "¿Qué característica tiene el Ministerio del Interior como departamento de la Administración General del Estado?",
    opciones: [
      "Es un órgano exclusivamente consultivo sin capacidad ejecutiva",
      "Es uno de los Ministerios en que se organiza la Administración General del Estado, bajo la dirección de su titular, con rango de Ministro, miembro del Gobierno",
      "Depende jerárquicamente del Ministerio de Justicia",
      "Solo tiene competencias en el ámbito de la Comunidad de Madrid",
    ],
    correcta: 1,
    explicacion: "El Ministerio del Interior es uno de los departamentos ministeriales en que se organiza la Administración General del Estado, conforme a los arts. 4 y 8 de la Ley 50/1997, del Gobierno, bajo la dirección de su titular, miembro del Gobierno con rango de Ministro.",
  },
  {
    id: "emi-28",
    enunciado: "¿Qué diferencia hay entre el CITCO y la Comisaría General de Información?",
    opciones: [
      "Son el mismo órgano con dos nombres distintos",
      "El CITCO es un centro de inteligencia interministerial de análisis estratégico sobre terrorismo y crimen organizado; la Comisaría General de Información es la unidad operativa de la Policía Nacional especializada en la lucha antiterrorista y contra el extremismo violento",
      "El CITCO depende exclusivamente de la Guardia Civil",
      "La Comisaría General de Información se encarga solo de la seguridad vial",
    ],
    correcta: 1,
    explicacion: "El CITCO (Centro de Inteligencia contra el Terrorismo y el Crimen Organizado) desempeña funciones de análisis estratégico y coordinación interministerial de la información, mientras que la Comisaría General de Información es la unidad operativa de la Dirección General de la Policía especializada en la investigación y prevención del terrorismo y el extremismo violento.",
  },
  {
    id: "emi-29",
    enunciado: "¿Qué régimen de recursos cabe interponer contra los actos y resoluciones dictados por los órganos del Ministerio del Interior?",
    opciones: [
      "Ninguno, sus actos son siempre firmes e inatacables",
      "Los recursos administrativos y, en su caso, contencioso-administrativos previstos con carácter general en la Ley 39/2015 y la Ley 29/1998, sin perjuicio de las especialidades de cada procedimiento",
      "Solo cabe el recurso de amparo directamente ante el Tribunal Constitucional",
      "Únicamente el recurso de casación ante el Tribunal Supremo",
    ],
    correcta: 1,
    explicacion: "Como cualquier órgano de la Administración General del Estado, los actos y resoluciones del Ministerio del Interior están sujetos al régimen general de recursos administrativos (Ley 39/2015) y, agotada la vía administrativa, al control de la jurisdicción contencioso-administrativa (Ley 29/1998).",
  },
  {
    id: "emi-30",
    enunciado: "¿Cuál es la denominación oficial completa del cuerpo policial de ámbito estatal dependiente de la Dirección General de la Policía?",
    opciones: [
      "Cuerpo Nacional de Policía, denominado Policía Nacional",
      "Policía Judicial del Estado",
      "Cuerpo General de Seguridad Ciudadana",
      "Guardia Civil de Seguridad Interior",
    ],
    correcta: 0,
    explicacion: "El Cuerpo Nacional de Policía, cuya denominación oficial es Policía Nacional desde la reforma introducida por la LO 9/2015, es el instituto armado de naturaleza civil dependiente de la Dirección General de la Policía, integrada en la Secretaría de Estado de Seguridad del Ministerio del Interior.",
  },
];
