import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "lopn-01",
    enunciado: "Según el artículo 2.1 de la Ley Orgánica 9/2015, ¿qué naturaleza tiene la Policía Nacional?",
    opciones: [
      "Instituto armado de naturaleza militar",
      "Instituto armado de naturaleza civil, con estructura jerarquizada",
      "Cuerpo civil sin estructura jerarquizada",
      "Órgano consultivo del Ministerio del Interior",
    ],
    correcta: 1,
    explicacion: "El art. 2.1 define a la Policía Nacional como instituto armado de naturaleza civil, con estructura jerarquizada.",
  },
  {
    id: "lopn-02",
    enunciado: "¿A quién corresponde el mando superior y el mando directo de la Policía Nacional según el artículo 2.4?",
    opciones: [
      "El mando superior al Director General de la Policía y el directo al Ministro del Interior",
      "El mando superior al Ministro del Interior, a través del Secretario de Estado de Seguridad, y el mando directo al Director General de la Policía, bajo la autoridad del Secretario de Estado de Seguridad",
      "Ambos mandos corresponden exclusivamente al Secretario de Estado de Seguridad",
      "El mando superior y directo corresponden al Rey",
    ],
    correcta: 1,
    explicacion: "El art. 2.4 distingue el mando superior (Ministro del Interior, a través del Secretario de Estado de Seguridad) del mando directo (Director General de la Policía).",
  },
  {
    id: "lopn-03",
    enunciado: "Según el artículo 4, ¿cuáles son los requisitos sucesivos para adquirir la condición de funcionario de carrera de la Policía Nacional?",
    opciones: [
      "Solo superar el proceso selectivo",
      "Superación del proceso selectivo, nombramiento por la autoridad competente, acto de acatamiento de la Constitución y del resto del ordenamiento jurídico, y toma de posesión dentro del plazo establecido",
      "Nombramiento y toma de posesión, sin necesidad de proceso selectivo",
      "Superación del proceso selectivo y juramento ante el Rey",
    ],
    correcta: 1,
    explicacion: "El art. 4 enumera estos cuatro requisitos de cumplimiento sucesivo.",
  },
  {
    id: "lopn-04",
    enunciado: "Según el artículo 5.2.b), ¿a qué edad se declara de oficio la jubilación forzosa?",
    opciones: ["60 años", "63 años", "65 años", "70 años"],
    correcta: 2,
    explicacion: "El art. 5.2.b) fija la jubilación forzosa al cumplir el funcionario los sesenta y cinco años de edad.",
  },
  {
    id: "lopn-05",
    enunciado: "¿Qué establece el artículo 15.2 sobre el régimen de incompatibilidades de los Policías Nacionales?",
    opciones: [
      "Pueden compatibilizar libremente cualquier segundo puesto de trabajo",
      "No se podrá autorizar la compatibilidad para un segundo puesto que menoscabe el cumplimiento de sus deberes, comprometa su imparcialidad, suponga deterioro de la imagen de la Policía Nacional o sea contrario a sus principios básicos de actuación",
      "Solo se prohíbe la compatibilidad con actividades en el sector público",
      "No existe régimen de incompatibilidades específico para la Policía Nacional",
    ],
    correcta: 1,
    explicacion: "El art. 15.2 establece estos límites estrictos a la compatibilidad de un segundo puesto de trabajo.",
  },
  {
    id: "lopn-06",
    enunciado: "Según el artículo 17.1, ¿en qué Escalas se estructura el Cuerpo Nacional de Policía?",
    opciones: [
      "Escala Superior y Escala Básica, únicamente",
      "Escala Superior, Escala Ejecutiva, Escala de Subinspección y Escala Básica",
      "Escala Ejecutiva y Escala de Subinspección, únicamente",
      "Escala Directiva, Escala Técnica y Escala Operativa",
    ],
    correcta: 1,
    explicacion: "El art. 17.1 mantiene las cuatro escalas: Superior, Ejecutiva, de Subinspección y Básica.",
  },
  {
    id: "lopn-07",
    enunciado: "Según el artículo 17.3, ¿en qué subgrupo de clasificación se integra la Escala de Subinspección?",
    opciones: ["Subgrupo A1", "Subgrupo A2", "Subgrupo C1", "Subgrupo C2"],
    correcta: 1,
    explicacion: "El art. 17.3.b) clasifica la Escala de Subinspección en el Grupo A, subgrupo A2, mientras que las Escalas Superior y Ejecutiva se integran en el subgrupo A1 y la Escala Básica en el C1.",
  },
  {
    id: "lopn-08",
    enunciado: "Según el artículo 18, ¿qué función corresponde a la Escala de Subinspección?",
    opciones: [
      "La dirección de los servicios policiales",
      "El mando de los servicios policiales",
      "La supervisión de los servicios policiales",
      "La ejecución material de las funciones encomendadas a la Policía Nacional",
    ],
    correcta: 2,
    explicacion: "El art. 18.1.c) atribuye a la Escala de Subinspección la supervisión de los servicios policiales, mientras que la dirección corresponde a la Superior, el mando a la Ejecutiva y la ejecución material a la Básica.",
  },
  {
    id: "lopn-09",
    enunciado: "Según el artículo 26.2, ¿qué titulación se exige para el acceso a la categoría de Policía?",
    opciones: [
      "Título universitario oficial de grado",
      "Título de bachiller o equivalente",
      "Título de graduado en Educación Secundaria Obligatoria",
      "No se exige titulación específica",
    ],
    correcta: 1,
    explicacion: "El art. 26.2.b) exige el título de bachiller o equivalente para el acceso a la categoría de Policía, mientras que para Inspector se exige el título universitario oficial de grado.",
  },
  {
    id: "lopn-10",
    enunciado: "Según el artículo 40, ¿en qué consiste la carrera horizontal de los Policías Nacionales?",
    opciones: [
      "En el acceso mediante promoción interna a categorías superiores",
      "En el reconocimiento individualizado del desarrollo profesional alcanzado, mediante la progresión en la estructura de los diferentes puestos de trabajo y la consolidación del grado personal",
      "En el traslado forzoso a otra unidad territorial",
      "En la obtención de recompensas y condecoraciones",
    ],
    correcta: 1,
    explicacion: "El art. 40.3 define así la carrera horizontal, distinta de la carrera vertical (ascenso por promoción interna, art. 40.2).",
  },
  {
    id: "lopn-11",
    enunciado: "¿A través de qué modalidades se puede ascender por promoción interna a las categorías de Oficial de Policía, Subinspector, Inspector, Inspector Jefe, Comisario y Comisario Principal, según el artículo 41?",
    opciones: [
      "Únicamente por concurso-oposición",
      "Concurso-oposición y antigüedad selectiva",
      "Únicamente por antigüedad",
      "Libre designación",
    ],
    correcta: 1,
    explicacion: "El art. 41.1 establece estas dos modalidades de promoción interna para todas las categorías señaladas.",
  },
  {
    id: "lopn-12",
    enunciado: "Según el artículo 52, ¿cuáles son las situaciones administrativas en que pueden hallarse los Policías Nacionales?",
    opciones: [
      "Solo servicio activo y excedencia",
      "Servicio activo, servicios especiales, servicio en otras administraciones públicas, excedencia, suspensión de funciones y segunda actividad",
      "Servicio activo y jubilación, únicamente",
      "Activo, pasivo y reserva",
    ],
    correcta: 1,
    explicacion: "El art. 52 enumera estas seis situaciones administrativas.",
  },
  {
    id: "lopn-13",
    enunciado: "Según el artículo 69.1, ¿a partir de qué edad puede solicitarse el pase a segunda actividad por petición propia en la Escala Básica?",
    opciones: ["55 años", "58 años", "60 años", "62 años"],
    correcta: 1,
    explicacion: "El art. 69.1.d) fija en 58 años la edad para el pase a segunda actividad por petición propia en la Escala Básica (64 años en la Superior, 62 en la Ejecutiva y 60 en la de Subinspección).",
  },
  {
    id: "lopn-14",
    enunciado: "Según el artículo 7 de la Ley Orgánica 4/2010, del Régimen disciplinario del Cuerpo Nacional de Policía, ¿cuál de las siguientes es una falta muy grave?",
    opciones: [
      "El retraso en el cumplimiento de las órdenes recibidas",
      "La grave desconsideración con los ciudadanos",
      "El abandono de servicio, salvo causa de fuerza mayor que impida comunicarlo a un superior",
      "El descuido en el aseo personal",
    ],
    correcta: 2,
    explicacion: "El art. 7.f) de la LO 4/2010 tipifica el abandono de servicio como falta muy grave, salvo causa de fuerza mayor.",
  },
  {
    id: "lopn-15",
    enunciado: "Según el artículo 10 de la Ley Orgánica 4/2010, ¿qué sanciones pueden imponerse por la comisión de faltas muy graves?",
    opciones: [
      "Solo el apercibimiento",
      "La separación del servicio, la suspensión de funciones de tres meses y un día hasta un máximo de seis años, y el traslado forzoso",
      "Únicamente la suspensión de funciones de uno a cuatro días",
      "Solo la separación del servicio",
    ],
    correcta: 1,
    explicacion: "El art. 10.1 de la LO 4/2010 enumera estas tres sanciones para las faltas muy graves.",
  },
  {
    id: "lopn-16",
    enunciado: "Según el artículo 15 de la Ley Orgánica 4/2010, ¿en qué plazo prescriben las faltas graves?",
    opciones: ["Un mes", "Seis meses", "Dos años", "Tres años"],
    correcta: 2,
    explicacion: "El art. 15.1 de la LO 4/2010 fija en tres años la prescripción de las faltas muy graves, en dos años la de las graves y en un mes la de las leves.",
  },
];
