import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "lrjsp-01",
    enunciado: "Según el artículo 2 de la Ley 40/2015, ¿qué integra el sector público institucional?",
    opciones: [
      "Únicamente los organismos autónomos",
      "Organismos y entidades de derecho público vinculados a las Administraciones, las entidades de derecho privado vinculadas o dependientes de ellas y las Universidades públicas",
      "Solo las sociedades mercantiles estatales",
      "Exclusivamente los consorcios y fundaciones",
    ],
    correcta: 1,
    explicacion: "El art. 2.2 define el sector público institucional con estos tres componentes.",
  },
  {
    id: "lrjsp-02",
    enunciado: "¿Cuál de los siguientes es un principio general de actuación de las Administraciones Públicas según el artículo 3?",
    opciones: [
      "Discrecionalidad absoluta",
      "Racionalización y agilidad de los procedimientos administrativos",
      "Opacidad en la gestión",
      "Centralización obligatoria de todas las competencias",
    ],
    correcta: 1,
    explicacion: "El art. 3.1.d) recoge la racionalización y agilidad de los procedimientos administrativos y de las actividades materiales de gestión.",
  },
  {
    id: "lrjsp-03",
    enunciado: "Según el artículo 5, ¿qué se entiende por órgano administrativo?",
    opciones: [
      "Cualquier funcionario público a título individual",
      "Las unidades administrativas a las que se atribuyan funciones con efectos jurídicos frente a terceros, o cuya actuación tenga carácter preceptivo",
      "Solo los Ministerios",
      "Exclusivamente los órganos colegiados",
    ],
    correcta: 1,
    explicacion: "El art. 5.1 recoge esta definición de órgano administrativo.",
  },
  {
    id: "lrjsp-04",
    enunciado: "Según el artículo 9, ¿qué competencias no pueden ser objeto de delegación?",
    opciones: [
      "Las relativas a la gestión ordinaria de personal",
      "Las atribuidas a la Jefatura del Estado, Presidencia del Gobierno o Cortes Generales, la adopción de disposiciones generales, y la resolución de recursos por el órgano que dictó el acto recurrido, entre otras",
      "Todas las competencias son delegables sin excepción",
      "Solo las competencias presupuestarias",
    ],
    correcta: 1,
    explicacion: "El art. 9.2 enumera estas materias, entre otras, como indelegables.",
  },
  {
    id: "lrjsp-05",
    enunciado: "¿Qué principio rige el ejercicio de la potestad sancionadora según el artículo 25?",
    opciones: [
      "Puede ejercerse sin necesidad de norma habilitante",
      "Solo se ejercerá cuando haya sido expresamente reconocida por una norma con rango de Ley",
      "Se ejerce discrecionalmente por cualquier funcionario",
      "No requiere procedimiento alguno",
    ],
    correcta: 1,
    explicacion: "El art. 25.1 exige reconocimiento expreso por norma con rango de Ley para el ejercicio de la potestad sancionadora.",
  },
  {
    id: "lrjsp-06",
    enunciado: "Según el artículo 30, ¿en qué plazo prescriben, con carácter general y salvo previsión distinta, las infracciones administrativas muy graves?",
    opciones: ["Seis meses", "Un año", "Dos años", "Tres años"],
    correcta: 3,
    explicacion: "El art. 30.1 fija en tres años la prescripción de las infracciones muy graves cuando la norma sancionadora no establezca otro plazo.",
  },
  {
    id: "lrjsp-07",
    enunciado: "Según el artículo 32, ¿en qué casos los particulares tienen derecho a ser indemnizados por las Administraciones Públicas?",
    opciones: [
      "Solo cuando exista dolo del funcionario",
      "Por toda lesión que sufran en sus bienes y derechos como consecuencia del funcionamiento normal o anormal de los servicios públicos, salvo fuerza mayor o deber jurídico de soportarla",
      "Nunca, la Administración es irresponsable",
      "Solo en caso de expropiación forzosa",
    ],
    correcta: 1,
    explicacion: "El art. 32.1 establece el principio de responsabilidad patrimonial objetiva por funcionamiento normal o anormal de los servicios públicos.",
  },
  {
    id: "lrjsp-08",
    enunciado: "Según el artículo 55, ¿qué órganos son considerados superiores en la organización central de la Administración General del Estado?",
    opciones: [
      "Los Subsecretarios y Directores generales",
      "Los Ministros y los Secretarios de Estado",
      "Los Subdirectores generales",
      "Los Delegados del Gobierno",
    ],
    correcta: 1,
    explicacion: "El art. 55.3.a) identifica como órganos superiores a los Ministros y Secretarios de Estado, distinguiéndolos de los órganos directivos (Subsecretarios, Directores generales, Subdirectores generales).",
  },
  {
    id: "lrjsp-09",
    enunciado: "¿Qué rango tienen los Delegados del Gobierno en las Comunidades Autónomas según el artículo 72?",
    opciones: ["Rango de Director general", "Rango de Subsecretario", "Rango de Ministro", "Rango de Secretario de Estado"],
    correcta: 1,
    explicacion: "El art. 72.3 establece que los Delegados del Gobierno son órganos directivos con rango de Subsecretario.",
  },
  {
    id: "lrjsp-10",
    enunciado: "Según el artículo 84, ¿qué tipos de organismos públicos integran el sector público institucional estatal?",
    opciones: [
      "Solo los organismos autónomos",
      "Organismos autónomos, entidades públicas empresariales y agencias estatales",
      "Únicamente las sociedades mercantiles estatales",
      "Solo los consorcios",
    ],
    correcta: 1,
    explicacion: "El art. 84.1.a) clasifica los organismos públicos en estas tres categorías.",
  },
  {
    id: "lrjsp-11",
    enunciado: "Según el artículo 98, ¿cuál es la naturaleza de los organismos autónomos?",
    opciones: [
      "Entidades de derecho privado que actúan en régimen de mercado",
      "Entidades de derecho público, con personalidad jurídica propia, que desarrollan actividades propias de la Administración Pública en régimen de descentralización funcional",
      "Sociedades mercantiles participadas mayoritariamente por el Estado",
      "Fundaciones sin ánimo de lucro",
    ],
    correcta: 1,
    explicacion: "El art. 98.1 define así a los organismos autónomos.",
  },
  {
    id: "lrjsp-12",
    enunciado: "Según el artículo 140, ¿cuál es la diferencia entre cooperación y coordinación en las relaciones interadministrativas?",
    opciones: [
      "No existe diferencia, son sinónimos",
      "La cooperación es voluntaria, mientras que la coordinación es obligatoria cuando la Constitución y el ordenamiento jurídico así lo prevén",
      "La coordinación es siempre voluntaria y la cooperación obligatoria",
      "Ambas son siempre obligatorias",
    ],
    correcta: 1,
    explicacion: "El art. 140.1.c) y d) distinguen la colaboración/cooperación (voluntaria) de la coordinación (obligatoria para garantizar la coherencia de actuaciones).",
  },
  {
    id: "lrjsp-13",
    enunciado: "¿Qué es la Conferencia de Presidentes según el artículo 146?",
    opciones: [
      "Un órgano de cooperación bilateral entre el Estado y una única Comunidad Autónoma",
      "Un órgano de cooperación multilateral entre el Gobierno de la Nación y los Presidentes de las Comunidades Autónomas y de las Ciudades de Ceuta y Melilla, presidido por el Presidente del Gobierno",
      "Un órgano exclusivamente consultivo del Congreso de los Diputados",
      "La reunión anual de los Delegados del Gobierno",
    ],
    correcta: 1,
    explicacion: "El art. 146.1 define la Conferencia de Presidentes con esta composición y presidencia.",
  },
];
