import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "lg-01",
    enunciado: "Según el artículo 1 de la Ley 50/1997, del Gobierno, ¿quiénes integran el Gobierno?",
    opciones: [
      "Solo el Presidente y los Ministros",
      "El Presidente, el Vicepresidente o Vicepresidentes en su caso, y los Ministros",
      "El Presidente y los Secretarios de Estado",
      "Todos los altos cargos de la Administración General del Estado",
    ],
    correcta: 1,
    explicacion: "El art. 1.2 establece que el Gobierno se compone del Presidente, del Vicepresidente o Vicepresidentes, en su caso, y de los Ministros.",
  },
  {
    id: "lg-02",
    enunciado: "¿Qué órganos de colaboración y apoyo del Gobierno regula el artículo 8?",
    opciones: [
      "Solo las Comisiones Delegadas del Gobierno",
      "Las Comisiones Delegadas del Gobierno, la Comisión General de Secretarios de Estado y Subsecretarios, el Secretariado del Gobierno y los Gabinetes",
      "Únicamente el Consejo de Estado",
      "Solo los Gabinetes de los Ministros",
    ],
    correcta: 1,
    explicacion: "El art. 8 enumera estos cuatro órganos de colaboración y apoyo del Gobierno.",
  },
  {
    id: "lg-03",
    enunciado: "Según el artículo 2, ¿a quién corresponde la dirección de la política interior y exterior, la Administración civil y militar y la defensa del Estado?",
    opciones: ["Al Consejo de Ministros colegiadamente", "Al Presidente del Gobierno", "Al Gobierno", "Al Ministro de Defensa"],
    correcta: 2,
    explicacion: "El art. 2.1 atribuye al Gobierno, como órgano colegiado, la dirección de la política interior y exterior, la Administración civil y militar y la defensa del Estado.",
  },
  {
    id: "lg-04",
    enunciado: "¿Cuáles son los órganos del Gobierno según el artículo 5?",
    opciones: [
      "El Consejo de Ministros y las Comisiones Delegadas del Gobierno",
      "Solo el Consejo de Ministros",
      "El Congreso y el Senado",
      "El Presidente y los Ministros individualmente",
    ],
    correcta: 0,
    explicacion: "El art. 5.1 establece que son órganos del Gobierno el Consejo de Ministros y las Comisiones Delegadas del Gobierno.",
  },
  {
    id: "lg-05",
    enunciado: "Según el artículo 6, ¿qué son las Comisiones Delegadas del Gobierno?",
    opciones: [
      "Órganos exclusivamente consultivos sin capacidad decisoria",
      "Órganos creados, modificados y suprimidos por Real Decreto del Consejo de Ministros, a propuesta del Presidente, para coordinar la elaboración de directrices en materias comunes a varios Ministerios",
      "Comisiones formadas por diputados y ministros conjuntamente",
      "Un órgano permanente regulado directamente por la Constitución",
    ],
    correcta: 1,
    explicacion: "El art. 6 regula la creación, composición y funciones de las Comisiones Delegadas del Gobierno.",
  },
  {
    id: "lg-06",
    enunciado: "Según el artículo 12, ¿a quién corresponde la representación ordinaria del Gobierno en las Comunidades Autónomas?",
    opciones: [
      "A los Subdelegados del Gobierno",
      "A los Delegados del Gobierno, sin perjuicio de la representación ordinaria del Estado en el territorio de las Comunidades Autónomas",
      "A los Presidentes autonómicos",
      "A los Ministros del ramo correspondiente",
    ],
    correcta: 1,
    explicacion: "El art. 12.1 regula la figura de los Delegados del Gobierno en las Comunidades Autónomas.",
  },
  {
    id: "lg-07",
    enunciado: "¿Cuál de los siguientes NO es requisito para ser miembro del Gobierno según el artículo 11?",
    opciones: [
      "Ser español",
      "Ser mayor de edad",
      "Disfrutar de los derechos de sufragio activo y pasivo",
      "Pertenecer al Congreso de los Diputados",
    ],
    correcta: 3,
    explicacion: "El art. 11 exige ser español, mayor de edad y disfrutar de los derechos de sufragio activo y pasivo, y no estar inhabilitado; no exige ser parlamentario.",
  },
  {
    id: "lg-08",
    enunciado: "Según el artículo 13, ¿quién asume las funciones del Presidente del Gobierno en caso de vacante, ausencia o enfermedad?",
    opciones: [
      "El Ministro de mayor antigüedad",
      "El Vicepresidente o, en su defecto, los Ministros según orden de precedencia",
      "El Presidente del Congreso de los Diputados",
      "El Rey directamente",
    ],
    correcta: 1,
    explicacion: "El art. 13.1 regula la suplencia del Presidente del Gobierno.",
  },
  {
    id: "lg-09",
    enunciado: "Según el artículo 14, ¿qué régimen de incompatibilidades rige para los miembros del Gobierno?",
    opciones: [
      "Pueden compatibilizar libremente su cargo con cualquier otra actividad",
      "Su cargo es incompatible con el ejercicio de cualquier otra función representativa, con la función pública y con cualquier actividad profesional o mercantil",
      "Solo es incompatible con otro cargo público, pero no con actividades privadas",
      "No existe régimen de incompatibilidades regulado por esta ley",
    ],
    correcta: 1,
    explicacion: "El art. 14 establece el estricto régimen de incompatibilidades de los miembros del Gobierno.",
  },
  {
    id: "lg-10",
    enunciado: "Según el artículo 21, ¿en qué supuestos el Gobierno cesante continúa en funciones?",
    opciones: [
      "Solo en caso de fallecimiento del Presidente",
      "Tras la celebración de elecciones generales, en los casos de pérdida de la confianza parlamentaria, dimisión o fallecimiento del Presidente",
      "Únicamente cuando lo solicite el Congreso",
      "Nunca; el cese es siempre inmediato y sin continuidad",
    ],
    correcta: 1,
    explicacion: "El art. 21.1 regula el Gobierno en funciones tras estos supuestos de cese, con limitación de sus facultades (art. 21.3).",
  },
  {
    id: "lg-11",
    enunciado: "¿Qué establece el artículo 22 sobre la iniciativa legislativa del Gobierno?",
    opciones: [
      "El Gobierno no tiene iniciativa legislativa",
      "El Gobierno ejerce la iniciativa legislativa mediante la elaboración y aprobación de anteproyectos de ley, que se remiten a las Cortes Generales acompañados de la documentación exigida",
      "Solo puede ejercerse a través de proposiciones de ley",
      "Requiere autorización previa del Consejo de Estado en todo caso",
    ],
    correcta: 1,
    explicacion: "El art. 22 regula la iniciativa legislativa y el procedimiento de elaboración de los anteproyectos de ley.",
  },
  {
    id: "lg-12",
    enunciado: "Según el artículo 23, ¿qué es el Plan Anual Normativo?",
    opciones: [
      "Un documento sin carácter vinculante que solo elabora el Ministerio de Justicia",
      "El instrumento en el que se recogen las iniciativas legales o reglamentarias que vayan a ser elevadas para su aprobación en el año siguiente",
      "Un plan exclusivamente presupuestario",
      "Un informe anual del Consejo de Estado",
    ],
    correcta: 1,
    explicacion: "El art. 25 (referenciado en la sección de planificación normativa) regula el Plan Anual Normativo como instrumento de planificación de la actividad normativa del Gobierno.",
  },
  {
    id: "lg-13",
    enunciado: "Según el artículo 26, ¿qué trámites incluye el procedimiento de elaboración de normas con rango de ley y reglamentos?",
    opciones: [
      "Únicamente la redacción del texto por el Ministerio proponente",
      "Consulta pública previa, elaboración del texto con memoria de análisis de impacto normativo, trámite de audiencia e información pública, e informes y dictámenes preceptivos",
      "Solo la aprobación directa por el Consejo de Ministros sin trámites previos",
      "Exclusivamente el dictamen del Consejo de Estado",
    ],
    correcta: 1,
    explicacion: "El art. 26 detalla las fases del procedimiento de elaboración de anteproyectos de ley y reglamentos.",
  },
  {
    id: "lg-14",
    enunciado: "Según el artículo 29, ¿cómo se ejerce el control del Gobierno?",
    opciones: [
      "Solo mediante la moción de censura",
      "El Gobierno está sujeto al control político de las Cortes Generales, sin perjuicio del ejercicio de la función jurisdiccional por Jueces y Tribunales y del control por el Tribunal de Cuentas",
      "Únicamente a través del Defensor del Pueblo",
      "El Gobierno no está sujeto a ningún control externo",
    ],
    correcta: 1,
    explicacion: "El art. 29 recoge los distintos mecanismos de control del Gobierno: político, jurisdiccional y económico-presupuestario.",
  },
];
