import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "lofcs-01",
    enunciado: "Según el artículo primero de la LO 2/1986, ¿a quién corresponde el mantenimiento de la Seguridad Pública, competencia exclusiva del Estado?",
    opciones: [
      "Al Ministerio del Interior en exclusiva",
      "Al Gobierno de la Nación",
      "A las Comunidades Autónomas",
      "Al Congreso de los Diputados",
    ],
    correcta: 1,
    explicacion: "El art. primero.1 establece que la Seguridad Pública es competencia exclusiva del Estado y su mantenimiento corresponde al Gobierno de la Nación.",
  },
  {
    id: "lofcs-02",
    enunciado: "¿Cuáles son, según el artículo segundo, las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "Solo el Cuerpo Nacional de Policía y la Guardia Civil",
      "Las FCS del Estado, los Cuerpos de Policía de las Comunidades Autónomas y los Cuerpos de Policía de las Corporaciones Locales",
      "Únicamente las Fuerzas Armadas",
      "Los cuerpos de seguridad privada autorizados",
    ],
    correcta: 1,
    explicacion: "El art. segundo distingue tres tipos: FCS del Estado, Cuerpos de Policía autonómicos y Cuerpos de Policía locales.",
  },
  {
    id: "lofcs-03",
    enunciado: "Según el artículo quinto (principios básicos de actuación), ¿cuándo deben utilizarse las armas los miembros de las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "Siempre que lo consideren oportuno para intimidar",
      "Solo cuando exista un riesgo racionalmente grave para su vida, su integridad física o las de terceros, o grave riesgo para la seguridad ciudadana",
      "Únicamente por orden expresa del superior jerárquico, sin más condición",
      "Nunca, salvo declaración de estado de excepción",
    ],
    correcta: 1,
    explicacion: "El art. quinto.2.d) limita el uso de armas a situaciones de riesgo racionalmente grave para la vida o integridad física propia o de terceros, o grave riesgo para la seguridad ciudadana.",
  },
  {
    id: "lofcs-04",
    enunciado: "¿Qué establece el artículo quinto sobre la obediencia debida?",
    opciones: [
      "Que ampara cualquier orden del superior sin excepción",
      "Que en ningún caso podrá amparar órdenes que entrañen actos que manifiestamente constituyan delito o sean contrarios a la Constitución o las Leyes",
      "Que solo se aplica a la Guardia Civil por su naturaleza militar",
      "Que queda derogada por esta ley",
    ],
    correcta: 1,
    explicacion: "El art. quinto.1.d) excluye expresamente de la obediencia debida las órdenes que constituyan delito o sean contrarias a la Constitución o las Leyes.",
  },
  {
    id: "lofcs-05",
    enunciado: "Según el artículo sexto, ¿pueden los miembros de las Fuerzas y Cuerpos de Seguridad ejercer el derecho de huelga?",
    opciones: [
      "Sí, sin ninguna restricción",
      "No podrán ejercerlo en ningún caso, ni acciones sustitutivas o concertadas con el fin de alterar el normal funcionamiento de los servicios",
      "Solo el Cuerpo Nacional de Policía puede ejercerlo",
      "Solo con autorización previa del Consejo de Ministros",
    ],
    correcta: 1,
    explicacion: "El art. sexto.8 prohíbe en todo caso el ejercicio del derecho de huelga y las acciones sustitutivas del mismo.",
  },
  {
    id: "lofcs-06",
    enunciado: "Según el artículo noveno, ¿cuál es la naturaleza del Cuerpo Nacional de Policía y de la Guardia Civil?",
    opciones: [
      "Ambos son Institutos Armados de naturaleza civil",
      "El CNP es un Instituto Armado de naturaleza civil y la Guardia Civil es un Instituto Armado de naturaleza militar",
      "Ambos son Institutos Armados de naturaleza militar",
      "El CNP es de naturaleza militar y la Guardia Civil de naturaleza civil",
    ],
    correcta: 1,
    explicacion: "El art. noveno distingue: el CNP es un Instituto Armado de naturaleza civil, dependiente del Ministro del Interior; la Guardia Civil es un Instituto Armado de naturaleza militar.",
  },
  {
    id: "lofcs-07",
    enunciado: "Según el artículo once, ¿en qué ámbito territorial ejerce sus funciones el Cuerpo Nacional de Policía, con carácter general?",
    opciones: [
      "En todo el territorio nacional sin distinción",
      "En las capitales de provincia y en los términos municipales y núcleos urbanos que el Gobierno determine",
      "Exclusivamente en la Comunidad de Madrid",
      "Solo en las fronteras y puertos",
    ],
    correcta: 1,
    explicacion: "El art. once.2.a) atribuye al CNP el ejercicio de sus funciones en capitales de provincia y en los términos municipales y núcleos urbanos que determine el Gobierno; la Guardia Civil actúa en el resto del territorio.",
  },
  {
    id: "lofcs-08",
    enunciado: "¿Cuál de las siguientes competencias corresponde en exclusiva al Cuerpo Nacional de Policía según el artículo doce?",
    opciones: [
      "El resguardo fiscal del Estado",
      "La expedición del documento nacional de identidad y de los pasaportes",
      "La vigilancia del tráfico interurbano",
      "La conducción interurbana de presos y detenidos",
    ],
    correcta: 1,
    explicacion: "El art. doce.1.A).a) atribuye al CNP la expedición del DNI y los pasaportes; las otras opciones corresponden a la Guardia Civil según el art. doce.1.B).",
  },
  {
    id: "lofcs-09",
    enunciado: "Según el artículo doce, ¿qué competencia corresponde en exclusiva a la Guardia Civil?",
    opciones: [
      "El control de entrada y salida del territorio nacional",
      "La investigación de los delitos relacionados con la droga",
      "La vigilancia del tráfico, tránsito y transporte en las vías públicas interurbanas",
      "El control de las entidades de seguridad privada",
    ],
    correcta: 2,
    explicacion: "El art. doce.1.B).c) atribuye a la Guardia Civil la vigilancia del tráfico, tránsito y transporte en las vías públicas interurbanas.",
  },
  {
    id: "lofcs-10",
    enunciado: "¿Qué órganos, según el artículo veintinueve, ejercen las funciones de Policía Judicial mencionadas en el artículo 126 de la Constitución?",
    opciones: [
      "Solo los Juzgados de Instrucción",
      "Las Fuerzas y Cuerpos de Seguridad del Estado, a través de las Unidades de Policía Judicial que se regulan en la Ley",
      "Exclusivamente el Ministerio Fiscal",
      "Las Policías Locales en exclusiva",
    ],
    correcta: 1,
    explicacion: "El art. veintinueve.1 atribuye estas funciones a las FCS del Estado a través de las Unidades reguladas en el capítulo V.",
  },
  {
    id: "lofcs-11",
    enunciado: "En el cumplimiento de sus funciones, ¿de quién dependen orgánica y funcionalmente los funcionarios adscritos a Unidades de Policía Judicial, según el artículo treinta y uno?",
    opciones: [
      "Dependen orgánicamente del Ministerio del Interior y funcionalmente de los Jueces, Tribunales o Ministerio Fiscal que conozcan del asunto",
      "Dependen exclusivamente del Ministerio Fiscal",
      "Dependen únicamente del Consejo General del Poder Judicial",
      "No tienen ninguna dependencia funcional distinta de la orgánica",
    ],
    correcta: 0,
    explicacion: "El art. treinta y uno.1 establece esta doble dependencia: orgánica del Ministerio del Interior y funcional de la autoridad judicial o fiscal que dirige la investigación.",
  },
  {
    id: "lofcs-12",
    enunciado: "Según el Real Decreto 769/1987 sobre regulación de la Policía Judicial, ¿qué se entiende por Unidades Orgánicas de Policía Judicial?",
    opciones: [
      "Cualquier funcionario policial que participe puntualmente en una investigación",
      "Las unidades integradas por miembros del CNP y de la Guardia Civil presididas por principios de permanencia, estabilidad, especialización y dependencia funcional de Jueces, Tribunales y Ministerio Fiscal",
      "Las unidades formadas exclusivamente por miembros de la Guardia Civil",
      "Las unidades de las Policías Locales especializadas en tráfico",
    ],
    correcta: 1,
    explicacion: "El preámbulo y el art. 7 del RD 769/1987 definen la Policía Judicial en sentido estricto como estas Unidades Orgánicas, con esos principios característicos.",
  },
  {
    id: "lofcs-13",
    enunciado: "¿Qué Comunidades Autónomas pueden crear Cuerpos de Policía propios según el artículo treinta y siete?",
    opciones: [
      "Todas las Comunidades Autónomas sin excepción",
      "Aquellas en cuyos Estatutos de Autonomía esté prevista dicha posibilidad",
      "Solo las que tengan lengua cooficial",
      "Ninguna, es competencia exclusiva del Estado",
    ],
    correcta: 1,
    explicacion: "El art. treinta y siete.1 reserva la creación de Cuerpos de Policía autonómicos a aquellas Comunidades Autónomas cuyos Estatutos lo prevean.",
  },
  {
    id: "lofcs-14",
    enunciado: "Según el artículo cuarenta y ocho, ¿qué órgano garantiza la coordinación entre las políticas de seguridad pública del Estado y de las Comunidades Autónomas?",
    opciones: [
      "El Consejo de Política de Seguridad, presidido por el Ministro del Interior",
      "El Consejo de Ministros",
      "El Tribunal Constitucional",
      "La Conferencia de Presidentes",
    ],
    correcta: 0,
    explicacion: "El art. cuarenta y ocho.1 crea el Consejo de Política de Seguridad, presidido por el Ministro del Interior e integrado por los Consejeros de Interior o Gobernación autonómicos.",
  },
  {
    id: "lofcs-15",
    enunciado: "Según el artículo cincuenta y tres, ¿cuál de las siguientes es una función de los Cuerpos de Policía Local?",
    opciones: [
      "El resguardo fiscal del Estado",
      "Ordenar, señalizar y dirigir el tráfico en el casco urbano de acuerdo con las normas de circulación",
      "La investigación de delitos de terrorismo",
      "El control de fronteras y aeropuertos",
    ],
    correcta: 1,
    explicacion: "El art. cincuenta y tres.1.b) atribuye a las Policías Locales la ordenación, señalización y dirección del tráfico en el casco urbano.",
  },
  {
    id: "lofcs-16",
    enunciado: "Según el artículo cuarto de la LO 2/1986, ¿existe un deber de colaboración de los ciudadanos con las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "No, la colaboración es siempre voluntaria y sin ningún respaldo legal",
      "Sí, todos tienen el deber de prestarles el auxilio necesario en la investigación y persecución de los delitos, en los términos previstos por la ley",
      "Solo están obligados los funcionarios públicos",
      "Solo existe ese deber durante los estados de alarma, excepción o sitio",
    ],
    correcta: 1,
    explicacion: "El art. cuarto de la LO 2/1986 establece que todos tienen el deber de prestar a las Fuerzas y Cuerpos de Seguridad el auxilio necesario en la investigación y persecución de los delitos, en los términos que establezca la ley.",
  },
  {
    id: "lofcs-17",
    enunciado: "Según los principios básicos de actuación del artículo quinto de la LO 2/1986, ¿cómo deben tratar los miembros de las Fuerzas y Cuerpos de Seguridad a los ciudadanos?",
    opciones: [
      "Con la mayor discrecionalidad posible, sin ningún criterio uniforme",
      "Con un trato correcto y esmerado en sus relaciones con los ciudadanos, cuidando especialmente el uso correcto del idioma",
      "Solo deben trato correcto a las autoridades, no a los particulares",
      "El trato dispensado no está regulado por esta ley",
    ],
    correcta: 1,
    explicacion: "El art. quinto.2.b) LO 2/1986 exige a los miembros de las Fuerzas y Cuerpos de Seguridad observar en todo momento un trato correcto y esmerado en sus relaciones con los ciudadanos, cuidando especialmente el idioma que utilicen.",
  },
  {
    id: "lofcs-18",
    enunciado: "Según el artículo quinto de la LO 2/1986, ¿qué deber tienen los miembros de las Fuerzas y Cuerpos de Seguridad respecto de las personas en peligro?",
    opciones: [
      "Ninguno, salvo que reciban orden expresa",
      "Auxiliar y proteger a las personas en peligro, en cualquier tiempo y lugar",
      "Solo auxiliarlas dentro de su horario de servicio",
      "Solo si la persona en peligro lo solicita expresamente por escrito",
    ],
    correcta: 1,
    explicacion: "El art. quinto.2.d) LO 2/1986 impone a los miembros de las Fuerzas y Cuerpos de Seguridad el deber de auxiliar y proteger a las personas, asegurando la protección y socorro a quienes, en cualquier tiempo y lugar, se encuentren en situación de peligro.",
  },
  {
    id: "lofcs-19",
    enunciado: "Según el artículo quinto de la LO 2/1986, ¿a qué obliga el deber de secreto profesional?",
    opciones: [
      "A guardar riguroso secreto respecto de todas las informaciones que conozcan por razón o con ocasión del desempeño de sus funciones",
      "Únicamente a no comentar información con la prensa, pudiendo divulgarla libremente por otros medios",
      "Solo se aplica a los mandos superiores",
      "No existe deber de secreto profesional en esta ley",
    ],
    correcta: 0,
    explicacion: "El art. quinto.5 LO 2/1986 obliga a los miembros de las Fuerzas y Cuerpos de Seguridad a guardar riguroso secreto respecto de todas las informaciones que conozcan por razón o con ocasión del desempeño de sus funciones, sin que este deber cese al pasar a la situación de retiro o al abandonar el servicio.",
  },
  {
    id: "lofcs-20",
    enunciado: "¿Qué significa el principio de \"dedicación profesional\" recogido en el artículo quinto de la LO 2/1986?",
    opciones: [
      "Que solo deben intervenir en asuntos de seguridad dentro de su horario de servicio",
      "Que deben llevar a cabo sus funciones con total dedicación, debiendo intervenir siempre, se hallen o no de servicio, en defensa de la ley y de la seguridad ciudadana, dentro de los límites de la ley",
      "Que solo pueden dedicarse a labores administrativas",
      "Que la dedicación profesional es incompatible con cualquier tipo de descanso",
    ],
    correcta: 1,
    explicacion: "El art. quinto.4 LO 2/1986 exige a los miembros de las Fuerzas y Cuerpos de Seguridad llevar a cabo sus funciones con total dedicación, debiendo intervenir siempre, se hallen o no de servicio, en defensa de la ley y de la seguridad ciudadana, dentro de los límites establecidos por la ley.",
  },
  {
    id: "lofcs-21",
    enunciado: "Según el artículo sexto de la LO 2/1986, ¿pueden los miembros del Cuerpo Nacional de Policía afiliarse a cualquier sindicato?",
    opciones: [
      "Sí, a cualquier sindicato sin restricción alguna",
      "No; solo pueden constituir y afiliarse a organizaciones sindicales de naturaleza exclusivamente policial, prohibiéndose la afiliación a otros sindicatos o asociaciones profesionales",
      "No pueden afiliarse a ningún tipo de organización sindical",
      "Solo pueden afiliarse a partidos políticos",
    ],
    correcta: 1,
    explicacion: "El art. sexto LO 2/1986 reconoce a los miembros del CNP el derecho a constituir y afiliarse a organizaciones sindicales, pero exclusivamente de ámbito policial, quedando prohibida su afiliación a otros sindicatos o asociaciones profesionales no específicamente policiales.",
  },
  {
    id: "lofcs-22",
    enunciado: "¿Qué es el Consejo de Policía, previsto en el artículo sexto de la LO 2/1986?",
    opciones: [
      "El órgano de mando operativo del Cuerpo Nacional de Policía",
      "El órgano de participación de los miembros del CNP en la determinación de sus condiciones de trabajo",
      "Un tribunal disciplinario de última instancia",
      "El órgano que sustituye al Ministro del Interior en su ausencia",
    ],
    correcta: 1,
    explicacion: "El Consejo de Policía, regulado en el marco del art. sexto LO 2/1986, es el órgano de participación de los funcionarios del Cuerpo Nacional de Policía en la determinación de sus condiciones de trabajo.",
  },
  {
    id: "lofcs-23",
    enunciado: "Según el artículo octavo de la LO 2/1986, ¿qué son las Juntas Locales de Seguridad?",
    opciones: [
      "Órganos judiciales de ámbito municipal",
      "Órganos de colaboración entre las Fuerzas y Cuerpos de Seguridad del Estado y los Cuerpos de Policía Local, presididos por el Alcalde del municipio correspondiente",
      "Un cuerpo especial de la Guardia Civil",
      "Órganos exclusivos de las Comunidades Autónomas insulares",
    ],
    correcta: 1,
    explicacion: "El art. octavo LO 2/1986 prevé la constitución de Juntas Locales de Seguridad, presididas por el Alcalde, como órganos de colaboración entre las Fuerzas y Cuerpos de Seguridad del Estado y los Cuerpos de Policía Local.",
  },
  {
    id: "lofcs-24",
    enunciado: "Según el artículo séptimo de la LO 2/1986, ¿cómo deben relacionarse entre sí el Cuerpo Nacional de Policía y la Guardia Civil?",
    opciones: [
      "No existe previsión legal alguna sobre su relación mutua",
      "En sus relaciones recíprocas actuarán bajo los principios de cooperación recíproca y coordinación, mediante el intercambio de información especialmente en materia de la lucha contra la delincuencia",
      "En permanente competencia, sin ningún deber de colaboración",
      "La Guardia Civil está subordinada jerárquicamente al Cuerpo Nacional de Policía",
    ],
    correcta: 1,
    explicacion: "El art. séptimo LO 2/1986 establece que en sus actuaciones el CNP y la Guardia Civil se coordinarán, sin perjuicio de sus respectivas competencias, actuando conforme a los principios de cooperación recíproca y coordinación, especialmente mediante el intercambio de información útil para el desempeño eficaz de sus funciones.",
  },
  {
    id: "lofcs-25",
    enunciado: "Según el artículo décimo de la LO 2/1986, ¿cuál es una función común a todas las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "El resguardo fiscal del Estado, en exclusiva",
      "Auxiliar y proteger a las personas y asegurar la conservación y custodia de los bienes que se encuentren en situación de peligro por cualquier causa",
      "La expedición del DNI y pasaportes, en exclusiva",
      "La representación diplomática del Estado en el extranjero",
    ],
    correcta: 1,
    explicacion: "El art. décimo LO 2/1986 enumera las funciones comunes a todas las Fuerzas y Cuerpos de Seguridad (estatales, autonómicas y locales), entre ellas auxiliar y proteger a las personas y asegurar la conservación y custodia de los bienes que se encuentren en situación de peligro por cualquier causa.",
  },
  {
    id: "lofcs-26",
    enunciado: "Según el artículo doce de la LO 2/1986, ¿qué función corresponde en exclusiva a la Guardia Civil en materia económica?",
    opciones: [
      "El resguardo fiscal del Estado y las actuaciones encaminadas a evitar y perseguir el contrabando",
      "La supervisión del Banco de España",
      "La emisión de moneda",
      "La gestión de los tributos estatales",
    ],
    correcta: 0,
    explicacion: "El art. doce.1.B).f) LO 2/1986 atribuye a la Guardia Civil, entre sus competencias exclusivas, el resguardo fiscal del Estado y las actuaciones encaminadas a evitar y perseguir el contrabando.",
  },
  {
    id: "lofcs-27",
    enunciado: "Según el artículo treinta y ocho de la LO 2/1986, ¿cuál es una función propia de los Cuerpos de Policía de las Comunidades Autónomas?",
    opciones: [
      "La expedición del DNI y pasaportes",
      "La vigilancia y protección de personas, órganos, edificios, establecimientos y dependencias de la Comunidad Autónoma correspondiente y de sus entes instrumentales",
      "El control de entrada y salida del territorio nacional",
      "La investigación de delitos de terrorismo en todo el territorio nacional",
    ],
    correcta: 1,
    explicacion: "El art. treinta y ocho.1.a) LO 2/1986 atribuye a las Policías de las Comunidades Autónomas la vigilancia y protección de personas, órganos, edificios, establecimientos y dependencias de la Comunidad Autónoma y de sus entes instrumentales.",
  },
  {
    id: "lofcs-28",
    enunciado: "Según el artículo cincuenta y tres de la LO 2/1986, ¿cuál es una función propia de los Cuerpos de Policía Local además de la ordenación del tráfico?",
    opciones: [
      "Proteger a las autoridades de las Corporaciones Locales y vigilar o custodiar sus edificios e instalaciones",
      "El control de fronteras marítimas",
      "La investigación de delitos monetarios",
      "La expedición de pasaportes",
    ],
    correcta: 0,
    explicacion: "El art. cincuenta y tres.1.a) LO 2/1986 atribuye a las Policías Locales, entre otras funciones, proteger a las autoridades de las Corporaciones Locales y vigilar o custodiar sus edificios e instalaciones.",
  },
  {
    id: "lofcs-29",
    enunciado: "Según el artículo cincuenta y tres de la LO 2/1986, ¿participan los Cuerpos de Policía Local en tareas de protección civil?",
    opciones: [
      "No, esa función corresponde en exclusiva a las Fuerzas Armadas",
      "Sí, participan en la prestación de auxilio en los casos de accidente, catástrofe o calamidad pública, colaborando en la forma prevista en las leyes",
      "Solo pueden participar si media declaración de estado de excepción",
      "Únicamente pueden colaborar si lo autoriza expresamente el Ministro del Interior en cada caso",
    ],
    correcta: 1,
    explicacion: "El art. cincuenta y tres.1.i) LO 2/1986 incluye entre las funciones de los Cuerpos de Policía Local participar en la prestación de auxilio en los casos de accidente, catástrofe o calamidad pública, colaborando en la forma prevista en las leyes.",
  },
  {
    id: "lofcs-30",
    enunciado: "¿Qué requisito exige, con carácter general, la LO 2/1986 para que una Comunidad Autónoma pueda crear un Cuerpo de Policía propio?",
    opciones: [
      "Que lo solicite directamente al Ministerio del Interior sin más trámite",
      "Que esté previsto en su Estatuto de Autonomía y se cree mediante Ley de su Parlamento autonómico",
      "Ninguno, cualquier Comunidad Autónoma puede crear libremente su propio Cuerpo",
      "Que exista declarado un estado de alarma en su territorio",
    ],
    correcta: 1,
    explicacion: "Conforme a los arts. treinta y siete y treinta y ocho LO 2/1986, solo pueden crear Cuerpos de Policía propios las Comunidades Autónomas cuyos Estatutos de Autonomía prevean esa posibilidad, y su creación se realiza mediante Ley aprobada por el Parlamento autonómico correspondiente.",
  },
];
