import type { Pregunta } from "@/lib/preguntas";

export const preguntas: Pregunta[] = [
  {
    id: "lofcs-01",
    enunciado: "Según el artículo primero de la LO 2/1986, ¿a quién corresponde el mantenimiento de la Seguridad Pública, competencia exclusiva del Estado?",
    opciones: [
      "Al Ministerio del Interior en exclusiva",
      "Al Gobierno de la Nación",
      "A las Comunidades Autónomas",
      "Al Congreso de los Diputados",
    ],
    correcta: 1,
    explicacion: "El art. primero.1 establece que la Seguridad Pública es competencia exclusiva del Estado y su mantenimiento corresponde al Gobierno de la Nación.",
  },
  {
    id: "lofcs-02",
    enunciado: "¿Cuáles son, según el artículo segundo, las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "Solo el Cuerpo Nacional de Policía y la Guardia Civil",
      "Las FCS del Estado, los Cuerpos de Policía de las Comunidades Autónomas y los Cuerpos de Policía de las Corporaciones Locales",
      "Únicamente las Fuerzas Armadas",
      "Los cuerpos de seguridad privada autorizados",
    ],
    correcta: 1,
    explicacion: "El art. segundo distingue tres tipos: FCS del Estado, Cuerpos de Policía autonómicos y Cuerpos de Policía locales.",
  },
  {
    id: "lofcs-03",
    enunciado: "Según el artículo quinto (principios básicos de actuación), ¿cuándo deben utilizarse las armas los miembros de las Fuerzas y Cuerpos de Seguridad?",
    opciones: [
      "Siempre que lo consideren oportuno para intimidar",
      "Solo cuando exista un riesgo racionalmente grave para su vida, su integridad física o las de terceros, o grave riesgo para la seguridad ciudadana",
      "Únicamente por orden expresa del superior jerárquico, sin más condición",
      "Nunca, salvo declaración de estado de excepción",
    ],
    correcta: 1,
    explicacion: "El art. quinto.2.d) limita el uso de armas a situaciones de riesgo racionalmente grave para la vida o integridad física propia o de terceros, o grave riesgo para la seguridad ciudadana.",
  },
  {
    id: "lofcs-04",
    enunciado: "¿Qué establece el artículo quinto sobre la obediencia debida?",
    opciones: [
      "Que ampara cualquier orden del superior sin excepción",
      "Que en ningún caso podrá amparar órdenes que entrañen actos que manifiestamente constituyan delito o sean contrarios a la Constitución o las Leyes",
      "Que solo se aplica a la Guardia Civil por su naturaleza militar",
      "Que queda derogada por esta ley",
    ],
    correcta: 1,
    explicacion: "El art. quinto.1.d) excluye expresamente de la obediencia debida las órdenes que constituyan delito o sean contrarias a la Constitución o las Leyes.",
  },
  {
    id: "lofcs-05",
    enunciado: "Según el artículo sexto, ¿pueden los miembros de las Fuerzas y Cuerpos de Seguridad ejercer el derecho de huelga?",
    opciones: [
      "Sí, sin ninguna restricción",
      "No podrán ejercerlo en ningún caso, ni acciones sustitutivas o concertadas con el fin de alterar el normal funcionamiento de los servicios",
      "Solo el Cuerpo Nacional de Policía puede ejercerlo",
      "Solo con autorización previa del Consejo de Ministros",
    ],
    correcta: 1,
    explicacion: "El art. sexto.8 prohíbe en todo caso el ejercicio del derecho de huelga y las acciones sustitutivas del mismo.",
  },
  {
    id: "lofcs-06",
    enunciado: "Según el artículo noveno, ¿cuál es la naturaleza del Cuerpo Nacional de Policía y de la Guardia Civil?",
    opciones: [
      "Ambos son Institutos Armados de naturaleza civil",
      "El CNP es un Instituto Armado de naturaleza civil y la Guardia Civil es un Instituto Armado de naturaleza militar",
      "Ambos son Institutos Armados de naturaleza militar",
      "El CNP es de naturaleza militar y la Guardia Civil de naturaleza civil",
    ],
    correcta: 1,
    explicacion: "El art. noveno distingue: el CNP es un Instituto Armado de naturaleza civil, dependiente del Ministro del Interior; la Guardia Civil es un Instituto Armado de naturaleza militar.",
  },
  {
    id: "lofcs-07",
    enunciado: "Según el artículo once, ¿en qué ámbito territorial ejerce sus funciones el Cuerpo Nacional de Policía, con carácter general?",
    opciones: [
      "En todo el territorio nacional sin distinción",
      "En las capitales de provincia y en los términos municipales y núcleos urbanos que el Gobierno determine",
      "Exclusivamente en la Comunidad de Madrid",
      "Solo en las fronteras y puertos",
    ],
    correcta: 1,
    explicacion: "El art. once.2.a) atribuye al CNP el ejercicio de sus funciones en capitales de provincia y en los términos municipales y núcleos urbanos que determine el Gobierno; la Guardia Civil actúa en el resto del territorio.",
  },
  {
    id: "lofcs-08",
    enunciado: "¿Cuál de las siguientes competencias corresponde en exclusiva al Cuerpo Nacional de Policía según el artículo doce?",
    opciones: [
      "El resguardo fiscal del Estado",
      "La expedición del documento nacional de identidad y de los pasaportes",
      "La vigilancia del tráfico interurbano",
      "La conducción interurbana de presos y detenidos",
    ],
    correcta: 1,
    explicacion: "El art. doce.1.A).a) atribuye al CNP la expedición del DNI y los pasaportes; las otras opciones corresponden a la Guardia Civil según el art. doce.1.B).",
  },
  {
    id: "lofcs-09",
    enunciado: "Según el artículo doce, ¿qué competencia corresponde en exclusiva a la Guardia Civil?",
    opciones: [
      "El control de entrada y salida del territorio nacional",
      "La investigación de los delitos relacionados con la droga",
      "La vigilancia del tráfico, tránsito y transporte en las vías públicas interurbanas",
      "El control de las entidades de seguridad privada",
    ],
    correcta: 2,
    explicacion: "El art. doce.1.B).c) atribuye a la Guardia Civil la vigilancia del tráfico, tránsito y transporte en las vías públicas interurbanas.",
  },
  {
    id: "lofcs-10",
    enunciado: "¿Qué órganos, según el artículo veintinueve, ejercen las funciones de Policía Judicial mencionadas en el artículo 126 de la Constitución?",
    opciones: [
      "Solo los Juzgados de Instrucción",
      "Las Fuerzas y Cuerpos de Seguridad del Estado, a través de las Unidades de Policía Judicial que se regulan en la Ley",
      "Exclusivamente el Ministerio Fiscal",
      "Las Policías Locales en exclusiva",
    ],
    correcta: 1,
    explicacion: "El art. veintinueve.1 atribuye estas funciones a las FCS del Estado a través de las Unidades reguladas en el capítulo V.",
  },
  {
    id: "lofcs-11",
    enunciado: "En el cumplimiento de sus funciones, ¿de quién dependen orgánica y funcionalmente los funcionarios adscritos a Unidades de Policía Judicial, según el artículo treinta y uno?",
    opciones: [
      "Dependen orgánicamente del Ministerio del Interior y funcionalmente de los Jueces, Tribunales o Ministerio Fiscal que conozcan del asunto",
      "Dependen exclusivamente del Ministerio Fiscal",
      "Dependen únicamente del Consejo General del Poder Judicial",
      "No tienen ninguna dependencia funcional distinta de la orgánica",
    ],
    correcta: 0,
    explicacion: "El art. treinta y uno.1 establece esta doble dependencia: orgánica del Ministerio del Interior y funcional de la autoridad judicial o fiscal que dirige la investigación.",
  },
  {
    id: "lofcs-12",
    enunciado: "Según el Real Decreto 769/1987 sobre regulación de la Policía Judicial, ¿qué se entiende por Unidades Orgánicas de Policía Judicial?",
    opciones: [
      "Cualquier funcionario policial que participe puntualmente en una investigación",
      "Las unidades integradas por miembros del CNP y de la Guardia Civil presididas por principios de permanencia, estabilidad, especialización y dependencia funcional de Jueces, Tribunales y Ministerio Fiscal",
      "Las unidades formadas exclusivamente por miembros de la Guardia Civil",
      "Las unidades de las Policías Locales especializadas en tráfico",
    ],
    correcta: 1,
    explicacion: "El preámbulo y el art. 7 del RD 769/1987 definen la Policía Judicial en sentido estricto como estas Unidades Orgánicas, con esos principios característicos.",
  },
  {
    id: "lofcs-13",
    enunciado: "¿Qué Comunidades Autónomas pueden crear Cuerpos de Policía propios según el artículo treinta y siete?",
    opciones: [
      "Todas las Comunidades Autónomas sin excepción",
      "Aquellas en cuyos Estatutos de Autonomía esté prevista dicha posibilidad",
      "Solo las que tengan lengua cooficial",
      "Ninguna, es competencia exclusiva del Estado",
    ],
    correcta: 1,
    explicacion: "El art. treinta y siete.1 reserva la creación de Cuerpos de Policía autonómicos a aquellas Comunidades Autónomas cuyos Estatutos lo prevean.",
  },
  {
    id: "lofcs-14",
    enunciado: "Según el artículo cuarenta y ocho, ¿qué órgano garantiza la coordinación entre las políticas de seguridad pública del Estado y de las Comunidades Autónomas?",
    opciones: [
      "El Consejo de Política de Seguridad, presidido por el Ministro del Interior",
      "El Consejo de Ministros",
      "El Tribunal Constitucional",
      "La Conferencia de Presidentes",
    ],
    correcta: 0,
    explicacion: "El art. cuarenta y ocho.1 crea el Consejo de Política de Seguridad, presidido por el Ministro del Interior e integrado por los Consejeros de Interior o Gobernación autonómicos.",
  },
  {
    id: "lofcs-15",
    enunciado: "Según el artículo cincuenta y tres, ¿cuál de las siguientes es una función de los Cuerpos de Policía Local?",
    opciones: [
      "El resguardo fiscal del Estado",
      "Ordenar, señalizar y dirigir el tráfico en el casco urbano de acuerdo con las normas de circulación",
      "La investigación de delitos de terrorismo",
      "El control de fronteras y aeropuertos",
    ],
    correcta: 1,
    explicacion: "El art. cincuenta y tres.1.b) atribuye a las Policías Locales la ordenación, señalización y dirección del tráfico en el casco urbano.",
  },
];
